/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.CompatibilityCore
public import HexConway.CompatibilityProofs.S0_3

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Compatibility of C(967, 1) with C(967, 2). -/
theorem compat_967_1_2 :
    Compatible 967 1 2 supportedEntry_967_1 supportedEntry_967_2 := by decide +kernel

/-- Compatibility of C(311, 1) with C(311, 2). -/
theorem compat_311_1_2 :
    Compatible 311 1 2 supportedEntry_311_1 supportedEntry_311_2 := by decide +kernel

/-- Compatibility of C(373, 1) with C(373, 2). -/
theorem compat_373_1_2 :
    Compatible 373 1 2 supportedEntry_373_1 supportedEntry_373_2 := by decide +kernel

/-- Compatibility of C(421, 1) with C(421, 2). -/
theorem compat_421_1_2 :
    Compatible 421 1 2 supportedEntry_421_1 supportedEntry_421_2 := by decide +kernel

/-- Compatibility of C(491, 1) with C(491, 2). -/
theorem compat_491_1_2 :
    Compatible 491 1 2 supportedEntry_491_1 supportedEntry_491_2 := by decide +kernel

/-- Compatibility of C(139, 1) with C(139, 2). -/
theorem compat_139_1_2 :
    Compatible 139 1 2 supportedEntry_139_1 supportedEntry_139_2 := by decide +kernel

/-- Compatibility of C(239, 1) with C(239, 2). -/
theorem compat_239_1_2 :
    Compatible 239 1 2 supportedEntry_239_1 supportedEntry_239_2 := by decide +kernel

/-- Compatibility of C(563, 1) with C(563, 2). -/
theorem compat_563_1_2 :
    Compatible 563 1 2 supportedEntry_563_1 supportedEntry_563_2 := by decide +kernel

/-- Compatibility of C(613, 1) with C(613, 2). -/
theorem compat_613_1_2 :
    Compatible 613 1 2 supportedEntry_613_1 supportedEntry_613_2 := by decide +kernel

/-- Compatibility of C(673, 1) with C(673, 2). -/
theorem compat_673_1_2 :
    Compatible 673 1 2 supportedEntry_673_1 supportedEntry_673_2 := by decide +kernel

/-- Compatibility of C(751, 1) with C(751, 2). -/
theorem compat_751_1_2 :
    Compatible 751 1 2 supportedEntry_751_1 supportedEntry_751_2 := by decide +kernel

/-- Compatibility of C(809, 1) with C(809, 2). -/
theorem compat_809_1_2 :
    Compatible 809 1 2 supportedEntry_809_1 supportedEntry_809_2 := by decide +kernel

/-- Compatibility of C(907, 1) with C(907, 2). -/
theorem compat_907_1_2 :
    Compatible 907 1 2 supportedEntry_907_1 supportedEntry_907_2 := by decide +kernel

/-- Compatibility of C(997, 1) with C(997, 2). -/
theorem compat_997_1_2 :
    Compatible 997 1 2 supportedEntry_997_1 supportedEntry_997_2 := by decide +kernel

/-- Compatibility of C(283, 1) with C(283, 2). -/
theorem compat_283_1_2 :
    Compatible 283 1 2 supportedEntry_283_1 supportedEntry_283_2 := by decide +kernel

/-- Compatibility of C(337, 1) with C(337, 2). -/
theorem compat_337_1_2 :
    Compatible 337 1 2 supportedEntry_337_1 supportedEntry_337_2 := by decide +kernel

/-- Compatibility of C(367, 1) with C(367, 2). -/
theorem compat_367_1_2 :
    Compatible 367 1 2 supportedEntry_367_1 supportedEntry_367_2 := by decide +kernel

/-- Compatibility of C(433, 1) with C(433, 2). -/
theorem compat_433_1_2 :
    Compatible 433 1 2 supportedEntry_433_1 supportedEntry_433_2 := by decide +kernel

/-- Compatibility of C(479, 1) with C(479, 2). -/
theorem compat_479_1_2 :
    Compatible 479 1 2 supportedEntry_479_1 supportedEntry_479_2 := by decide +kernel

/-- Compatibility of C(2, 1) with C(2, 4). -/
theorem compat_2_1_4 :
    Compatible 2 1 4 supportedEntry_2_1 supportedEntry_2_4 := by decide +kernel

/-- Compatibility of C(2, 2) with C(2, 4). -/
theorem compat_2_2_4 :
    Compatible 2 2 4 supportedEntry_2_2 supportedEntry_2_4 := by decide +kernel

/-- Compatibility of C(149, 1) with C(149, 2). -/
theorem compat_149_1_2 :
    Compatible 149 1 2 supportedEntry_149_1 supportedEntry_149_2 := by decide +kernel

/-- Compatibility of C(173, 1) with C(173, 2). -/
theorem compat_173_1_2 :
    Compatible 173 1 2 supportedEntry_173_1 supportedEntry_173_2 := by decide +kernel

/-- Compatibility of C(199, 1) with C(199, 2). -/
theorem compat_199_1_2 :
    Compatible 199 1 2 supportedEntry_199_1 supportedEntry_199_2 := by decide +kernel


end Conway

end Hex
