/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.CompatibilityCore
public import HexConway.CompatibilityProofs.S1_0

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Compatibility of C(67, 2) with C(67, 4). -/
theorem compat_67_2_4 :
    Compatible 67 2 4 supportedEntry_67_2 supportedEntry_67_4 := by decide +kernel

/-- Compatibility of C(89, 2) with C(89, 4). -/
theorem compat_89_2_4 :
    Compatible 89 2 4 supportedEntry_89_2 supportedEntry_89_4 := by decide +kernel

/-- Compatibility of C(109, 2) with C(109, 4). -/
theorem compat_109_2_4 :
    Compatible 109 2 4 supportedEntry_109_2 supportedEntry_109_4 := by decide +kernel

/-- Compatibility of C(5, 2) with C(5, 6). -/
theorem compat_5_2_6 :
    Compatible 5 2 6 supportedEntry_5_2 supportedEntry_5_6 := by decide +kernel

/-- Compatibility of C(7, 3) with C(7, 6). -/
theorem compat_7_3_6 :
    Compatible 7 3 6 supportedEntry_7_3 supportedEntry_7_6 := by decide +kernel

/-- Compatibility of C(193, 2) with C(193, 4). -/
theorem compat_193_2_4 :
    Compatible 193 2 4 supportedEntry_193_2 supportedEntry_193_4 := by decide +kernel

/-- Compatibility of C(43, 2) with C(43, 4). -/
theorem compat_43_2_4 :
    Compatible 43 2 4 supportedEntry_43_2 supportedEntry_43_4 := by decide +kernel

/-- Compatibility of C(71, 1) with C(71, 4). -/
theorem compat_71_1_4 :
    Compatible 71 1 4 supportedEntry_71_1 supportedEntry_71_4 := by decide +kernel

/-- Compatibility of C(97, 1) with C(97, 4). -/
theorem compat_97_1_4 :
    Compatible 97 1 4 supportedEntry_97_1 supportedEntry_97_4 := by decide +kernel

/-- Compatibility of C(107, 1) with C(107, 4). -/
theorem compat_107_1_4 :
    Compatible 107 1 4 supportedEntry_107_1 supportedEntry_107_4 := by decide +kernel

/-- Compatibility of C(5, 1) with C(5, 7). -/
theorem compat_5_1_7 :
    Compatible 5 1 7 supportedEntry_5_1 supportedEntry_5_7 := by decide +kernel

/-- Compatibility of C(41, 1) with C(41, 4). -/
theorem compat_41_1_4 :
    Compatible 41 1 4 supportedEntry_41_1 supportedEntry_41_4 := by decide +kernel

/-- Compatibility of C(59, 1) with C(59, 4). -/
theorem compat_59_1_4 :
    Compatible 59 1 4 supportedEntry_59_1 supportedEntry_59_4 := by decide +kernel

/-- Compatibility of C(571, 1) with C(571, 3). -/
theorem compat_571_1_3 :
    Compatible 571 1 3 supportedEntry_571_1 supportedEntry_571_3 := by decide +kernel

/-- Compatibility of C(631, 1) with C(631, 3). -/
theorem compat_631_1_3 :
    Compatible 631 1 3 supportedEntry_631_1 supportedEntry_631_3 := by decide +kernel

/-- Compatibility of C(821, 1) with C(821, 3). -/
theorem compat_821_1_3 :
    Compatible 821 1 3 supportedEntry_821_1 supportedEntry_821_3 := by decide +kernel

/-- Compatibility of C(967, 1) with C(967, 3). -/
theorem compat_967_1_3 :
    Compatible 967 1 3 supportedEntry_967_1 supportedEntry_967_3 := by decide +kernel

/-- Compatibility of C(23, 2) with C(23, 4). -/
theorem compat_23_2_4 :
    Compatible 23 2 4 supportedEntry_23_2 supportedEntry_23_4 := by decide +kernel

/-- Compatibility of C(31, 2) with C(31, 4). -/
theorem compat_31_2_4 :
    Compatible 31 2 4 supportedEntry_31_2 supportedEntry_31_4 := by decide +kernel

/-- Compatibility of C(331, 1) with C(331, 3). -/
theorem compat_331_1_3 :
    Compatible 331 1 3 supportedEntry_331_1 supportedEntry_331_3 := by decide +kernel

/-- Compatibility of C(3, 1) with C(3, 7). -/
theorem compat_3_1_7 :
    Compatible 3 1 7 supportedEntry_3_1 supportedEntry_3_7 := by decide +kernel

/-- Compatibility of C(541, 1) with C(541, 3). -/
theorem compat_541_1_3 :
    Compatible 541 1 3 supportedEntry_541_1 supportedEntry_541_3 := by decide +kernel

/-- Compatibility of C(613, 1) with C(613, 3). -/
theorem compat_613_1_3 :
    Compatible 613 1 3 supportedEntry_613_1 supportedEntry_613_3 := by decide +kernel

/-- Compatibility of C(647, 1) with C(647, 3). -/
theorem compat_647_1_3 :
    Compatible 647 1 3 supportedEntry_647_1 supportedEntry_647_3 := by decide +kernel


end Conway

end Hex
