/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.CompatibilityCore
public import HexConway.CompatibilityProofs.S1_2

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Compatibility of C(79, 1) with C(79, 3). -/
theorem compat_79_1_3 :
    Compatible 79 1 3 supportedEntry_79_1 supportedEntry_79_3 := by decide +kernel

/-- Compatibility of C(131, 1) with C(131, 3). -/
theorem compat_131_1_3 :
    Compatible 131 1 3 supportedEntry_131_1 supportedEntry_131_3 := by decide +kernel

/-- Compatibility of C(197, 1) with C(197, 3). -/
theorem compat_197_1_3 :
    Compatible 197 1 3 supportedEntry_197_1 supportedEntry_197_3 := by decide +kernel

/-- Compatibility of C(233, 1) with C(233, 3). -/
theorem compat_233_1_3 :
    Compatible 233 1 3 supportedEntry_233_1 supportedEntry_233_3 := by decide +kernel

/-- Compatibility of C(677, 1) with C(677, 3). -/
theorem compat_677_1_3 :
    Compatible 677 1 3 supportedEntry_677_1 supportedEntry_677_3 := by decide +kernel

/-- Compatibility of C(857, 1) with C(857, 3). -/
theorem compat_857_1_3 :
    Compatible 857 1 3 supportedEntry_857_1 supportedEntry_857_3 := by decide +kernel

/-- Compatibility of C(127, 1) with C(127, 3). -/
theorem compat_127_1_3 :
    Compatible 127 1 3 supportedEntry_127_1 supportedEntry_127_3 := by decide +kernel

/-- Compatibility of C(2, 1) with C(2, 7). -/
theorem compat_2_1_7 :
    Compatible 2 1 7 supportedEntry_2_1 supportedEntry_2_7 := by decide +kernel

/-- Compatibility of C(43, 1) with C(43, 3). -/
theorem compat_43_1_3 :
    Compatible 43 1 3 supportedEntry_43_1 supportedEntry_43_3 := by decide +kernel

/-- Compatibility of C(173, 1) with C(173, 3). -/
theorem compat_173_1_3 :
    Compatible 173 1 3 supportedEntry_173_1 supportedEntry_173_3 := by decide +kernel

/-- Compatibility of C(89, 1) with C(89, 3). -/
theorem compat_89_1_3 :
    Compatible 89 1 3 supportedEntry_89_1 supportedEntry_89_3 := by decide +kernel

/-- Compatibility of C(29, 1) with C(29, 3). -/
theorem compat_29_1_3 :
    Compatible 29 1 3 supportedEntry_29_1 supportedEntry_29_3 := by decide +kernel

/-- Compatibility of C(59, 1) with C(59, 3). -/
theorem compat_59_1_3 :
    Compatible 59 1 3 supportedEntry_59_1 supportedEntry_59_3 := by decide +kernel

/-- Compatibility of C(659, 1) with C(659, 2). -/
theorem compat_659_1_2 :
    Compatible 659 1 2 supportedEntry_659_1 supportedEntry_659_2 := by decide +kernel

/-- Compatibility of C(419, 1) with C(419, 2). -/
theorem compat_419_1_2 :
    Compatible 419 1 2 supportedEntry_419_1 supportedEntry_419_2 := by decide +kernel

/-- Compatibility of C(547, 1) with C(547, 2). -/
theorem compat_547_1_2 :
    Compatible 547 1 2 supportedEntry_547_1 supportedEntry_547_2 := by decide +kernel

/-- Compatibility of C(617, 1) with C(617, 2). -/
theorem compat_617_1_2 :
    Compatible 617 1 2 supportedEntry_617_1 supportedEntry_617_2 := by decide +kernel

/-- Compatibility of C(661, 1) with C(661, 2). -/
theorem compat_661_1_2 :
    Compatible 661 1 2 supportedEntry_661_1 supportedEntry_661_2 := by decide +kernel

/-- Compatibility of C(709, 1) with C(709, 2). -/
theorem compat_709_1_2 :
    Compatible 709 1 2 supportedEntry_709_1 supportedEntry_709_2 := by decide +kernel

/-- Compatibility of C(761, 1) with C(761, 2). -/
theorem compat_761_1_2 :
    Compatible 761 1 2 supportedEntry_761_1 supportedEntry_761_2 := by decide +kernel

/-- Compatibility of C(821, 1) with C(821, 2). -/
theorem compat_821_1_2 :
    Compatible 821 1 2 supportedEntry_821_1 supportedEntry_821_2 := by decide +kernel

/-- Compatibility of C(853, 1) with C(853, 2). -/
theorem compat_853_1_2 :
    Compatible 853 1 2 supportedEntry_853_1 supportedEntry_853_2 := by decide +kernel

/-- Compatibility of C(919, 1) with C(919, 2). -/
theorem compat_919_1_2 :
    Compatible 919 1 2 supportedEntry_919_1 supportedEntry_919_2 := by decide +kernel

/-- Compatibility of C(947, 1) with C(947, 2). -/
theorem compat_947_1_2 :
    Compatible 947 1 2 supportedEntry_947_1 supportedEntry_947_2 := by decide +kernel


end Conway

end Hex
