/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.CompatibilityCore
public import HexConway.CompatibilityProofs.S2_1

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Compatibility of C(709, 1) with C(709, 3). -/
theorem compat_709_1_3 :
    Compatible 709 1 3 supportedEntry_709_1 supportedEntry_709_3 := by decide +kernel

/-- Compatibility of C(757, 1) with C(757, 3). -/
theorem compat_757_1_3 :
    Compatible 757 1 3 supportedEntry_757_1 supportedEntry_757_3 := by decide +kernel

/-- Compatibility of C(859, 1) with C(859, 3). -/
theorem compat_859_1_3 :
    Compatible 859 1 3 supportedEntry_859_1 supportedEntry_859_3 := by decide +kernel

/-- Compatibility of C(941, 1) with C(941, 3). -/
theorem compat_941_1_3 :
    Compatible 941 1 3 supportedEntry_941_1 supportedEntry_941_3 := by decide +kernel

/-- Compatibility of C(3, 3) with C(3, 6). -/
theorem compat_3_3_6 :
    Compatible 3 3 6 supportedEntry_3_3 supportedEntry_3_6 := by decide +kernel

/-- Compatibility of C(17, 1) with C(17, 4). -/
theorem compat_17_1_4 :
    Compatible 17 1 4 supportedEntry_17_1 supportedEntry_17_4 := by decide +kernel

/-- Compatibility of C(263, 1) with C(263, 3). -/
theorem compat_263_1_3 :
    Compatible 263 1 3 supportedEntry_263_1 supportedEntry_263_3 := by decide +kernel

/-- Compatibility of C(283, 1) with C(283, 3). -/
theorem compat_283_1_3 :
    Compatible 283 1 3 supportedEntry_283_1 supportedEntry_283_3 := by decide +kernel

/-- Compatibility of C(347, 1) with C(347, 3). -/
theorem compat_347_1_3 :
    Compatible 347 1 3 supportedEntry_347_1 supportedEntry_347_3 := by decide +kernel

/-- Compatibility of C(379, 1) with C(379, 3). -/
theorem compat_379_1_3 :
    Compatible 379 1 3 supportedEntry_379_1 supportedEntry_379_3 := by decide +kernel

/-- Compatibility of C(439, 1) with C(439, 3). -/
theorem compat_439_1_3 :
    Compatible 439 1 3 supportedEntry_439_1 supportedEntry_439_3 := by decide +kernel

/-- Compatibility of C(491, 1) with C(491, 3). -/
theorem compat_491_1_3 :
    Compatible 491 1 3 supportedEntry_491_1 supportedEntry_491_3 := by decide +kernel

/-- Compatibility of C(139, 1) with C(139, 3). -/
theorem compat_139_1_3 :
    Compatible 139 1 3 supportedEntry_139_1 supportedEntry_139_3 := by decide +kernel

/-- Compatibility of C(163, 1) with C(163, 3). -/
theorem compat_163_1_3 :
    Compatible 163 1 3 supportedEntry_163_1 supportedEntry_163_3 := by decide +kernel

/-- Compatibility of C(557, 1) with C(557, 3). -/
theorem compat_557_1_3 :
    Compatible 557 1 3 supportedEntry_557_1 supportedEntry_557_3 := by decide +kernel

/-- Compatibility of C(587, 1) with C(587, 3). -/
theorem compat_587_1_3 :
    Compatible 587 1 3 supportedEntry_587_1 supportedEntry_587_3 := by decide +kernel

/-- Compatibility of C(701, 1) with C(701, 3). -/
theorem compat_701_1_3 :
    Compatible 701 1 3 supportedEntry_701_1 supportedEntry_701_3 := by decide +kernel

/-- Compatibility of C(761, 1) with C(761, 3). -/
theorem compat_761_1_3 :
    Compatible 761 1 3 supportedEntry_761_1 supportedEntry_761_3 := by decide +kernel

/-- Compatibility of C(863, 1) with C(863, 3). -/
theorem compat_863_1_3 :
    Compatible 863 1 3 supportedEntry_863_1 supportedEntry_863_3 := by decide +kernel

/-- Compatibility of C(937, 1) with C(937, 3). -/
theorem compat_937_1_3 :
    Compatible 937 1 3 supportedEntry_937_1 supportedEntry_937_3 := by decide +kernel

/-- Compatibility of C(11, 2) with C(11, 4). -/
theorem compat_11_2_4 :
    Compatible 11 2 4 supportedEntry_11_2 supportedEntry_11_4 := by decide +kernel

/-- Compatibility of C(401, 1) with C(401, 3). -/
theorem compat_401_1_3 :
    Compatible 401 1 3 supportedEntry_401_1 supportedEntry_401_3 := by decide +kernel

/-- Compatibility of C(467, 1) with C(467, 3). -/
theorem compat_467_1_3 :
    Compatible 467 1 3 supportedEntry_467_1 supportedEntry_467_3 := by decide +kernel

/-- Compatibility of C(509, 1) with C(509, 3). -/
theorem compat_509_1_3 :
    Compatible 509 1 3 supportedEntry_509_1 supportedEntry_509_3 := by decide +kernel


end Conway

end Hex
