/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Table
public import HexConway.Power
public import HexConway.Rabin.S1_3

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Rabin certificate for C(7, 3). -/
private def cert_7_3 : Berlekamp.IrreducibilityCertificate where
  p := 7
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 7), 1], FpPoly.ofCoeffs #[(0 : ZMod64 7), 5, 3], FpPoly.ofCoeffs #[(1 : ZMod64 7), 1, 4], FpPoly.ofCoeffs #[(0 : ZMod64 7), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(2 : ZMod64 7)], right := FpPoly.ofCoeffs #[(0 : ZMod64 7), 4] }]

/-- Irreducibility of the imported C(7, 3). -/
@[grind .] theorem luebeckConwayPolynomial_7_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_7_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_7_3 luebeckConwayPolynomial_7_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_7_3 luebeckConwayPolynomial_7_3_monic cert_7_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(863, 2). -/
private def cert_863_2 : Berlekamp.IrreducibilityCertificate where
  p := 863
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 863), 1], FpPoly.ofCoeffs #[(1 : ZMod64 863), 862], FpPoly.ofCoeffs #[(0 : ZMod64 863), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(409 : ZMod64 863)], right := FpPoly.ofCoeffs #[(545 : ZMod64 863), 636] }]

/-- Irreducibility of the imported C(863, 2). -/
@[grind .] theorem luebeckConwayPolynomial_863_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_863_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_863_2 luebeckConwayPolynomial_863_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_863_2 luebeckConwayPolynomial_863_2_monic cert_863_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(103, 2). -/
private def cert_103_2 : Berlekamp.IrreducibilityCertificate where
  p := 103
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 103), 1], FpPoly.ofCoeffs #[(1 : ZMod64 103), 102], FpPoly.ofCoeffs #[(0 : ZMod64 103), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(49 : ZMod64 103)], right := FpPoly.ofCoeffs #[(65 : ZMod64 103), 76] }]

/-- Irreducibility of the imported C(103, 2). -/
@[grind .] theorem luebeckConwayPolynomial_103_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_103_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_103_2 luebeckConwayPolynomial_103_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_103_2 luebeckConwayPolynomial_103_2_monic cert_103_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(383, 2). -/
private def cert_383_2 : Berlekamp.IrreducibilityCertificate where
  p := 383
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 383), 1], FpPoly.ofCoeffs #[(1 : ZMod64 383), 382], FpPoly.ofCoeffs #[(0 : ZMod64 383), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(101 : ZMod64 383)], right := FpPoly.ofCoeffs #[(262 : ZMod64 383), 242] }]

/-- Irreducibility of the imported C(383, 2). -/
@[grind .] theorem luebeckConwayPolynomial_383_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_383_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_383_2 luebeckConwayPolynomial_383_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_383_2 luebeckConwayPolynomial_383_2_monic cert_383_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(59, 2). -/
private def cert_59_2 : Berlekamp.IrreducibilityCertificate where
  p := 59
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 59), 1], FpPoly.ofCoeffs #[(1 : ZMod64 59), 58], FpPoly.ofCoeffs #[(0 : ZMod64 59), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(9 : ZMod64 59)], right := FpPoly.ofCoeffs #[(42 : ZMod64 59), 34] }]

/-- Irreducibility of the imported C(59, 2). -/
@[grind .] theorem luebeckConwayPolynomial_59_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_59_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_59_2 luebeckConwayPolynomial_59_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_59_2 luebeckConwayPolynomial_59_2_monic cert_59_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(193, 2). -/
private def cert_193_2 : Berlekamp.IrreducibilityCertificate where
  p := 193
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 193), 1], FpPoly.ofCoeffs #[(1 : ZMod64 193), 192], FpPoly.ofCoeffs #[(0 : ZMod64 193), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(51 : ZMod64 193)], right := FpPoly.ofCoeffs #[(132 : ZMod64 193), 122] }]

/-- Irreducibility of the imported C(193, 2). -/
@[grind .] theorem luebeckConwayPolynomial_193_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_193_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_193_2 luebeckConwayPolynomial_193_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_193_2 luebeckConwayPolynomial_193_2_monic cert_193_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(5, 3). -/
private def cert_5_3 : Berlekamp.IrreducibilityCertificate where
  p := 5
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 5), 1], FpPoly.ofCoeffs #[(4 : ZMod64 5), 4, 2], FpPoly.ofCoeffs #[(1 : ZMod64 5), 0, 3], FpPoly.ofCoeffs #[(0 : ZMod64 5), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(3 : ZMod64 5), 3], right := FpPoly.ofCoeffs #[(3 : ZMod64 5), 2, 1] }]

/-- Irreducibility of the imported C(5, 3). -/
@[grind .] theorem luebeckConwayPolynomial_5_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_5_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_5_3 luebeckConwayPolynomial_5_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_5_3 luebeckConwayPolynomial_5_3_monic cert_5_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(37, 2). -/
private def cert_37_2 : Berlekamp.IrreducibilityCertificate where
  p := 37
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 37), 1], FpPoly.ofCoeffs #[(4 : ZMod64 37), 36], FpPoly.ofCoeffs #[(0 : ZMod64 37), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(18 : ZMod64 37)], right := FpPoly.ofCoeffs #[(19 : ZMod64 37), 9] }]

/-- Irreducibility of the imported C(37, 2). -/
@[grind .] theorem luebeckConwayPolynomial_37_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_37_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_37_2 luebeckConwayPolynomial_37_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_37_2 luebeckConwayPolynomial_37_2_monic cert_37_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(19, 2). -/
private def cert_19_2 : Berlekamp.IrreducibilityCertificate where
  p := 19
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 19), 1], FpPoly.ofCoeffs #[(1 : ZMod64 19), 18], FpPoly.ofCoeffs #[(0 : ZMod64 19), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(6 : ZMod64 19)], right := FpPoly.ofCoeffs #[(8 : ZMod64 19), 3] }]

/-- Irreducibility of the imported C(19, 2). -/
@[grind .] theorem luebeckConwayPolynomial_19_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_19_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_19_2 luebeckConwayPolynomial_19_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_19_2 luebeckConwayPolynomial_19_2_monic cert_19_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(11, 2). -/
private def cert_11_2 : Berlekamp.IrreducibilityCertificate where
  p := 11
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 11), 1], FpPoly.ofCoeffs #[(4 : ZMod64 11), 10], FpPoly.ofCoeffs #[(0 : ZMod64 11), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(5 : ZMod64 11)], right := FpPoly.ofCoeffs #[(6 : ZMod64 11), 8] }]

/-- Irreducibility of the imported C(11, 2). -/
@[grind .] theorem luebeckConwayPolynomial_11_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_11_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_11_2 luebeckConwayPolynomial_11_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_11_2 luebeckConwayPolynomial_11_2_monic cert_11_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(547, 1). -/
private def cert_547_1 : Berlekamp.IrreducibilityCertificate where
  p := 547
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(2 : ZMod64 547)], FpPoly.ofCoeffs #[(2 : ZMod64 547)]]
  bezout := #[]

/-- Irreducibility of the imported C(547, 1). -/
@[grind .] theorem luebeckConwayPolynomial_547_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_547_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_547_1 luebeckConwayPolynomial_547_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_547_1 luebeckConwayPolynomial_547_1_monic cert_547_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(691, 1). -/
private def cert_691_1 : Berlekamp.IrreducibilityCertificate where
  p := 691
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(3 : ZMod64 691)], FpPoly.ofCoeffs #[(3 : ZMod64 691)]]
  bezout := #[]

/-- Irreducibility of the imported C(691, 1). -/
@[grind .] theorem luebeckConwayPolynomial_691_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_691_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_691_1 luebeckConwayPolynomial_691_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_691_1 luebeckConwayPolynomial_691_1_monic cert_691_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(991, 1). -/
private def cert_991_1 : Berlekamp.IrreducibilityCertificate where
  p := 991
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(6 : ZMod64 991)], FpPoly.ofCoeffs #[(6 : ZMod64 991)]]
  bezout := #[]

/-- Irreducibility of the imported C(991, 1). -/
@[grind .] theorem luebeckConwayPolynomial_991_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_991_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_991_1 luebeckConwayPolynomial_991_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_991_1 luebeckConwayPolynomial_991_1_monic cert_991_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(521, 1). -/
private def cert_521_1 : Berlekamp.IrreducibilityCertificate where
  p := 521
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(3 : ZMod64 521)], FpPoly.ofCoeffs #[(3 : ZMod64 521)]]
  bezout := #[]

/-- Irreducibility of the imported C(521, 1). -/
@[grind .] theorem luebeckConwayPolynomial_521_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_521_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_521_1 luebeckConwayPolynomial_521_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_521_1 luebeckConwayPolynomial_521_1_monic cert_521_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(599, 1). -/
private def cert_599_1 : Berlekamp.IrreducibilityCertificate where
  p := 599
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(7 : ZMod64 599)], FpPoly.ofCoeffs #[(7 : ZMod64 599)]]
  bezout := #[]

/-- Irreducibility of the imported C(599, 1). -/
@[grind .] theorem luebeckConwayPolynomial_599_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_599_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_599_1 luebeckConwayPolynomial_599_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_599_1 luebeckConwayPolynomial_599_1_monic cert_599_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(617, 1). -/
private def cert_617_1 : Berlekamp.IrreducibilityCertificate where
  p := 617
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(3 : ZMod64 617)], FpPoly.ofCoeffs #[(3 : ZMod64 617)]]
  bezout := #[]

/-- Irreducibility of the imported C(617, 1). -/
@[grind .] theorem luebeckConwayPolynomial_617_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_617_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_617_1 luebeckConwayPolynomial_617_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_617_1 luebeckConwayPolynomial_617_1_monic cert_617_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(659, 1). -/
private def cert_659_1 : Berlekamp.IrreducibilityCertificate where
  p := 659
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(2 : ZMod64 659)], FpPoly.ofCoeffs #[(2 : ZMod64 659)]]
  bezout := #[]

/-- Irreducibility of the imported C(659, 1). -/
@[grind .] theorem luebeckConwayPolynomial_659_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_659_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_659_1 luebeckConwayPolynomial_659_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_659_1 luebeckConwayPolynomial_659_1_monic cert_659_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(709, 1). -/
private def cert_709_1 : Berlekamp.IrreducibilityCertificate where
  p := 709
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(2 : ZMod64 709)], FpPoly.ofCoeffs #[(2 : ZMod64 709)]]
  bezout := #[]

/-- Irreducibility of the imported C(709, 1). -/
@[grind .] theorem luebeckConwayPolynomial_709_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_709_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_709_1 luebeckConwayPolynomial_709_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_709_1 luebeckConwayPolynomial_709_1_monic cert_709_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(743, 1). -/
private def cert_743_1 : Berlekamp.IrreducibilityCertificate where
  p := 743
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(5 : ZMod64 743)], FpPoly.ofCoeffs #[(5 : ZMod64 743)]]
  bezout := #[]

/-- Irreducibility of the imported C(743, 1). -/
@[grind .] theorem luebeckConwayPolynomial_743_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_743_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_743_1 luebeckConwayPolynomial_743_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_743_1 luebeckConwayPolynomial_743_1_monic cert_743_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(787, 1). -/
private def cert_787_1 : Berlekamp.IrreducibilityCertificate where
  p := 787
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(2 : ZMod64 787)], FpPoly.ofCoeffs #[(2 : ZMod64 787)]]
  bezout := #[]

/-- Irreducibility of the imported C(787, 1). -/
@[grind .] theorem luebeckConwayPolynomial_787_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_787_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_787_1 luebeckConwayPolynomial_787_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_787_1 luebeckConwayPolynomial_787_1_monic cert_787_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(827, 1). -/
private def cert_827_1 : Berlekamp.IrreducibilityCertificate where
  p := 827
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(2 : ZMod64 827)], FpPoly.ofCoeffs #[(2 : ZMod64 827)]]
  bezout := #[]

/-- Irreducibility of the imported C(827, 1). -/
@[grind .] theorem luebeckConwayPolynomial_827_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_827_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_827_1 luebeckConwayPolynomial_827_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_827_1 luebeckConwayPolynomial_827_1_monic cert_827_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(881, 1). -/
private def cert_881_1 : Berlekamp.IrreducibilityCertificate where
  p := 881
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(3 : ZMod64 881)], FpPoly.ofCoeffs #[(3 : ZMod64 881)]]
  bezout := #[]

/-- Irreducibility of the imported C(881, 1). -/
@[grind .] theorem luebeckConwayPolynomial_881_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_881_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_881_1 luebeckConwayPolynomial_881_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_881_1 luebeckConwayPolynomial_881_1_monic cert_881_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(937, 1). -/
private def cert_937_1 : Berlekamp.IrreducibilityCertificate where
  p := 937
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(5 : ZMod64 937)], FpPoly.ofCoeffs #[(5 : ZMod64 937)]]
  bezout := #[]

/-- Irreducibility of the imported C(937, 1). -/
@[grind .] theorem luebeckConwayPolynomial_937_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_937_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_937_1 luebeckConwayPolynomial_937_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_937_1 luebeckConwayPolynomial_937_1_monic cert_937_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(971, 1). -/
private def cert_971_1 : Berlekamp.IrreducibilityCertificate where
  p := 971
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(6 : ZMod64 971)], FpPoly.ofCoeffs #[(6 : ZMod64 971)]]
  bezout := #[]

/-- Irreducibility of the imported C(971, 1). -/
@[grind .] theorem luebeckConwayPolynomial_971_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_971_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_971_1 luebeckConwayPolynomial_971_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_971_1 luebeckConwayPolynomial_971_1_monic cert_971_1
      (by rw [← checkRabin_eq]; decide +kernel))


end Conway

end Hex
