/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Table
public import HexConway.Power
public import HexConway.Rabin.S2_1

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Rabin certificate for C(401, 3). -/
private def cert_401_3 : Berlekamp.IrreducibilityCertificate where
  p := 401
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 401), 1], FpPoly.ofCoeffs #[(65 : ZMod64 401), 349, 233], FpPoly.ofCoeffs #[(336 : ZMod64 401), 51, 168], FpPoly.ofCoeffs #[(0 : ZMod64 401), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(149 : ZMod64 401), 397], right := FpPoly.ofCoeffs #[(266 : ZMod64 401), 216, 105] }]

/-- Irreducibility of the imported C(401, 3). -/
@[grind .] theorem luebeckConwayPolynomial_401_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_401_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_401_3 luebeckConwayPolynomial_401_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_401_3 luebeckConwayPolynomial_401_3_monic cert_401_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(467, 3). -/
private def cert_467_3 : Berlekamp.IrreducibilityCertificate where
  p := 467
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 467), 1], FpPoly.ofCoeffs #[(241 : ZMod64 467), 329, 64], FpPoly.ofCoeffs #[(226 : ZMod64 467), 137, 403], FpPoly.ofCoeffs #[(0 : ZMod64 467), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(22 : ZMod64 467), 89], right := FpPoly.ofCoeffs #[(6 : ZMod64 467), 347, 254] }]

/-- Irreducibility of the imported C(467, 3). -/
@[grind .] theorem luebeckConwayPolynomial_467_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_467_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_467_3 luebeckConwayPolynomial_467_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_467_3 luebeckConwayPolynomial_467_3_monic cert_467_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(509, 3). -/
private def cert_509_3 : Berlekamp.IrreducibilityCertificate where
  p := 509
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 509), 1], FpPoly.ofCoeffs #[(274 : ZMod64 509), 391, 137], FpPoly.ofCoeffs #[(235 : ZMod64 509), 117, 372], FpPoly.ofCoeffs #[(0 : ZMod64 509), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(220 : ZMod64 509), 367], right := FpPoly.ofCoeffs #[(375 : ZMod64 509), 191, 380] }]

/-- Irreducibility of the imported C(509, 3). -/
@[grind .] theorem luebeckConwayPolynomial_509_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_509_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_509_3 luebeckConwayPolynomial_509_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_509_3 luebeckConwayPolynomial_509_3_monic cert_509_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(2, 6). -/
private def cert_2_6 : Berlekamp.IrreducibilityCertificate where
  p := 2
  n := 6
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 2), 1], FpPoly.ofCoeffs #[(0 : ZMod64 2), 0, 1], FpPoly.ofCoeffs #[(0 : ZMod64 2), 0, 0, 0, 1], FpPoly.ofCoeffs #[(1 : ZMod64 2), 1, 1, 0, 1, 1], FpPoly.ofCoeffs #[(1 : ZMod64 2), 1, 0, 0, 1], FpPoly.ofCoeffs #[(0 : ZMod64 2), 1, 0, 0, 1, 1], FpPoly.ofCoeffs #[(0 : ZMod64 2), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(1 : ZMod64 2)], right := FpPoly.ofCoeffs #[(1 : ZMod64 2), 0, 1] }, { left := FpPoly.ofCoeffs #[(1 : ZMod64 2), 0, 1, 1], right := FpPoly.ofCoeffs #[(0 : ZMod64 2), 1, 1, 0, 1] }]

/-- Irreducibility of the imported C(2, 6). -/
@[grind .] theorem luebeckConwayPolynomial_2_6_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_2_6 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_2_6 luebeckConwayPolynomial_2_6_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_2_6 luebeckConwayPolynomial_2_6_monic cert_2_6
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(193, 3). -/
private def cert_193_3 : Berlekamp.IrreducibilityCertificate where
  p := 193
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 193), 1], FpPoly.ofCoeffs #[(61 : ZMod64 193), 155, 188], FpPoly.ofCoeffs #[(132 : ZMod64 193), 37, 5], FpPoly.ofCoeffs #[(0 : ZMod64 193), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(163 : ZMod64 193), 178], right := FpPoly.ofCoeffs #[(64 : ZMod64 193), 56, 190] }]

/-- Irreducibility of the imported C(193, 3). -/
@[grind .] theorem luebeckConwayPolynomial_193_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_193_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_193_3 luebeckConwayPolynomial_193_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_193_3 luebeckConwayPolynomial_193_3_monic cert_193_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(227, 3). -/
private def cert_227_3 : Berlekamp.IrreducibilityCertificate where
  p := 227
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 227), 1], FpPoly.ofCoeffs #[(143 : ZMod64 227), 132, 164], FpPoly.ofCoeffs #[(84 : ZMod64 227), 94, 63], FpPoly.ofCoeffs #[(0 : ZMod64 227), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(85 : ZMod64 227), 4], right := FpPoly.ofCoeffs #[(152 : ZMod64 227), 39, 155] }]

/-- Irreducibility of the imported C(227, 3). -/
@[grind .] theorem luebeckConwayPolynomial_227_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_227_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_227_3 luebeckConwayPolynomial_227_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_227_3 luebeckConwayPolynomial_227_3_monic cert_227_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(61, 3). -/
private def cert_61_3 : Berlekamp.IrreducibilityCertificate where
  p := 61
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 61), 1], FpPoly.ofCoeffs #[(56 : ZMod64 61), 9, 12], FpPoly.ofCoeffs #[(5 : ZMod64 61), 51, 49], FpPoly.ofCoeffs #[(0 : ZMod64 61), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(43 : ZMod64 61), 24], right := FpPoly.ofCoeffs #[(7 : ZMod64 61), 13, 59] }]

/-- Irreducibility of the imported C(61, 3). -/
@[grind .] theorem luebeckConwayPolynomial_61_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_61_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_61_3 luebeckConwayPolynomial_61_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_61_3 luebeckConwayPolynomial_61_3_monic cert_61_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(857, 3). -/
private def cert_857_3 : Berlekamp.IrreducibilityCertificate where
  p := 857
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 857), 1], FpPoly.ofCoeffs #[(405 : ZMod64 857), 398, 259], FpPoly.ofCoeffs #[(452 : ZMod64 857), 458, 598], FpPoly.ofCoeffs #[(0 : ZMod64 857), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(412 : ZMod64 857), 185], right := FpPoly.ofCoeffs #[(75 : ZMod64 857), 493, 489] }]

/-- Irreducibility of the imported C(857, 3). -/
@[grind .] theorem luebeckConwayPolynomial_857_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_857_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_857_3 luebeckConwayPolynomial_857_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_857_3 luebeckConwayPolynomial_857_3_monic cert_857_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(109, 3). -/
private def cert_109_3 : Berlekamp.IrreducibilityCertificate where
  p := 109
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 109), 1], FpPoly.ofCoeffs #[(52 : ZMod64 109), 102, 78], FpPoly.ofCoeffs #[(57 : ZMod64 109), 6, 31], FpPoly.ofCoeffs #[(0 : ZMod64 109), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(17 : ZMod64 109), 78], right := FpPoly.ofCoeffs #[(46 : ZMod64 109), 43, 108] }]

/-- Irreducibility of the imported C(109, 3). -/
@[grind .] theorem luebeckConwayPolynomial_109_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_109_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_109_3 luebeckConwayPolynomial_109_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_109_3 luebeckConwayPolynomial_109_3_monic cert_109_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(293, 3). -/
private def cert_293_3 : Berlekamp.IrreducibilityCertificate where
  p := 293
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 293), 1], FpPoly.ofCoeffs #[(10 : ZMod64 293), 84, 154], FpPoly.ofCoeffs #[(283 : ZMod64 293), 208, 139], FpPoly.ofCoeffs #[(0 : ZMod64 293), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(36 : ZMod64 293), 128], right := FpPoly.ofCoeffs #[(271 : ZMod64 293), 201, 22] }]

/-- Irreducibility of the imported C(293, 3). -/
@[grind .] theorem luebeckConwayPolynomial_293_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_293_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_293_3 luebeckConwayPolynomial_293_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_293_3 luebeckConwayPolynomial_293_3_monic cert_293_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(53, 3). -/
private def cert_53_3 : Berlekamp.IrreducibilityCertificate where
  p := 53
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 53), 1], FpPoly.ofCoeffs #[(5 : ZMod64 53), 2, 29], FpPoly.ofCoeffs #[(48 : ZMod64 53), 50, 24], FpPoly.ofCoeffs #[(0 : ZMod64 53), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(19 : ZMod64 53), 40], right := FpPoly.ofCoeffs #[(29 : ZMod64 53), 20, 37] }]

/-- Irreducibility of the imported C(53, 3). -/
@[grind .] theorem luebeckConwayPolynomial_53_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_53_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_53_3 luebeckConwayPolynomial_53_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_53_3 luebeckConwayPolynomial_53_3_monic cert_53_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(7, 4). -/
private def cert_7_4 : Berlekamp.IrreducibilityCertificate where
  p := 7
  n := 4
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 7), 1], FpPoly.ofCoeffs #[(5 : ZMod64 7), 3, 5, 1], FpPoly.ofCoeffs #[(0 : ZMod64 7), 0, 3, 1], FpPoly.ofCoeffs #[(2 : ZMod64 7), 3, 6, 5], FpPoly.ofCoeffs #[(0 : ZMod64 7), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(5 : ZMod64 7), 3, 5], right := FpPoly.ofCoeffs #[(1 : ZMod64 7), 6, 5, 2] }]

/-- Irreducibility of the imported C(7, 4). -/
@[grind .] theorem luebeckConwayPolynomial_7_4_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_7_4 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_7_4 luebeckConwayPolynomial_7_4_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_7_4 luebeckConwayPolynomial_7_4_monic cert_7_4
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(101, 3). -/
private def cert_101_3 : Berlekamp.IrreducibilityCertificate where
  p := 101
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 101), 1], FpPoly.ofCoeffs #[(94 : ZMod64 101), 97, 47], FpPoly.ofCoeffs #[(7 : ZMod64 101), 3, 54], FpPoly.ofCoeffs #[(0 : ZMod64 101), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(89 : ZMod64 101), 50], right := FpPoly.ofCoeffs #[(61 : ZMod64 101), 38, 72] }]

/-- Irreducibility of the imported C(101, 3). -/
@[grind .] theorem luebeckConwayPolynomial_101_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_101_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_101_3 luebeckConwayPolynomial_101_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_101_3 luebeckConwayPolynomial_101_3_monic cert_101_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(3, 5). -/
private def cert_3_5 : Berlekamp.IrreducibilityCertificate where
  p := 3
  n := 5
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 3), 1], FpPoly.ofCoeffs #[(0 : ZMod64 3), 0, 0, 1], FpPoly.ofCoeffs #[(2 : ZMod64 3), 1, 0, 0, 2], FpPoly.ofCoeffs #[(2 : ZMod64 3), 0, 2, 0, 2], FpPoly.ofCoeffs #[(2 : ZMod64 3), 1, 1, 2, 2], FpPoly.ofCoeffs #[(0 : ZMod64 3), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(1 : ZMod64 3)], right := FpPoly.ofCoeffs #[(2 : ZMod64 3), 0, 2] }]

/-- Irreducibility of the imported C(3, 5). -/
@[grind .] theorem luebeckConwayPolynomial_3_5_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_3_5 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_3_5 luebeckConwayPolynomial_3_5_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_3_5 luebeckConwayPolynomial_3_5_monic cert_3_5
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(59, 3). -/
private def cert_59_3 : Berlekamp.IrreducibilityCertificate where
  p := 59
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 59), 1], FpPoly.ofCoeffs #[(54 : ZMod64 59), 34, 28], FpPoly.ofCoeffs #[(5 : ZMod64 59), 24, 31], FpPoly.ofCoeffs #[(0 : ZMod64 59), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(39 : ZMod64 59), 26], right := FpPoly.ofCoeffs #[(55 : ZMod64 59), 14, 37] }]

/-- Irreducibility of the imported C(59, 3). -/
@[grind .] theorem luebeckConwayPolynomial_59_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_59_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_59_3 luebeckConwayPolynomial_59_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_59_3 luebeckConwayPolynomial_59_3_monic cert_59_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(11, 3). -/
private def cert_11_3 : Berlekamp.IrreducibilityCertificate where
  p := 11
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 11), 1], FpPoly.ofCoeffs #[(6 : ZMod64 11), 9, 10], FpPoly.ofCoeffs #[(5 : ZMod64 11), 1, 1], FpPoly.ofCoeffs #[(0 : ZMod64 11), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(10 : ZMod64 11), 1], right := FpPoly.ofCoeffs #[(9 : ZMod64 11), 7, 1] }]

/-- Irreducibility of the imported C(11, 3). -/
@[grind .] theorem luebeckConwayPolynomial_11_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_11_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_11_3 luebeckConwayPolynomial_11_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_11_3 luebeckConwayPolynomial_11_3_monic cert_11_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(19, 3). -/
private def cert_19_3 : Berlekamp.IrreducibilityCertificate where
  p := 19
  n := 3
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 19), 1], FpPoly.ofCoeffs #[(8 : ZMod64 19), 16, 3], FpPoly.ofCoeffs #[(11 : ZMod64 19), 2, 16], FpPoly.ofCoeffs #[(0 : ZMod64 19), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(0 : ZMod64 19), 2], right := FpPoly.ofCoeffs #[(12 : ZMod64 19), 16, 12] }]

/-- Irreducibility of the imported C(19, 3). -/
@[grind .] theorem luebeckConwayPolynomial_19_3_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_19_3 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_19_3 luebeckConwayPolynomial_19_3_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_19_3 luebeckConwayPolynomial_19_3_monic cert_19_3
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(599, 2). -/
private def cert_599_2 : Berlekamp.IrreducibilityCertificate where
  p := 599
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 599), 1], FpPoly.ofCoeffs #[(1 : ZMod64 599), 598], FpPoly.ofCoeffs #[(0 : ZMod64 599), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(222 : ZMod64 599)], right := FpPoly.ofCoeffs #[(244 : ZMod64 599), 111] }]

/-- Irreducibility of the imported C(599, 2). -/
@[grind .] theorem luebeckConwayPolynomial_599_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_599_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_599_2 luebeckConwayPolynomial_599_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_599_2 luebeckConwayPolynomial_599_2_monic cert_599_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(631, 2). -/
private def cert_631_2 : Berlekamp.IrreducibilityCertificate where
  p := 631
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 631), 1], FpPoly.ofCoeffs #[(2 : ZMod64 631), 630], FpPoly.ofCoeffs #[(0 : ZMod64 631), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(316 : ZMod64 631)], right := FpPoly.ofCoeffs #[(473 : ZMod64 631), 158] }]

/-- Irreducibility of the imported C(631, 2). -/
@[grind .] theorem luebeckConwayPolynomial_631_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_631_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_631_2 luebeckConwayPolynomial_631_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_631_2 luebeckConwayPolynomial_631_2_monic cert_631_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(691, 2). -/
private def cert_691_2 : Berlekamp.IrreducibilityCertificate where
  p := 691
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 691), 1], FpPoly.ofCoeffs #[(5 : ZMod64 691), 690], FpPoly.ofCoeffs #[(0 : ZMod64 691), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(106 : ZMod64 691)], right := FpPoly.ofCoeffs #[(213 : ZMod64 691), 53] }]

/-- Irreducibility of the imported C(691, 2). -/
@[grind .] theorem luebeckConwayPolynomial_691_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_691_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_691_2 luebeckConwayPolynomial_691_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_691_2 luebeckConwayPolynomial_691_2_monic cert_691_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(739, 2). -/
private def cert_739_2 : Berlekamp.IrreducibilityCertificate where
  p := 739
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 739), 1], FpPoly.ofCoeffs #[(5 : ZMod64 739), 738], FpPoly.ofCoeffs #[(0 : ZMod64 739), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(625 : ZMod64 739)], right := FpPoly.ofCoeffs #[(512 : ZMod64 739), 682] }]

/-- Irreducibility of the imported C(739, 2). -/
@[grind .] theorem luebeckConwayPolynomial_739_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_739_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_739_2 luebeckConwayPolynomial_739_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_739_2 luebeckConwayPolynomial_739_2_monic cert_739_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(797, 2). -/
private def cert_797_2 : Berlekamp.IrreducibilityCertificate where
  p := 797
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 797), 1], FpPoly.ofCoeffs #[(4 : ZMod64 797), 796], FpPoly.ofCoeffs #[(0 : ZMod64 797), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(398 : ZMod64 797)], right := FpPoly.ofCoeffs #[(399 : ZMod64 797), 199] }]

/-- Irreducibility of the imported C(797, 2). -/
@[grind .] theorem luebeckConwayPolynomial_797_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_797_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_797_2 luebeckConwayPolynomial_797_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_797_2 luebeckConwayPolynomial_797_2_monic cert_797_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(829, 2). -/
private def cert_829_2 : Berlekamp.IrreducibilityCertificate where
  p := 829
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 829), 1], FpPoly.ofCoeffs #[(1 : ZMod64 829), 828], FpPoly.ofCoeffs #[(0 : ZMod64 829), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(119 : ZMod64 829)], right := FpPoly.ofCoeffs #[(592 : ZMod64 829), 474] }]

/-- Irreducibility of the imported C(829, 2). -/
@[grind .] theorem luebeckConwayPolynomial_829_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_829_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_829_2 luebeckConwayPolynomial_829_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_829_2 luebeckConwayPolynomial_829_2_monic cert_829_2
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(881, 2). -/
private def cert_881_2 : Berlekamp.IrreducibilityCertificate where
  p := 881
  n := 2
  powChain := #[FpPoly.ofCoeffs #[(0 : ZMod64 881), 1], FpPoly.ofCoeffs #[(12 : ZMod64 881), 880], FpPoly.ofCoeffs #[(0 : ZMod64 881), 1]]
  bezout := #[{ left := FpPoly.ofCoeffs #[(614 : ZMod64 881)], right := FpPoly.ofCoeffs #[(801 : ZMod64 881), 307] }]

/-- Irreducibility of the imported C(881, 2). -/
@[grind .] theorem luebeckConwayPolynomial_881_2_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_881_2 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_881_2 luebeckConwayPolynomial_881_2_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_881_2 luebeckConwayPolynomial_881_2_monic cert_881_2
      (by rw [← checkRabin_eq]; decide +kernel))


end Conway

end Hex
