/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Table
public import HexConway.Power
public import HexConway.Rabin.S3_5

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Rabin certificate for C(73, 1). -/
private def cert_73_1 : Berlekamp.IrreducibilityCertificate where
  p := 73
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(5 : ZMod64 73)], FpPoly.ofCoeffs #[(5 : ZMod64 73)]]
  bezout := #[]

/-- Irreducibility of the imported C(73, 1). -/
@[grind .] theorem luebeckConwayPolynomial_73_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_73_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_73_1 luebeckConwayPolynomial_73_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_73_1 luebeckConwayPolynomial_73_1_monic cert_73_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(83, 1). -/
private def cert_83_1 : Berlekamp.IrreducibilityCertificate where
  p := 83
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(2 : ZMod64 83)], FpPoly.ofCoeffs #[(2 : ZMod64 83)]]
  bezout := #[]

/-- Irreducibility of the imported C(83, 1). -/
@[grind .] theorem luebeckConwayPolynomial_83_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_83_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_83_1 luebeckConwayPolynomial_83_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_83_1 luebeckConwayPolynomial_83_1_monic cert_83_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(107, 1). -/
private def cert_107_1 : Berlekamp.IrreducibilityCertificate where
  p := 107
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(2 : ZMod64 107)], FpPoly.ofCoeffs #[(2 : ZMod64 107)]]
  bezout := #[]

/-- Irreducibility of the imported C(107, 1). -/
@[grind .] theorem luebeckConwayPolynomial_107_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_107_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_107_1 luebeckConwayPolynomial_107_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_107_1 luebeckConwayPolynomial_107_1_monic cert_107_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(47, 1). -/
private def cert_47_1 : Berlekamp.IrreducibilityCertificate where
  p := 47
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(5 : ZMod64 47)], FpPoly.ofCoeffs #[(5 : ZMod64 47)]]
  bezout := #[]

/-- Irreducibility of the imported C(47, 1). -/
@[grind .] theorem luebeckConwayPolynomial_47_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_47_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_47_1 luebeckConwayPolynomial_47_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_47_1 luebeckConwayPolynomial_47_1_monic cert_47_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(23, 1). -/
private def cert_23_1 : Berlekamp.IrreducibilityCertificate where
  p := 23
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(5 : ZMod64 23)], FpPoly.ofCoeffs #[(5 : ZMod64 23)]]
  bezout := #[]

/-- Irreducibility of the imported C(23, 1). -/
@[grind .] theorem luebeckConwayPolynomial_23_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_23_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_23_1 luebeckConwayPolynomial_23_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_23_1 luebeckConwayPolynomial_23_1_monic cert_23_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(7, 1). -/
private def cert_7_1 : Berlekamp.IrreducibilityCertificate where
  p := 7
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(3 : ZMod64 7)], FpPoly.ofCoeffs #[(3 : ZMod64 7)]]
  bezout := #[]

/-- Irreducibility of the imported C(7, 1). -/
@[grind .] theorem luebeckConwayPolynomial_7_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_7_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_7_1 luebeckConwayPolynomial_7_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_7_1 luebeckConwayPolynomial_7_1_monic cert_7_1
      (by rw [← checkRabin_eq]; decide +kernel))

/-- Rabin certificate for C(3, 1). -/
private def cert_3_1 : Berlekamp.IrreducibilityCertificate where
  p := 3
  n := 1
  powChain := #[FpPoly.ofCoeffs #[(2 : ZMod64 3)], FpPoly.ofCoeffs #[(2 : ZMod64 3)]]
  bezout := #[]

/-- Irreducibility of the imported C(3, 1). -/
@[grind .] theorem luebeckConwayPolynomial_3_1_irreducible : FpPoly.Irreducible luebeckConwayPolynomial_3_1 :=
  Berlekamp.rabinTest_imp_irreducible luebeckConwayPolynomial_3_1 luebeckConwayPolynomial_3_1_monic
    (Berlekamp.checkIrreducibilityCertificateLinearIncremental_rabinTest
      luebeckConwayPolynomial_3_1 luebeckConwayPolynomial_3_1_monic cert_3_1
      (by rw [← checkRabin_eq]; decide +kernel))


end Conway

end Hex
