name = "hex-conway"
defaultTargets = ["HexConway"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBerlekamp"
git = "https://github.com/leanprover/hex-berlekamp.git"
rev = "b0a24af3b8b0a42f6ddd8b96f77eaf9eb8955875"

[[lean_lib]]
name = "HexConway"
