name = "hex-conway"
defaultTargets = ["HexConway"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBerlekamp"
git = "https://github.com/leanprover/hex-berlekamp.git"
rev = "1abc06a7bf0a0fb570116f88df049a412df7187a"

[[require]]
name = "HexArith"
git = "https://github.com/leanprover/hex-arith.git"
rev = "ea246536c442464a68210ecce973eb7708968f59"

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "ab1e4419cc16a219d0432bc1c535a8430385d329"

[[require]]
name = "HexGFqRing"
git = "https://github.com/leanprover/hex-gfq-ring.git"
rev = "c8e9ae656852744edb51cdf11801248085a7a8d5"

[[lean_lib]]
name = "HexConway"
