/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.ApiCore

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- The verified table supports C(2, 16). -/
@[expose] def supportedEntry_2_16 : SupportedEntry 2 16 :=
  ⟨luebeckConwayPolynomial_2_16, prime_two, luebeckConwayPolynomial?_hit_2_16⟩

/-- The verified table supports C(173, 4). -/
@[expose] def supportedEntry_173_4 : SupportedEntry 173 4 :=
  ⟨luebeckConwayPolynomial_173_4, prime_173, luebeckConwayPolynomial?_hit_173_4⟩

/-- The verified table supports C(233, 4). -/
@[expose] def supportedEntry_233_4 : SupportedEntry 233 4 :=
  ⟨luebeckConwayPolynomial_233_4, prime_233, luebeckConwayPolynomial?_hit_233_4⟩

/-- The verified table supports C(283, 4). -/
@[expose] def supportedEntry_283_4 : SupportedEntry 283 4 :=
  ⟨luebeckConwayPolynomial_283_4, prime_283, luebeckConwayPolynomial?_hit_283_4⟩

/-- The verified table supports C(131, 4). -/
@[expose] def supportedEntry_131_4 : SupportedEntry 131 4 :=
  ⟨luebeckConwayPolynomial_131_4, prime_131, luebeckConwayPolynomial?_hit_131_4⟩

/-- The verified table supports C(151, 4). -/
@[expose] def supportedEntry_151_4 : SupportedEntry 151 4 :=
  ⟨luebeckConwayPolynomial_151_4, prime_151, luebeckConwayPolynomial?_hit_151_4⟩

/-- The verified table supports C(197, 4). -/
@[expose] def supportedEntry_197_4 : SupportedEntry 197 4 :=
  ⟨luebeckConwayPolynomial_197_4, prime_197, luebeckConwayPolynomial?_hit_197_4⟩

/-- The verified table supports C(241, 4). -/
@[expose] def supportedEntry_241_4 : SupportedEntry 241 4 :=
  ⟨luebeckConwayPolynomial_241_4, prime_241, luebeckConwayPolynomial?_hit_241_4⟩

/-- The verified table supports C(271, 4). -/
@[expose] def supportedEntry_271_4 : SupportedEntry 271 4 :=
  ⟨luebeckConwayPolynomial_271_4, prime_271, luebeckConwayPolynomial?_hit_271_4⟩

/-- The verified table supports C(103, 4). -/
@[expose] def supportedEntry_103_4 : SupportedEntry 103 4 :=
  ⟨luebeckConwayPolynomial_103_4, prime_103, luebeckConwayPolynomial?_hit_103_4⟩

/-- The verified table supports C(7, 6). -/
@[expose] def supportedEntry_7_6 : SupportedEntry 7 6 :=
  ⟨luebeckConwayPolynomial_7_6, prime_seven, luebeckConwayPolynomial?_hit_7_6⟩

/-- The verified table supports C(43, 4). -/
@[expose] def supportedEntry_43_4 : SupportedEntry 43 4 :=
  ⟨luebeckConwayPolynomial_43_4, prime_43, luebeckConwayPolynomial?_hit_43_4⟩

/-- The verified table supports C(97, 4). -/
@[expose] def supportedEntry_97_4 : SupportedEntry 97 4 :=
  ⟨luebeckConwayPolynomial_97_4, prime_97, luebeckConwayPolynomial?_hit_97_4⟩

/-- The verified table supports C(5, 7). -/
@[expose] def supportedEntry_5_7 : SupportedEntry 5 7 :=
  ⟨luebeckConwayPolynomial_5_7, prime_five, luebeckConwayPolynomial?_hit_5_7⟩

/-- The verified table supports C(59, 4). -/
@[expose] def supportedEntry_59_4 : SupportedEntry 59 4 :=
  ⟨luebeckConwayPolynomial_59_4, prime_59, luebeckConwayPolynomial?_hit_59_4⟩

/-- The verified table supports C(991, 3). -/
@[expose] def supportedEntry_991_3 : SupportedEntry 991 3 :=
  ⟨luebeckConwayPolynomial_991_3, prime_991, luebeckConwayPolynomial?_hit_991_3⟩

/-- The verified table supports C(809, 3). -/
@[expose] def supportedEntry_809_3 : SupportedEntry 809 3 :=
  ⟨luebeckConwayPolynomial_809_3, prime_809, luebeckConwayPolynomial?_hit_809_3⟩

/-- The verified table supports C(877, 3). -/
@[expose] def supportedEntry_877_3 : SupportedEntry 877 3 :=
  ⟨luebeckConwayPolynomial_877_3, prime_877, luebeckConwayPolynomial?_hit_877_3⟩

/-- The verified table supports C(997, 3). -/
@[expose] def supportedEntry_997_3 : SupportedEntry 997 3 :=
  ⟨luebeckConwayPolynomial_997_3, prime_997, luebeckConwayPolynomial?_hit_997_3⟩

/-- The verified table supports C(211, 3). -/
@[expose] def supportedEntry_211_3 : SupportedEntry 211 3 :=
  ⟨luebeckConwayPolynomial_211_3, prime_211, luebeckConwayPolynomial?_hit_211_3⟩

/-- The verified table supports C(331, 3). -/
@[expose] def supportedEntry_331_3 : SupportedEntry 331 3 :=
  ⟨luebeckConwayPolynomial_331_3, prime_331, luebeckConwayPolynomial?_hit_331_3⟩

/-- The verified table supports C(3, 7). -/
@[expose] def supportedEntry_3_7 : SupportedEntry 3 7 :=
  ⟨luebeckConwayPolynomial_3_7, prime_three, luebeckConwayPolynomial?_hit_3_7⟩

/-- The verified table supports C(599, 3). -/
@[expose] def supportedEntry_599_3 : SupportedEntry 599 3 :=
  ⟨luebeckConwayPolynomial_599_3, prime_599, luebeckConwayPolynomial?_hit_599_3⟩

/-- The verified table supports C(617, 3). -/
@[expose] def supportedEntry_617_3 : SupportedEntry 617 3 :=
  ⟨luebeckConwayPolynomial_617_3, prime_617, luebeckConwayPolynomial?_hit_617_3⟩


end Conway

end Hex
