/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.ApiCore
public import HexConway.Supported.S0_2

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- The verified table supports C(421, 2). -/
@[expose] def supportedEntry_421_2 : SupportedEntry 421 2 :=
  ⟨luebeckConwayPolynomial_421_2, prime_421, luebeckConwayPolynomial?_hit_421_2⟩

/-- The verified table supports C(491, 2). -/
@[expose] def supportedEntry_491_2 : SupportedEntry 491 2 :=
  ⟨luebeckConwayPolynomial_491_2, prime_491, luebeckConwayPolynomial?_hit_491_2⟩

/-- The verified table supports C(139, 2). -/
@[expose] def supportedEntry_139_2 : SupportedEntry 139 2 :=
  ⟨luebeckConwayPolynomial_139_2, prime_139, luebeckConwayPolynomial?_hit_139_2⟩

/-- The verified table supports C(229, 2). -/
@[expose] def supportedEntry_229_2 : SupportedEntry 229 2 :=
  ⟨luebeckConwayPolynomial_229_2, prime_229, luebeckConwayPolynomial?_hit_229_2⟩

/-- The verified table supports C(557, 2). -/
@[expose] def supportedEntry_557_2 : SupportedEntry 557 2 :=
  ⟨luebeckConwayPolynomial_557_2, prime_557, luebeckConwayPolynomial?_hit_557_2⟩

/-- The verified table supports C(607, 2). -/
@[expose] def supportedEntry_607_2 : SupportedEntry 607 2 :=
  ⟨luebeckConwayPolynomial_607_2, prime_607, luebeckConwayPolynomial?_hit_607_2⟩

/-- The verified table supports C(653, 2). -/
@[expose] def supportedEntry_653_2 : SupportedEntry 653 2 :=
  ⟨luebeckConwayPolynomial_653_2, prime_653, luebeckConwayPolynomial?_hit_653_2⟩

/-- The verified table supports C(733, 2). -/
@[expose] def supportedEntry_733_2 : SupportedEntry 733 2 :=
  ⟨luebeckConwayPolynomial_733_2, prime_733, luebeckConwayPolynomial?_hit_733_2⟩

/-- The verified table supports C(787, 2). -/
@[expose] def supportedEntry_787_2 : SupportedEntry 787 2 :=
  ⟨luebeckConwayPolynomial_787_2, prime_787, luebeckConwayPolynomial?_hit_787_2⟩

/-- The verified table supports C(887, 2). -/
@[expose] def supportedEntry_887_2 : SupportedEntry 887 2 :=
  ⟨luebeckConwayPolynomial_887_2, prime_887, luebeckConwayPolynomial?_hit_887_2⟩

/-- The verified table supports C(983, 2). -/
@[expose] def supportedEntry_983_2 : SupportedEntry 983 2 :=
  ⟨luebeckConwayPolynomial_983_2, prime_983, luebeckConwayPolynomial?_hit_983_2⟩

/-- The verified table supports C(271, 2). -/
@[expose] def supportedEntry_271_2 : SupportedEntry 271 2 :=
  ⟨luebeckConwayPolynomial_271_2, prime_271, luebeckConwayPolynomial?_hit_271_2⟩

/-- The verified table supports C(313, 2). -/
@[expose] def supportedEntry_313_2 : SupportedEntry 313 2 :=
  ⟨luebeckConwayPolynomial_313_2, prime_313, luebeckConwayPolynomial?_hit_313_2⟩

/-- The verified table supports C(353, 2). -/
@[expose] def supportedEntry_353_2 : SupportedEntry 353 2 :=
  ⟨luebeckConwayPolynomial_353_2, prime_353, luebeckConwayPolynomial?_hit_353_2⟩

/-- The verified table supports C(401, 2). -/
@[expose] def supportedEntry_401_2 : SupportedEntry 401 2 :=
  ⟨luebeckConwayPolynomial_401_2, prime_401, luebeckConwayPolynomial?_hit_401_2⟩

/-- The verified table supports C(457, 2). -/
@[expose] def supportedEntry_457_2 : SupportedEntry 457 2 :=
  ⟨luebeckConwayPolynomial_457_2, prime_457, luebeckConwayPolynomial?_hit_457_2⟩

/-- The verified table supports C(503, 2). -/
@[expose] def supportedEntry_503_2 : SupportedEntry 503 2 :=
  ⟨luebeckConwayPolynomial_503_2, prime_503, luebeckConwayPolynomial?_hit_503_2⟩

/-- The verified table supports C(149, 2). -/
@[expose] def supportedEntry_149_2 : SupportedEntry 149 2 :=
  ⟨luebeckConwayPolynomial_149_2, prime_149, luebeckConwayPolynomial?_hit_149_2⟩

/-- The verified table supports C(173, 2). -/
@[expose] def supportedEntry_173_2 : SupportedEntry 173 2 :=
  ⟨luebeckConwayPolynomial_173_2, prime_173, luebeckConwayPolynomial?_hit_173_2⟩

/-- The verified table supports C(199, 2). -/
@[expose] def supportedEntry_199_2 : SupportedEntry 199 2 :=
  ⟨luebeckConwayPolynomial_199_2, prime_199, luebeckConwayPolynomial?_hit_199_2⟩

/-- The verified table supports C(241, 2). -/
@[expose] def supportedEntry_241_2 : SupportedEntry 241 2 :=
  ⟨luebeckConwayPolynomial_241_2, prime_241, luebeckConwayPolynomial?_hit_241_2⟩

/-- The verified table supports C(577, 2). -/
@[expose] def supportedEntry_577_2 : SupportedEntry 577 2 :=
  ⟨luebeckConwayPolynomial_577_2, prime_577, luebeckConwayPolynomial?_hit_577_2⟩

/-- The verified table supports C(79, 2). -/
@[expose] def supportedEntry_79_2 : SupportedEntry 79 2 :=
  ⟨luebeckConwayPolynomial_79_2, prime_79, luebeckConwayPolynomial?_hit_79_2⟩

/-- The verified table supports C(101, 2). -/
@[expose] def supportedEntry_101_2 : SupportedEntry 101 2 :=
  ⟨luebeckConwayPolynomial_101_2, prime_101, luebeckConwayPolynomial?_hit_101_2⟩


end Conway

end Hex
