/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.ApiCore

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- The verified table supports C(2, 15). -/
@[expose] def supportedEntry_2_15 : SupportedEntry 2 15 :=
  ⟨luebeckConwayPolynomial_2_15, prime_two, luebeckConwayPolynomial?_hit_2_15⟩

/-- The verified table supports C(2, 11). -/
@[expose] def supportedEntry_2_11 : SupportedEntry 2 11 :=
  ⟨luebeckConwayPolynomial_2_11, prime_two, luebeckConwayPolynomial?_hit_2_11⟩

/-- The verified table supports C(2, 13). -/
@[expose] def supportedEntry_2_13 : SupportedEntry 2 13 :=
  ⟨luebeckConwayPolynomial_2_13, prime_two, luebeckConwayPolynomial?_hit_2_13⟩

/-- The verified table supports C(281, 4). -/
@[expose] def supportedEntry_281_4 : SupportedEntry 281 4 :=
  ⟨luebeckConwayPolynomial_281_4, prime_281, luebeckConwayPolynomial?_hit_281_4⟩

/-- The verified table supports C(191, 4). -/
@[expose] def supportedEntry_191_4 : SupportedEntry 191 4 :=
  ⟨luebeckConwayPolynomial_191_4, prime_191, luebeckConwayPolynomial?_hit_191_4⟩

/-- The verified table supports C(263, 4). -/
@[expose] def supportedEntry_263_4 : SupportedEntry 263 4 :=
  ⟨luebeckConwayPolynomial_263_4, prime_263, luebeckConwayPolynomial?_hit_263_4⟩

/-- The verified table supports C(83, 4). -/
@[expose] def supportedEntry_83_4 : SupportedEntry 83 4 :=
  ⟨luebeckConwayPolynomial_83_4, prime_83, luebeckConwayPolynomial?_hit_83_4⟩

/-- The verified table supports C(137, 4). -/
@[expose] def supportedEntry_137_4 : SupportedEntry 137 4 :=
  ⟨luebeckConwayPolynomial_137_4, prime_137, luebeckConwayPolynomial?_hit_137_4⟩

/-- The verified table supports C(167, 4). -/
@[expose] def supportedEntry_167_4 : SupportedEntry 167 4 :=
  ⟨luebeckConwayPolynomial_167_4, prime_167, luebeckConwayPolynomial?_hit_167_4⟩

/-- The verified table supports C(223, 4). -/
@[expose] def supportedEntry_223_4 : SupportedEntry 223 4 :=
  ⟨luebeckConwayPolynomial_223_4, prime_223, luebeckConwayPolynomial?_hit_223_4⟩

/-- The verified table supports C(251, 4). -/
@[expose] def supportedEntry_251_4 : SupportedEntry 251 4 :=
  ⟨luebeckConwayPolynomial_251_4, prime_251, luebeckConwayPolynomial?_hit_251_4⟩

/-- The verified table supports C(67, 4). -/
@[expose] def supportedEntry_67_4 : SupportedEntry 67 4 :=
  ⟨luebeckConwayPolynomial_67_4, prime_67, luebeckConwayPolynomial?_hit_67_4⟩

/-- The verified table supports C(109, 4). -/
@[expose] def supportedEntry_109_4 : SupportedEntry 109 4 :=
  ⟨luebeckConwayPolynomial_109_4, prime_109, luebeckConwayPolynomial?_hit_109_4⟩

/-- The verified table supports C(163, 4). -/
@[expose] def supportedEntry_163_4 : SupportedEntry 163 4 :=
  ⟨luebeckConwayPolynomial_163_4, prime_163, luebeckConwayPolynomial?_hit_163_4⟩

/-- The verified table supports C(47, 4). -/
@[expose] def supportedEntry_47_4 : SupportedEntry 47 4 :=
  ⟨luebeckConwayPolynomial_47_4, prime_47, luebeckConwayPolynomial?_hit_47_4⟩

/-- The verified table supports C(101, 4). -/
@[expose] def supportedEntry_101_4 : SupportedEntry 101 4 :=
  ⟨luebeckConwayPolynomial_101_4, prime_101, luebeckConwayPolynomial?_hit_101_4⟩

/-- The verified table supports C(37, 4). -/
@[expose] def supportedEntry_37_4 : SupportedEntry 37 4 :=
  ⟨luebeckConwayPolynomial_37_4, prime_37, luebeckConwayPolynomial?_hit_37_4⟩

/-- The verified table supports C(61, 4). -/
@[expose] def supportedEntry_61_4 : SupportedEntry 61 4 :=
  ⟨luebeckConwayPolynomial_61_4, prime_61, luebeckConwayPolynomial?_hit_61_4⟩

/-- The verified table supports C(547, 3). -/
@[expose] def supportedEntry_547_3 : SupportedEntry 547 3 :=
  ⟨luebeckConwayPolynomial_547_3, prime_547, luebeckConwayPolynomial?_hit_547_3⟩

/-- The verified table supports C(811, 3). -/
@[expose] def supportedEntry_811_3 : SupportedEntry 811 3 :=
  ⟨luebeckConwayPolynomial_811_3, prime_811, luebeckConwayPolynomial?_hit_811_3⟩

/-- The verified table supports C(947, 3). -/
@[expose] def supportedEntry_947_3 : SupportedEntry 947 3 :=
  ⟨luebeckConwayPolynomial_947_3, prime_947, luebeckConwayPolynomial?_hit_947_3⟩

/-- The verified table supports C(23, 4). -/
@[expose] def supportedEntry_23_4 : SupportedEntry 23 4 :=
  ⟨luebeckConwayPolynomial_23_4, prime_23, luebeckConwayPolynomial?_hit_23_4⟩

/-- The verified table supports C(11, 5). -/
@[expose] def supportedEntry_11_5 : SupportedEntry 11 5 :=
  ⟨luebeckConwayPolynomial_11_5, prime_eleven, luebeckConwayPolynomial?_hit_11_5⟩

/-- The verified table supports C(373, 3). -/
@[expose] def supportedEntry_373_3 : SupportedEntry 373 3 :=
  ⟨luebeckConwayPolynomial_373_3, prime_373, luebeckConwayPolynomial?_hit_373_3⟩


end Conway

end Hex
