/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.ApiCore
public import HexConway.Supported.S1_2

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- The verified table supports C(947, 2). -/
@[expose] def supportedEntry_947_2 : SupportedEntry 947 2 :=
  ⟨luebeckConwayPolynomial_947_2, prime_947, luebeckConwayPolynomial?_hit_947_2⟩

/-- The verified table supports C(281, 2). -/
@[expose] def supportedEntry_281_2 : SupportedEntry 281 2 :=
  ⟨luebeckConwayPolynomial_281_2, prime_281, luebeckConwayPolynomial?_hit_281_2⟩

/-- The verified table supports C(311, 2). -/
@[expose] def supportedEntry_311_2 : SupportedEntry 311 2 :=
  ⟨luebeckConwayPolynomial_311_2, prime_311, luebeckConwayPolynomial?_hit_311_2⟩

/-- The verified table supports C(379, 2). -/
@[expose] def supportedEntry_379_2 : SupportedEntry 379 2 :=
  ⟨luebeckConwayPolynomial_379_2, prime_379, luebeckConwayPolynomial?_hit_379_2⟩

/-- The verified table supports C(439, 2). -/
@[expose] def supportedEntry_439_2 : SupportedEntry 439 2 :=
  ⟨luebeckConwayPolynomial_439_2, prime_439, luebeckConwayPolynomial?_hit_439_2⟩

/-- The verified table supports C(509, 2). -/
@[expose] def supportedEntry_509_2 : SupportedEntry 509 2 :=
  ⟨luebeckConwayPolynomial_509_2, prime_509, luebeckConwayPolynomial?_hit_509_2⟩

/-- The verified table supports C(239, 2). -/
@[expose] def supportedEntry_239_2 : SupportedEntry 239 2 :=
  ⟨luebeckConwayPolynomial_239_2, prime_239, luebeckConwayPolynomial?_hit_239_2⟩

/-- The verified table supports C(563, 2). -/
@[expose] def supportedEntry_563_2 : SupportedEntry 563 2 :=
  ⟨luebeckConwayPolynomial_563_2, prime_563, luebeckConwayPolynomial?_hit_563_2⟩

/-- The verified table supports C(613, 2). -/
@[expose] def supportedEntry_613_2 : SupportedEntry 613 2 :=
  ⟨luebeckConwayPolynomial_613_2, prime_613, luebeckConwayPolynomial?_hit_613_2⟩

/-- The verified table supports C(673, 2). -/
@[expose] def supportedEntry_673_2 : SupportedEntry 673 2 :=
  ⟨luebeckConwayPolynomial_673_2, prime_673, luebeckConwayPolynomial?_hit_673_2⟩

/-- The verified table supports C(751, 2). -/
@[expose] def supportedEntry_751_2 : SupportedEntry 751 2 :=
  ⟨luebeckConwayPolynomial_751_2, prime_751, luebeckConwayPolynomial?_hit_751_2⟩

/-- The verified table supports C(809, 2). -/
@[expose] def supportedEntry_809_2 : SupportedEntry 809 2 :=
  ⟨luebeckConwayPolynomial_809_2, prime_809, luebeckConwayPolynomial?_hit_809_2⟩

/-- The verified table supports C(907, 2). -/
@[expose] def supportedEntry_907_2 : SupportedEntry 907 2 :=
  ⟨luebeckConwayPolynomial_907_2, prime_907, luebeckConwayPolynomial?_hit_907_2⟩

/-- The verified table supports C(997, 2). -/
@[expose] def supportedEntry_997_2 : SupportedEntry 997 2 :=
  ⟨luebeckConwayPolynomial_997_2, prime_997, luebeckConwayPolynomial?_hit_997_2⟩

/-- The verified table supports C(277, 2). -/
@[expose] def supportedEntry_277_2 : SupportedEntry 277 2 :=
  ⟨luebeckConwayPolynomial_277_2, prime_277, luebeckConwayPolynomial?_hit_277_2⟩

/-- The verified table supports C(317, 2). -/
@[expose] def supportedEntry_317_2 : SupportedEntry 317 2 :=
  ⟨luebeckConwayPolynomial_317_2, prime_317, luebeckConwayPolynomial?_hit_317_2⟩

/-- The verified table supports C(359, 2). -/
@[expose] def supportedEntry_359_2 : SupportedEntry 359 2 :=
  ⟨luebeckConwayPolynomial_359_2, prime_359, luebeckConwayPolynomial?_hit_359_2⟩

/-- The verified table supports C(431, 2). -/
@[expose] def supportedEntry_431_2 : SupportedEntry 431 2 :=
  ⟨luebeckConwayPolynomial_431_2, prime_431, luebeckConwayPolynomial?_hit_431_2⟩

/-- The verified table supports C(467, 2). -/
@[expose] def supportedEntry_467_2 : SupportedEntry 467 2 :=
  ⟨luebeckConwayPolynomial_467_2, prime_467, luebeckConwayPolynomial?_hit_467_2⟩

/-- The verified table supports C(17, 3). -/
@[expose] def supportedEntry_17_3 : SupportedEntry 17 3 :=
  ⟨luebeckConwayPolynomial_17_3, prime_17, luebeckConwayPolynomial?_hit_17_3⟩

/-- The verified table supports C(137, 2). -/
@[expose] def supportedEntry_137_2 : SupportedEntry 137 2 :=
  ⟨luebeckConwayPolynomial_137_2, prime_137, luebeckConwayPolynomial?_hit_137_2⟩

/-- The verified table supports C(167, 2). -/
@[expose] def supportedEntry_167_2 : SupportedEntry 167 2 :=
  ⟨luebeckConwayPolynomial_167_2, prime_167, luebeckConwayPolynomial?_hit_167_2⟩

/-- The verified table supports C(197, 2). -/
@[expose] def supportedEntry_197_2 : SupportedEntry 197 2 :=
  ⟨luebeckConwayPolynomial_197_2, prime_197, luebeckConwayPolynomial?_hit_197_2⟩

/-- The verified table supports C(233, 2). -/
@[expose] def supportedEntry_233_2 : SupportedEntry 233 2 :=
  ⟨luebeckConwayPolynomial_233_2, prime_233, luebeckConwayPolynomial?_hit_233_2⟩


end Conway

end Hex
