/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.ApiCore
public import HexConway.Supported.S2_0

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- The verified table supports C(463, 3). -/
@[expose] def supportedEntry_463_3 : SupportedEntry 463 3 :=
  ⟨luebeckConwayPolynomial_463_3, prime_463, luebeckConwayPolynomial?_hit_463_3⟩

/-- The verified table supports C(541, 3). -/
@[expose] def supportedEntry_541_3 : SupportedEntry 541 3 :=
  ⟨luebeckConwayPolynomial_541_3, prime_541, luebeckConwayPolynomial?_hit_541_3⟩

/-- The verified table supports C(613, 3). -/
@[expose] def supportedEntry_613_3 : SupportedEntry 613 3 :=
  ⟨luebeckConwayPolynomial_613_3, prime_613, luebeckConwayPolynomial?_hit_613_3⟩

/-- The verified table supports C(647, 3). -/
@[expose] def supportedEntry_647_3 : SupportedEntry 647 3 :=
  ⟨luebeckConwayPolynomial_647_3, prime_647, luebeckConwayPolynomial?_hit_647_3⟩

/-- The verified table supports C(683, 3). -/
@[expose] def supportedEntry_683_3 : SupportedEntry 683 3 :=
  ⟨luebeckConwayPolynomial_683_3, prime_683, luebeckConwayPolynomial?_hit_683_3⟩

/-- The verified table supports C(751, 3). -/
@[expose] def supportedEntry_751_3 : SupportedEntry 751 3 :=
  ⟨luebeckConwayPolynomial_751_3, prime_751, luebeckConwayPolynomial?_hit_751_3⟩

/-- The verified table supports C(853, 3). -/
@[expose] def supportedEntry_853_3 : SupportedEntry 853 3 :=
  ⟨luebeckConwayPolynomial_853_3, prime_853, luebeckConwayPolynomial?_hit_853_3⟩

/-- The verified table supports C(911, 3). -/
@[expose] def supportedEntry_911_3 : SupportedEntry 911 3 :=
  ⟨luebeckConwayPolynomial_911_3, prime_911, luebeckConwayPolynomial?_hit_911_3⟩

/-- The verified table supports C(191, 3). -/
@[expose] def supportedEntry_191_3 : SupportedEntry 191 3 :=
  ⟨luebeckConwayPolynomial_191_3, prime_191, luebeckConwayPolynomial?_hit_191_3⟩

/-- The verified table supports C(263, 3). -/
@[expose] def supportedEntry_263_3 : SupportedEntry 263 3 :=
  ⟨luebeckConwayPolynomial_263_3, prime_263, luebeckConwayPolynomial?_hit_263_3⟩

/-- The verified table supports C(307, 3). -/
@[expose] def supportedEntry_307_3 : SupportedEntry 307 3 :=
  ⟨luebeckConwayPolynomial_307_3, prime_307, luebeckConwayPolynomial?_hit_307_3⟩

/-- The verified table supports C(349, 3). -/
@[expose] def supportedEntry_349_3 : SupportedEntry 349 3 :=
  ⟨luebeckConwayPolynomial_349_3, prime_349, luebeckConwayPolynomial?_hit_349_3⟩

/-- The verified table supports C(397, 3). -/
@[expose] def supportedEntry_397_3 : SupportedEntry 397 3 :=
  ⟨luebeckConwayPolynomial_397_3, prime_397, luebeckConwayPolynomial?_hit_397_3⟩

/-- The verified table supports C(443, 3). -/
@[expose] def supportedEntry_443_3 : SupportedEntry 443 3 :=
  ⟨luebeckConwayPolynomial_443_3, prime_443, luebeckConwayPolynomial?_hit_443_3⟩

/-- The verified table supports C(499, 3). -/
@[expose] def supportedEntry_499_3 : SupportedEntry 499 3 :=
  ⟨luebeckConwayPolynomial_499_3, prime_499, luebeckConwayPolynomial?_hit_499_3⟩

/-- The verified table supports C(139, 3). -/
@[expose] def supportedEntry_139_3 : SupportedEntry 139 3 :=
  ⟨luebeckConwayPolynomial_139_3, prime_139, luebeckConwayPolynomial?_hit_139_3⟩

/-- The verified table supports C(181, 3). -/
@[expose] def supportedEntry_181_3 : SupportedEntry 181 3 :=
  ⟨luebeckConwayPolynomial_181_3, prime_181, luebeckConwayPolynomial?_hit_181_3⟩

/-- The verified table supports C(563, 3). -/
@[expose] def supportedEntry_563_3 : SupportedEntry 563 3 :=
  ⟨luebeckConwayPolynomial_563_3, prime_563, luebeckConwayPolynomial?_hit_563_3⟩

/-- The verified table supports C(593, 3). -/
@[expose] def supportedEntry_593_3 : SupportedEntry 593 3 :=
  ⟨luebeckConwayPolynomial_593_3, prime_593, luebeckConwayPolynomial?_hit_593_3⟩

/-- The verified table supports C(719, 3). -/
@[expose] def supportedEntry_719_3 : SupportedEntry 719 3 :=
  ⟨luebeckConwayPolynomial_719_3, prime_719, luebeckConwayPolynomial?_hit_719_3⟩

/-- The verified table supports C(769, 3). -/
@[expose] def supportedEntry_769_3 : SupportedEntry 769 3 :=
  ⟨luebeckConwayPolynomial_769_3, prime_769, luebeckConwayPolynomial?_hit_769_3⟩

/-- The verified table supports C(883, 3). -/
@[expose] def supportedEntry_883_3 : SupportedEntry 883 3 :=
  ⟨luebeckConwayPolynomial_883_3, prime_883, luebeckConwayPolynomial?_hit_883_3⟩

/-- The verified table supports C(977, 3). -/
@[expose] def supportedEntry_977_3 : SupportedEntry 977 3 :=
  ⟨luebeckConwayPolynomial_977_3, prime_977, luebeckConwayPolynomial?_hit_977_3⟩

/-- The verified table supports C(313, 3). -/
@[expose] def supportedEntry_313_3 : SupportedEntry 313 3 :=
  ⟨luebeckConwayPolynomial_313_3, prime_313, luebeckConwayPolynomial?_hit_313_3⟩


end Conway

end Hex
