/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Coefficients
public import HexConway.Entries.S0_0

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Imported C(653, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_653_3 : FpPoly 653 :=
  { coeffs := #[(651 : ZMod64 653), 3, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(653, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_653_3_monic : DensePoly.Monic luebeckConwayPolynomial_653_3 := by rfl

/-- Positive degree of C(653, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_653_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_653_3 := by decide

/-- Lookup identifies the imported C(653, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_653_3 :
    luebeckConwayPolynomial? 653 3 = some luebeckConwayPolynomial_653_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 653 [651, 3, 0, 1]) = some luebeckConwayPolynomial_653_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 653 [651, 3, 0, 1]) k =
        ([651, 3, 0, 1].toArray.map (fun m => ZMod64.ofNat 653 m)).getD k
          (Zero.zero : ZMod64 653) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_653_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(709, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_709_3 : FpPoly 709 :=
  { coeffs := #[(707 : ZMod64 709), 2, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(709, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_709_3_monic : DensePoly.Monic luebeckConwayPolynomial_709_3 := by rfl

/-- Positive degree of C(709, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_709_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_709_3 := by decide

/-- Lookup identifies the imported C(709, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_709_3 :
    luebeckConwayPolynomial? 709 3 = some luebeckConwayPolynomial_709_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 709 [707, 2, 0, 1]) = some luebeckConwayPolynomial_709_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 709 [707, 2, 0, 1]) k =
        ([707, 2, 0, 1].toArray.map (fun m => ZMod64.ofNat 709 m)).getD k
          (Zero.zero : ZMod64 709) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_709_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(757, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_757_3 : FpPoly 757 :=
  { coeffs := #[(755 : ZMod64 757), 6, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(757, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_757_3_monic : DensePoly.Monic luebeckConwayPolynomial_757_3 := by rfl

/-- Positive degree of C(757, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_757_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_757_3 := by decide

/-- Lookup identifies the imported C(757, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_757_3 :
    luebeckConwayPolynomial? 757 3 = some luebeckConwayPolynomial_757_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 757 [755, 6, 0, 1]) = some luebeckConwayPolynomial_757_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 757 [755, 6, 0, 1]) k =
        ([755, 6, 0, 1].toArray.map (fun m => ZMod64.ofNat 757 m)).getD k
          (Zero.zero : ZMod64 757) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_757_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(859, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_859_3 : FpPoly 859 :=
  { coeffs := #[(857 : ZMod64 859), 6, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(859, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_859_3_monic : DensePoly.Monic luebeckConwayPolynomial_859_3 := by rfl

/-- Positive degree of C(859, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_859_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_859_3 := by decide

/-- Lookup identifies the imported C(859, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_859_3 :
    luebeckConwayPolynomial? 859 3 = some luebeckConwayPolynomial_859_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 859 [857, 6, 0, 1]) = some luebeckConwayPolynomial_859_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 859 [857, 6, 0, 1]) k =
        ([857, 6, 0, 1].toArray.map (fun m => ZMod64.ofNat 859 m)).getD k
          (Zero.zero : ZMod64 859) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_859_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(941, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_941_3 : FpPoly 941 :=
  { coeffs := #[(939 : ZMod64 941), 3, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(941, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_941_3_monic : DensePoly.Monic luebeckConwayPolynomial_941_3 := by rfl

/-- Positive degree of C(941, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_941_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_941_3 := by decide

/-- Lookup identifies the imported C(941, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_941_3 :
    luebeckConwayPolynomial? 941 3 = some luebeckConwayPolynomial_941_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 941 [939, 3, 0, 1]) = some luebeckConwayPolynomial_941_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 941 [939, 3, 0, 1]) k =
        ([939, 3, 0, 1].toArray.map (fun m => ZMod64.ofNat 941 m)).getD k
          (Zero.zero : ZMod64 941) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_941_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(13, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_13_4 : FpPoly 13 :=
  { coeffs := #[(2 : ZMod64 13), 12, 3, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(13, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_13_4_monic : DensePoly.Monic luebeckConwayPolynomial_13_4 := by rfl

/-- Positive degree of C(13, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_13_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_13_4 := by decide

/-- Lookup identifies the imported C(13, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_13_4 :
    luebeckConwayPolynomial? 13 4 = some luebeckConwayPolynomial_13_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 13 [2, 12, 3, 0, 1]) = some luebeckConwayPolynomial_13_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 13 [2, 12, 3, 0, 1]) k =
        ([2, 12, 3, 0, 1].toArray.map (fun m => ZMod64.ofNat 13 m)).getD k
          (Zero.zero : ZMod64 13) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_13_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(269, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_269_3 : FpPoly 269 :=
  { coeffs := #[(267 : ZMod64 269), 9, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(269, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_269_3_monic : DensePoly.Monic luebeckConwayPolynomial_269_3 := by rfl

/-- Positive degree of C(269, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_269_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_269_3 := by decide

/-- Lookup identifies the imported C(269, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_269_3 :
    luebeckConwayPolynomial? 269 3 = some luebeckConwayPolynomial_269_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 269 [267, 9, 0, 1]) = some luebeckConwayPolynomial_269_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 269 [267, 9, 0, 1]) k =
        ([267, 9, 0, 1].toArray.map (fun m => ZMod64.ofNat 269 m)).getD k
          (Zero.zero : ZMod64 269) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_269_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(311, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_311_3 : FpPoly 311 :=
  { coeffs := #[(294 : ZMod64 311), 3, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(311, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_311_3_monic : DensePoly.Monic luebeckConwayPolynomial_311_3 := by rfl

/-- Positive degree of C(311, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_311_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_311_3 := by decide

/-- Lookup identifies the imported C(311, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_311_3 :
    luebeckConwayPolynomial? 311 3 = some luebeckConwayPolynomial_311_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 311 [294, 3, 0, 1]) = some luebeckConwayPolynomial_311_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 311 [294, 3, 0, 1]) k =
        ([294, 3, 0, 1].toArray.map (fun m => ZMod64.ofNat 311 m)).getD k
          (Zero.zero : ZMod64 311) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_311_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(359, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_359_3 : FpPoly 359 :=
  { coeffs := #[(352 : ZMod64 359), 3, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(359, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_359_3_monic : DensePoly.Monic luebeckConwayPolynomial_359_3 := by rfl

/-- Positive degree of C(359, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_359_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_359_3 := by decide

/-- Lookup identifies the imported C(359, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_359_3 :
    luebeckConwayPolynomial? 359 3 = some luebeckConwayPolynomial_359_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 359 [352, 3, 0, 1]) = some luebeckConwayPolynomial_359_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 359 [352, 3, 0, 1]) k =
        ([352, 3, 0, 1].toArray.map (fun m => ZMod64.ofNat 359 m)).getD k
          (Zero.zero : ZMod64 359) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_359_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(419, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_419_3 : FpPoly 419 :=
  { coeffs := #[(417 : ZMod64 419), 11, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(419, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_419_3_monic : DensePoly.Monic luebeckConwayPolynomial_419_3 := by rfl

/-- Positive degree of C(419, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_419_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_419_3 := by decide

/-- Lookup identifies the imported C(419, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_419_3 :
    luebeckConwayPolynomial? 419 3 = some luebeckConwayPolynomial_419_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 419 [417, 11, 0, 1]) = some luebeckConwayPolynomial_419_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 419 [417, 11, 0, 1]) k =
        ([417, 11, 0, 1].toArray.map (fun m => ZMod64.ofNat 419 m)).getD k
          (Zero.zero : ZMod64 419) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_419_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(457, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_457_3 : FpPoly 457 :=
  { coeffs := #[(444 : ZMod64 457), 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(457, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_457_3_monic : DensePoly.Monic luebeckConwayPolynomial_457_3 := by rfl

/-- Positive degree of C(457, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_457_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_457_3 := by decide

/-- Lookup identifies the imported C(457, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_457_3 :
    luebeckConwayPolynomial? 457 3 = some luebeckConwayPolynomial_457_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 457 [444, 1, 0, 1]) = some luebeckConwayPolynomial_457_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 457 [444, 1, 0, 1]) k =
        ([444, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 457 m)).getD k
          (Zero.zero : ZMod64 457) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_457_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(5, 5), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_5_5 : FpPoly 5 :=
  { coeffs := #[(3 : ZMod64 5), 4, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(5, 5). -/
@[simp, grind .] theorem luebeckConwayPolynomial_5_5_monic : DensePoly.Monic luebeckConwayPolynomial_5_5 := by rfl

/-- Positive degree of C(5, 5). -/
@[simp, grind .] theorem luebeckConwayPolynomial_5_5_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_5_5 := by decide

/-- Lookup identifies the imported C(5, 5). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_5_5 :
    luebeckConwayPolynomial? 5 5 = some luebeckConwayPolynomial_5_5 := by
  show some (luebeckConwayPolynomialOfCoeffs 5 [3, 4, 0, 0, 0, 1]) = some luebeckConwayPolynomial_5_5
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 5 [3, 4, 0, 0, 0, 1]) k =
        ([3, 4, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 5 m)).getD k
          (Zero.zero : ZMod64 5) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_5_5]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | _ + 6 => rfl

/-- Imported C(149, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_149_3 : FpPoly 149 :=
  { coeffs := #[(147 : ZMod64 149), 3, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(149, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_149_3_monic : DensePoly.Monic luebeckConwayPolynomial_149_3 := by rfl

/-- Positive degree of C(149, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_149_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_149_3 := by decide

/-- Lookup identifies the imported C(149, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_149_3 :
    luebeckConwayPolynomial? 149 3 = some luebeckConwayPolynomial_149_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 149 [147, 3, 0, 1]) = some luebeckConwayPolynomial_149_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 149 [147, 3, 0, 1]) k =
        ([147, 3, 0, 1].toArray.map (fun m => ZMod64.ofNat 149 m)).getD k
          (Zero.zero : ZMod64 149) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_149_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(229, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_229_3 : FpPoly 229 :=
  { coeffs := #[(223 : ZMod64 229), 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(229, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_229_3_monic : DensePoly.Monic luebeckConwayPolynomial_229_3 := by rfl

/-- Positive degree of C(229, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_229_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_229_3 := by decide

/-- Lookup identifies the imported C(229, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_229_3 :
    luebeckConwayPolynomial? 229 3 = some luebeckConwayPolynomial_229_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 229 [223, 1, 0, 1]) = some luebeckConwayPolynomial_229_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 229 [223, 1, 0, 1]) k =
        ([223, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 229 m)).getD k
          (Zero.zero : ZMod64 229) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_229_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(569, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_569_3 : FpPoly 569 :=
  { coeffs := #[(566 : ZMod64 569), 4, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(569, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_569_3_monic : DensePoly.Monic luebeckConwayPolynomial_569_3 := by rfl

/-- Positive degree of C(569, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_569_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_569_3 := by decide

/-- Lookup identifies the imported C(569, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_569_3 :
    luebeckConwayPolynomial? 569 3 = some luebeckConwayPolynomial_569_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 569 [566, 4, 0, 1]) = some luebeckConwayPolynomial_569_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 569 [566, 4, 0, 1]) k =
        ([566, 4, 0, 1].toArray.map (fun m => ZMod64.ofNat 569 m)).getD k
          (Zero.zero : ZMod64 569) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_569_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(641, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_641_3 : FpPoly 641 :=
  { coeffs := #[(638 : ZMod64 641), 4, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(641, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_641_3_monic : DensePoly.Monic luebeckConwayPolynomial_641_3 := by rfl

/-- Positive degree of C(641, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_641_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_641_3 := by decide

/-- Lookup identifies the imported C(641, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_641_3 :
    luebeckConwayPolynomial? 641 3 = some luebeckConwayPolynomial_641_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 641 [638, 4, 0, 1]) = some luebeckConwayPolynomial_641_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 641 [638, 4, 0, 1]) k =
        ([638, 4, 0, 1].toArray.map (fun m => ZMod64.ofNat 641 m)).getD k
          (Zero.zero : ZMod64 641) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_641_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(727, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_727_3 : FpPoly 727 :=
  { coeffs := #[(722 : ZMod64 727), 7, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(727, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_727_3_monic : DensePoly.Monic luebeckConwayPolynomial_727_3 := by rfl

/-- Positive degree of C(727, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_727_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_727_3 := by decide

/-- Lookup identifies the imported C(727, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_727_3 :
    luebeckConwayPolynomial? 727 3 = some luebeckConwayPolynomial_727_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 727 [722, 7, 0, 1]) = some luebeckConwayPolynomial_727_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 727 [722, 7, 0, 1]) k =
        ([722, 7, 0, 1].toArray.map (fun m => ZMod64.ofNat 727 m)).getD k
          (Zero.zero : ZMod64 727) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_727_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(797, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_797_3 : FpPoly 797 :=
  { coeffs := #[(795 : ZMod64 797), 2, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(797, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_797_3_monic : DensePoly.Monic luebeckConwayPolynomial_797_3 := by rfl

/-- Positive degree of C(797, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_797_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_797_3 := by decide

/-- Lookup identifies the imported C(797, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_797_3 :
    luebeckConwayPolynomial? 797 3 = some luebeckConwayPolynomial_797_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 797 [795, 2, 0, 1]) = some luebeckConwayPolynomial_797_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 797 [795, 2, 0, 1]) k =
        ([795, 2, 0, 1].toArray.map (fun m => ZMod64.ofNat 797 m)).getD k
          (Zero.zero : ZMod64 797) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_797_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(887, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_887_3 : FpPoly 887 :=
  { coeffs := #[(882 : ZMod64 887), 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(887, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_887_3_monic : DensePoly.Monic luebeckConwayPolynomial_887_3 := by rfl

/-- Positive degree of C(887, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_887_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_887_3 := by decide

/-- Lookup identifies the imported C(887, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_887_3 :
    luebeckConwayPolynomial? 887 3 = some luebeckConwayPolynomial_887_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 887 [882, 1, 0, 1]) = some luebeckConwayPolynomial_887_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 887 [882, 1, 0, 1]) k =
        ([882, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 887 m)).getD k
          (Zero.zero : ZMod64 887) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_887_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(983, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_983_3 : FpPoly 983 :=
  { coeffs := #[(978 : ZMod64 983), 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(983, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_983_3_monic : DensePoly.Monic luebeckConwayPolynomial_983_3 := by rfl

/-- Positive degree of C(983, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_983_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_983_3 := by decide

/-- Lookup identifies the imported C(983, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_983_3 :
    luebeckConwayPolynomial? 983 3 = some luebeckConwayPolynomial_983_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 983 [978, 1, 0, 1]) = some luebeckConwayPolynomial_983_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 983 [978, 1, 0, 1]) k =
        ([978, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 983 m)).getD k
          (Zero.zero : ZMod64 983) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_983_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(389, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_389_3 : FpPoly 389 :=
  { coeffs := #[(387 : ZMod64 389), 2, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(389, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_389_3_monic : DensePoly.Monic luebeckConwayPolynomial_389_3 := by rfl

/-- Positive degree of C(389, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_389_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_389_3 := by decide

/-- Lookup identifies the imported C(389, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_389_3 :
    luebeckConwayPolynomial? 389 3 = some luebeckConwayPolynomial_389_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 389 [387, 2, 0, 1]) = some luebeckConwayPolynomial_389_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 389 [387, 2, 0, 1]) k =
        ([387, 2, 0, 1].toArray.map (fun m => ZMod64.ofNat 389 m)).getD k
          (Zero.zero : ZMod64 389) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_389_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(449, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_449_3 : FpPoly 449 :=
  { coeffs := #[(446 : ZMod64 449), 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(449, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_449_3_monic : DensePoly.Monic luebeckConwayPolynomial_449_3 := by rfl

/-- Positive degree of C(449, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_449_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_449_3 := by decide

/-- Lookup identifies the imported C(449, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_449_3 :
    luebeckConwayPolynomial? 449 3 = some luebeckConwayPolynomial_449_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 449 [446, 1, 0, 1]) = some luebeckConwayPolynomial_449_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 449 [446, 1, 0, 1]) k =
        ([446, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 449 m)).getD k
          (Zero.zero : ZMod64 449) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_449_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(503, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_503_3 : FpPoly 503 :=
  { coeffs := #[(498 : ZMod64 503), 2, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(503, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_503_3_monic : DensePoly.Monic luebeckConwayPolynomial_503_3 := by rfl

/-- Positive degree of C(503, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_503_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_503_3 := by decide

/-- Lookup identifies the imported C(503, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_503_3 :
    luebeckConwayPolynomial? 503 3 = some luebeckConwayPolynomial_503_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 503 [498, 2, 0, 1]) = some luebeckConwayPolynomial_503_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 503 [498, 2, 0, 1]) k =
        ([498, 2, 0, 1].toArray.map (fun m => ZMod64.ofNat 503 m)).getD k
          (Zero.zero : ZMod64 503) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_503_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(107, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_107_3 : FpPoly 107 :=
  { coeffs := #[(105 : ZMod64 107), 5, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(107, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_107_3_monic : DensePoly.Monic luebeckConwayPolynomial_107_3 := by rfl

/-- Positive degree of C(107, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_107_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_107_3 := by decide

/-- Lookup identifies the imported C(107, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_107_3 :
    luebeckConwayPolynomial? 107 3 = some luebeckConwayPolynomial_107_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 107 [105, 5, 0, 1]) = some luebeckConwayPolynomial_107_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 107 [105, 5, 0, 1]) k =
        ([105, 5, 0, 1].toArray.map (fun m => ZMod64.ofNat 107 m)).getD k
          (Zero.zero : ZMod64 107) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_107_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl


end Conway

end Hex
