/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Coefficients
public import HexConway.Entries.S0_2

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Imported C(421, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_421_2 : FpPoly 421 :=
  { coeffs := #[(2 : ZMod64 421), 417, 1]
    normalized := by right; decide }

/-- Monicity of C(421, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_421_2_monic : DensePoly.Monic luebeckConwayPolynomial_421_2 := by rfl

/-- Positive degree of C(421, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_421_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_421_2 := by decide

/-- Lookup identifies the imported C(421, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_421_2 :
    luebeckConwayPolynomial? 421 2 = some luebeckConwayPolynomial_421_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 421 [2, 417, 1]) = some luebeckConwayPolynomial_421_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 421 [2, 417, 1]) k =
        ([2, 417, 1].toArray.map (fun m => ZMod64.ofNat 421 m)).getD k
          (Zero.zero : ZMod64 421) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_421_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(491, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_491_2 : FpPoly 491 :=
  { coeffs := #[(2 : ZMod64 491), 487, 1]
    normalized := by right; decide }

/-- Monicity of C(491, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_491_2_monic : DensePoly.Monic luebeckConwayPolynomial_491_2 := by rfl

/-- Positive degree of C(491, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_491_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_491_2 := by decide

/-- Lookup identifies the imported C(491, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_491_2 :
    luebeckConwayPolynomial? 491 2 = some luebeckConwayPolynomial_491_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 491 [2, 487, 1]) = some luebeckConwayPolynomial_491_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 491 [2, 487, 1]) k =
        ([2, 487, 1].toArray.map (fun m => ZMod64.ofNat 491 m)).getD k
          (Zero.zero : ZMod64 491) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_491_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(139, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_139_2 : FpPoly 139 :=
  { coeffs := #[(2 : ZMod64 139), 138, 1]
    normalized := by right; decide }

/-- Monicity of C(139, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_139_2_monic : DensePoly.Monic luebeckConwayPolynomial_139_2 := by rfl

/-- Positive degree of C(139, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_139_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_139_2 := by decide

/-- Lookup identifies the imported C(139, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_139_2 :
    luebeckConwayPolynomial? 139 2 = some luebeckConwayPolynomial_139_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 139 [2, 138, 1]) = some luebeckConwayPolynomial_139_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 139 [2, 138, 1]) k =
        ([2, 138, 1].toArray.map (fun m => ZMod64.ofNat 139 m)).getD k
          (Zero.zero : ZMod64 139) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_139_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(229, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_229_2 : FpPoly 229 :=
  { coeffs := #[(6 : ZMod64 229), 228, 1]
    normalized := by right; decide }

/-- Monicity of C(229, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_229_2_monic : DensePoly.Monic luebeckConwayPolynomial_229_2 := by rfl

/-- Positive degree of C(229, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_229_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_229_2 := by decide

/-- Lookup identifies the imported C(229, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_229_2 :
    luebeckConwayPolynomial? 229 2 = some luebeckConwayPolynomial_229_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 229 [6, 228, 1]) = some luebeckConwayPolynomial_229_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 229 [6, 228, 1]) k =
        ([6, 228, 1].toArray.map (fun m => ZMod64.ofNat 229 m)).getD k
          (Zero.zero : ZMod64 229) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_229_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(557, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_557_2 : FpPoly 557 :=
  { coeffs := #[(2 : ZMod64 557), 553, 1]
    normalized := by right; decide }

/-- Monicity of C(557, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_557_2_monic : DensePoly.Monic luebeckConwayPolynomial_557_2 := by rfl

/-- Positive degree of C(557, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_557_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_557_2 := by decide

/-- Lookup identifies the imported C(557, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_557_2 :
    luebeckConwayPolynomial? 557 2 = some luebeckConwayPolynomial_557_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 557 [2, 553, 1]) = some luebeckConwayPolynomial_557_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 557 [2, 553, 1]) k =
        ([2, 553, 1].toArray.map (fun m => ZMod64.ofNat 557 m)).getD k
          (Zero.zero : ZMod64 557) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_557_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(607, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_607_2 : FpPoly 607 :=
  { coeffs := #[(3 : ZMod64 607), 606, 1]
    normalized := by right; decide }

/-- Monicity of C(607, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_607_2_monic : DensePoly.Monic luebeckConwayPolynomial_607_2 := by rfl

/-- Positive degree of C(607, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_607_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_607_2 := by decide

/-- Lookup identifies the imported C(607, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_607_2 :
    luebeckConwayPolynomial? 607 2 = some luebeckConwayPolynomial_607_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 607 [3, 606, 1]) = some luebeckConwayPolynomial_607_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 607 [3, 606, 1]) k =
        ([3, 606, 1].toArray.map (fun m => ZMod64.ofNat 607 m)).getD k
          (Zero.zero : ZMod64 607) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_607_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(653, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_653_2 : FpPoly 653 :=
  { coeffs := #[(2 : ZMod64 653), 649, 1]
    normalized := by right; decide }

/-- Monicity of C(653, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_653_2_monic : DensePoly.Monic luebeckConwayPolynomial_653_2 := by rfl

/-- Positive degree of C(653, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_653_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_653_2 := by decide

/-- Lookup identifies the imported C(653, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_653_2 :
    luebeckConwayPolynomial? 653 2 = some luebeckConwayPolynomial_653_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 653 [2, 649, 1]) = some luebeckConwayPolynomial_653_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 653 [2, 649, 1]) k =
        ([2, 649, 1].toArray.map (fun m => ZMod64.ofNat 653 m)).getD k
          (Zero.zero : ZMod64 653) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_653_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(733, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_733_2 : FpPoly 733 :=
  { coeffs := #[(6 : ZMod64 733), 732, 1]
    normalized := by right; decide }

/-- Monicity of C(733, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_733_2_monic : DensePoly.Monic luebeckConwayPolynomial_733_2 := by rfl

/-- Positive degree of C(733, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_733_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_733_2 := by decide

/-- Lookup identifies the imported C(733, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_733_2 :
    luebeckConwayPolynomial? 733 2 = some luebeckConwayPolynomial_733_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 733 [6, 732, 1]) = some luebeckConwayPolynomial_733_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 733 [6, 732, 1]) k =
        ([6, 732, 1].toArray.map (fun m => ZMod64.ofNat 733 m)).getD k
          (Zero.zero : ZMod64 733) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_733_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(787, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_787_2 : FpPoly 787 :=
  { coeffs := #[(2 : ZMod64 787), 786, 1]
    normalized := by right; decide }

/-- Monicity of C(787, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_787_2_monic : DensePoly.Monic luebeckConwayPolynomial_787_2 := by rfl

/-- Positive degree of C(787, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_787_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_787_2 := by decide

/-- Lookup identifies the imported C(787, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_787_2 :
    luebeckConwayPolynomial? 787 2 = some luebeckConwayPolynomial_787_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 787 [2, 786, 1]) = some luebeckConwayPolynomial_787_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 787 [2, 786, 1]) k =
        ([2, 786, 1].toArray.map (fun m => ZMod64.ofNat 787 m)).getD k
          (Zero.zero : ZMod64 787) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_787_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(887, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_887_2 : FpPoly 887 :=
  { coeffs := #[(5 : ZMod64 887), 885, 1]
    normalized := by right; decide }

/-- Monicity of C(887, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_887_2_monic : DensePoly.Monic luebeckConwayPolynomial_887_2 := by rfl

/-- Positive degree of C(887, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_887_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_887_2 := by decide

/-- Lookup identifies the imported C(887, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_887_2 :
    luebeckConwayPolynomial? 887 2 = some luebeckConwayPolynomial_887_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 887 [5, 885, 1]) = some luebeckConwayPolynomial_887_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 887 [5, 885, 1]) k =
        ([5, 885, 1].toArray.map (fun m => ZMod64.ofNat 887 m)).getD k
          (Zero.zero : ZMod64 887) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_887_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(983, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_983_2 : FpPoly 983 :=
  { coeffs := #[(5 : ZMod64 983), 981, 1]
    normalized := by right; decide }

/-- Monicity of C(983, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_983_2_monic : DensePoly.Monic luebeckConwayPolynomial_983_2 := by rfl

/-- Positive degree of C(983, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_983_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_983_2 := by decide

/-- Lookup identifies the imported C(983, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_983_2 :
    luebeckConwayPolynomial? 983 2 = some luebeckConwayPolynomial_983_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 983 [5, 981, 1]) = some luebeckConwayPolynomial_983_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 983 [5, 981, 1]) k =
        ([5, 981, 1].toArray.map (fun m => ZMod64.ofNat 983 m)).getD k
          (Zero.zero : ZMod64 983) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_983_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(271, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_271_2 : FpPoly 271 :=
  { coeffs := #[(6 : ZMod64 271), 269, 1]
    normalized := by right; decide }

/-- Monicity of C(271, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_271_2_monic : DensePoly.Monic luebeckConwayPolynomial_271_2 := by rfl

/-- Positive degree of C(271, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_271_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_271_2 := by decide

/-- Lookup identifies the imported C(271, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_271_2 :
    luebeckConwayPolynomial? 271 2 = some luebeckConwayPolynomial_271_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 271 [6, 269, 1]) = some luebeckConwayPolynomial_271_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 271 [6, 269, 1]) k =
        ([6, 269, 1].toArray.map (fun m => ZMod64.ofNat 271 m)).getD k
          (Zero.zero : ZMod64 271) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_271_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(313, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_313_2 : FpPoly 313 :=
  { coeffs := #[(10 : ZMod64 313), 310, 1]
    normalized := by right; decide }

/-- Monicity of C(313, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_313_2_monic : DensePoly.Monic luebeckConwayPolynomial_313_2 := by rfl

/-- Positive degree of C(313, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_313_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_313_2 := by decide

/-- Lookup identifies the imported C(313, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_313_2 :
    luebeckConwayPolynomial? 313 2 = some luebeckConwayPolynomial_313_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 313 [10, 310, 1]) = some luebeckConwayPolynomial_313_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 313 [10, 310, 1]) k =
        ([10, 310, 1].toArray.map (fun m => ZMod64.ofNat 313 m)).getD k
          (Zero.zero : ZMod64 313) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_313_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(353, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_353_2 : FpPoly 353 :=
  { coeffs := #[(3 : ZMod64 353), 348, 1]
    normalized := by right; decide }

/-- Monicity of C(353, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_353_2_monic : DensePoly.Monic luebeckConwayPolynomial_353_2 := by rfl

/-- Positive degree of C(353, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_353_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_353_2 := by decide

/-- Lookup identifies the imported C(353, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_353_2 :
    luebeckConwayPolynomial? 353 2 = some luebeckConwayPolynomial_353_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 353 [3, 348, 1]) = some luebeckConwayPolynomial_353_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 353 [3, 348, 1]) k =
        ([3, 348, 1].toArray.map (fun m => ZMod64.ofNat 353 m)).getD k
          (Zero.zero : ZMod64 353) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_353_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(401, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_401_2 : FpPoly 401 :=
  { coeffs := #[(3 : ZMod64 401), 396, 1]
    normalized := by right; decide }

/-- Monicity of C(401, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_401_2_monic : DensePoly.Monic luebeckConwayPolynomial_401_2 := by rfl

/-- Positive degree of C(401, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_401_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_401_2 := by decide

/-- Lookup identifies the imported C(401, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_401_2 :
    luebeckConwayPolynomial? 401 2 = some luebeckConwayPolynomial_401_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 401 [3, 396, 1]) = some luebeckConwayPolynomial_401_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 401 [3, 396, 1]) k =
        ([3, 396, 1].toArray.map (fun m => ZMod64.ofNat 401 m)).getD k
          (Zero.zero : ZMod64 401) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_401_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(457, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_457_2 : FpPoly 457 :=
  { coeffs := #[(13 : ZMod64 457), 454, 1]
    normalized := by right; decide }

/-- Monicity of C(457, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_457_2_monic : DensePoly.Monic luebeckConwayPolynomial_457_2 := by rfl

/-- Positive degree of C(457, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_457_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_457_2 := by decide

/-- Lookup identifies the imported C(457, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_457_2 :
    luebeckConwayPolynomial? 457 2 = some luebeckConwayPolynomial_457_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 457 [13, 454, 1]) = some luebeckConwayPolynomial_457_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 457 [13, 454, 1]) k =
        ([13, 454, 1].toArray.map (fun m => ZMod64.ofNat 457 m)).getD k
          (Zero.zero : ZMod64 457) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_457_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(503, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_503_2 : FpPoly 503 :=
  { coeffs := #[(5 : ZMod64 503), 498, 1]
    normalized := by right; decide }

/-- Monicity of C(503, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_503_2_monic : DensePoly.Monic luebeckConwayPolynomial_503_2 := by rfl

/-- Positive degree of C(503, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_503_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_503_2 := by decide

/-- Lookup identifies the imported C(503, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_503_2 :
    luebeckConwayPolynomial? 503 2 = some luebeckConwayPolynomial_503_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 503 [5, 498, 1]) = some luebeckConwayPolynomial_503_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 503 [5, 498, 1]) k =
        ([5, 498, 1].toArray.map (fun m => ZMod64.ofNat 503 m)).getD k
          (Zero.zero : ZMod64 503) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_503_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(149, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_149_2 : FpPoly 149 :=
  { coeffs := #[(2 : ZMod64 149), 145, 1]
    normalized := by right; decide }

/-- Monicity of C(149, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_149_2_monic : DensePoly.Monic luebeckConwayPolynomial_149_2 := by rfl

/-- Positive degree of C(149, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_149_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_149_2 := by decide

/-- Lookup identifies the imported C(149, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_149_2 :
    luebeckConwayPolynomial? 149 2 = some luebeckConwayPolynomial_149_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 149 [2, 145, 1]) = some luebeckConwayPolynomial_149_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 149 [2, 145, 1]) k =
        ([2, 145, 1].toArray.map (fun m => ZMod64.ofNat 149 m)).getD k
          (Zero.zero : ZMod64 149) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_149_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(173, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_173_2 : FpPoly 173 :=
  { coeffs := #[(2 : ZMod64 173), 169, 1]
    normalized := by right; decide }

/-- Monicity of C(173, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_173_2_monic : DensePoly.Monic luebeckConwayPolynomial_173_2 := by rfl

/-- Positive degree of C(173, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_173_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_173_2 := by decide

/-- Lookup identifies the imported C(173, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_173_2 :
    luebeckConwayPolynomial? 173 2 = some luebeckConwayPolynomial_173_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 173 [2, 169, 1]) = some luebeckConwayPolynomial_173_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 173 [2, 169, 1]) k =
        ([2, 169, 1].toArray.map (fun m => ZMod64.ofNat 173 m)).getD k
          (Zero.zero : ZMod64 173) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_173_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(199, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_199_2 : FpPoly 199 :=
  { coeffs := #[(3 : ZMod64 199), 193, 1]
    normalized := by right; decide }

/-- Monicity of C(199, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_199_2_monic : DensePoly.Monic luebeckConwayPolynomial_199_2 := by rfl

/-- Positive degree of C(199, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_199_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_199_2 := by decide

/-- Lookup identifies the imported C(199, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_199_2 :
    luebeckConwayPolynomial? 199 2 = some luebeckConwayPolynomial_199_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 199 [3, 193, 1]) = some luebeckConwayPolynomial_199_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 199 [3, 193, 1]) k =
        ([3, 193, 1].toArray.map (fun m => ZMod64.ofNat 199 m)).getD k
          (Zero.zero : ZMod64 199) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_199_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(241, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_241_2 : FpPoly 241 :=
  { coeffs := #[(7 : ZMod64 241), 238, 1]
    normalized := by right; decide }

/-- Monicity of C(241, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_241_2_monic : DensePoly.Monic luebeckConwayPolynomial_241_2 := by rfl

/-- Positive degree of C(241, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_241_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_241_2 := by decide

/-- Lookup identifies the imported C(241, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_241_2 :
    luebeckConwayPolynomial? 241 2 = some luebeckConwayPolynomial_241_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 241 [7, 238, 1]) = some luebeckConwayPolynomial_241_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 241 [7, 238, 1]) k =
        ([7, 238, 1].toArray.map (fun m => ZMod64.ofNat 241 m)).getD k
          (Zero.zero : ZMod64 241) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_241_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(577, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_577_2 : FpPoly 577 :=
  { coeffs := #[(5 : ZMod64 577), 572, 1]
    normalized := by right; decide }

/-- Monicity of C(577, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_577_2_monic : DensePoly.Monic luebeckConwayPolynomial_577_2 := by rfl

/-- Positive degree of C(577, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_577_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_577_2 := by decide

/-- Lookup identifies the imported C(577, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_577_2 :
    luebeckConwayPolynomial? 577 2 = some luebeckConwayPolynomial_577_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 577 [5, 572, 1]) = some luebeckConwayPolynomial_577_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 577 [5, 572, 1]) k =
        ([5, 572, 1].toArray.map (fun m => ZMod64.ofNat 577 m)).getD k
          (Zero.zero : ZMod64 577) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_577_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(79, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_79_2 : FpPoly 79 :=
  { coeffs := #[(3 : ZMod64 79), 78, 1]
    normalized := by right; decide }

/-- Monicity of C(79, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_79_2_monic : DensePoly.Monic luebeckConwayPolynomial_79_2 := by rfl

/-- Positive degree of C(79, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_79_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_79_2 := by decide

/-- Lookup identifies the imported C(79, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_79_2 :
    luebeckConwayPolynomial? 79 2 = some luebeckConwayPolynomial_79_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 79 [3, 78, 1]) = some luebeckConwayPolynomial_79_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 79 [3, 78, 1]) k =
        ([3, 78, 1].toArray.map (fun m => ZMod64.ofNat 79 m)).getD k
          (Zero.zero : ZMod64 79) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_79_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(101, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_101_2 : FpPoly 101 :=
  { coeffs := #[(2 : ZMod64 101), 97, 1]
    normalized := by right; decide }

/-- Monicity of C(101, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_101_2_monic : DensePoly.Monic luebeckConwayPolynomial_101_2 := by rfl

/-- Positive degree of C(101, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_101_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_101_2 := by decide

/-- Lookup identifies the imported C(101, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_101_2 :
    luebeckConwayPolynomial? 101 2 = some luebeckConwayPolynomial_101_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 101 [2, 97, 1]) = some luebeckConwayPolynomial_101_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 101 [2, 97, 1]) k =
        ([2, 97, 1].toArray.map (fun m => ZMod64.ofNat 101 m)).getD k
          (Zero.zero : ZMod64 101) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_101_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl


end Conway

end Hex
