/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Coefficients
public import HexConway.Entries.S1_3

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Imported C(7, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_7_3 : FpPoly 7 :=
  { coeffs := #[(4 : ZMod64 7), 0, 6, 1]
    normalized := by right; decide }

/-- Monicity of C(7, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_7_3_monic : DensePoly.Monic luebeckConwayPolynomial_7_3 := by rfl

/-- Positive degree of C(7, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_7_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_7_3 := by decide

/-- Lookup identifies the imported C(7, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_7_3 :
    luebeckConwayPolynomial? 7 3 = some luebeckConwayPolynomial_7_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 7 [4, 0, 6, 1]) = some luebeckConwayPolynomial_7_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 7 [4, 0, 6, 1]) k =
        ([4, 0, 6, 1].toArray.map (fun m => ZMod64.ofNat 7 m)).getD k
          (Zero.zero : ZMod64 7) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_7_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(863, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_863_2 : FpPoly 863 :=
  { coeffs := #[(5 : ZMod64 863), 862, 1]
    normalized := by right; decide }

/-- Monicity of C(863, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_863_2_monic : DensePoly.Monic luebeckConwayPolynomial_863_2 := by rfl

/-- Positive degree of C(863, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_863_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_863_2 := by decide

/-- Lookup identifies the imported C(863, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_863_2 :
    luebeckConwayPolynomial? 863 2 = some luebeckConwayPolynomial_863_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 863 [5, 862, 1]) = some luebeckConwayPolynomial_863_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 863 [5, 862, 1]) k =
        ([5, 862, 1].toArray.map (fun m => ZMod64.ofNat 863 m)).getD k
          (Zero.zero : ZMod64 863) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_863_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(103, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_103_2 : FpPoly 103 :=
  { coeffs := #[(5 : ZMod64 103), 102, 1]
    normalized := by right; decide }

/-- Monicity of C(103, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_103_2_monic : DensePoly.Monic luebeckConwayPolynomial_103_2 := by rfl

/-- Positive degree of C(103, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_103_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_103_2 := by decide

/-- Lookup identifies the imported C(103, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_103_2 :
    luebeckConwayPolynomial? 103 2 = some luebeckConwayPolynomial_103_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 103 [5, 102, 1]) = some luebeckConwayPolynomial_103_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 103 [5, 102, 1]) k =
        ([5, 102, 1].toArray.map (fun m => ZMod64.ofNat 103 m)).getD k
          (Zero.zero : ZMod64 103) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_103_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(383, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_383_2 : FpPoly 383 :=
  { coeffs := #[(5 : ZMod64 383), 382, 1]
    normalized := by right; decide }

/-- Monicity of C(383, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_383_2_monic : DensePoly.Monic luebeckConwayPolynomial_383_2 := by rfl

/-- Positive degree of C(383, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_383_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_383_2 := by decide

/-- Lookup identifies the imported C(383, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_383_2 :
    luebeckConwayPolynomial? 383 2 = some luebeckConwayPolynomial_383_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 383 [5, 382, 1]) = some luebeckConwayPolynomial_383_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 383 [5, 382, 1]) k =
        ([5, 382, 1].toArray.map (fun m => ZMod64.ofNat 383 m)).getD k
          (Zero.zero : ZMod64 383) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_383_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(59, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_59_2 : FpPoly 59 :=
  { coeffs := #[(2 : ZMod64 59), 58, 1]
    normalized := by right; decide }

/-- Monicity of C(59, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_59_2_monic : DensePoly.Monic luebeckConwayPolynomial_59_2 := by rfl

/-- Positive degree of C(59, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_59_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_59_2 := by decide

/-- Lookup identifies the imported C(59, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_59_2 :
    luebeckConwayPolynomial? 59 2 = some luebeckConwayPolynomial_59_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 59 [2, 58, 1]) = some luebeckConwayPolynomial_59_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 59 [2, 58, 1]) k =
        ([2, 58, 1].toArray.map (fun m => ZMod64.ofNat 59 m)).getD k
          (Zero.zero : ZMod64 59) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_59_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(193, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_193_2 : FpPoly 193 :=
  { coeffs := #[(5 : ZMod64 193), 192, 1]
    normalized := by right; decide }

/-- Monicity of C(193, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_193_2_monic : DensePoly.Monic luebeckConwayPolynomial_193_2 := by rfl

/-- Positive degree of C(193, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_193_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_193_2 := by decide

/-- Lookup identifies the imported C(193, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_193_2 :
    luebeckConwayPolynomial? 193 2 = some luebeckConwayPolynomial_193_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 193 [5, 192, 1]) = some luebeckConwayPolynomial_193_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 193 [5, 192, 1]) k =
        ([5, 192, 1].toArray.map (fun m => ZMod64.ofNat 193 m)).getD k
          (Zero.zero : ZMod64 193) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_193_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(5, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_5_3 : FpPoly 5 :=
  { coeffs := #[(3 : ZMod64 5), 3, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(5, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_5_3_monic : DensePoly.Monic luebeckConwayPolynomial_5_3 := by rfl

/-- Positive degree of C(5, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_5_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_5_3 := by decide

/-- Lookup identifies the imported C(5, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_5_3 :
    luebeckConwayPolynomial? 5 3 = some luebeckConwayPolynomial_5_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 5 [3, 3, 0, 1]) = some luebeckConwayPolynomial_5_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 5 [3, 3, 0, 1]) k =
        ([3, 3, 0, 1].toArray.map (fun m => ZMod64.ofNat 5 m)).getD k
          (Zero.zero : ZMod64 5) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_5_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(37, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_37_2 : FpPoly 37 :=
  { coeffs := #[(2 : ZMod64 37), 33, 1]
    normalized := by right; decide }

/-- Monicity of C(37, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_37_2_monic : DensePoly.Monic luebeckConwayPolynomial_37_2 := by rfl

/-- Positive degree of C(37, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_37_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_37_2 := by decide

/-- Lookup identifies the imported C(37, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_37_2 :
    luebeckConwayPolynomial? 37 2 = some luebeckConwayPolynomial_37_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 37 [2, 33, 1]) = some luebeckConwayPolynomial_37_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 37 [2, 33, 1]) k =
        ([2, 33, 1].toArray.map (fun m => ZMod64.ofNat 37 m)).getD k
          (Zero.zero : ZMod64 37) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_37_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(19, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_19_2 : FpPoly 19 :=
  { coeffs := #[(2 : ZMod64 19), 18, 1]
    normalized := by right; decide }

/-- Monicity of C(19, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_19_2_monic : DensePoly.Monic luebeckConwayPolynomial_19_2 := by rfl

/-- Positive degree of C(19, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_19_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_19_2 := by decide

/-- Lookup identifies the imported C(19, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_19_2 :
    luebeckConwayPolynomial? 19 2 = some luebeckConwayPolynomial_19_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 19 [2, 18, 1]) = some luebeckConwayPolynomial_19_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 19 [2, 18, 1]) k =
        ([2, 18, 1].toArray.map (fun m => ZMod64.ofNat 19 m)).getD k
          (Zero.zero : ZMod64 19) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_19_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(11, 2), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_11_2 : FpPoly 11 :=
  { coeffs := #[(2 : ZMod64 11), 7, 1]
    normalized := by right; decide }

/-- Monicity of C(11, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_11_2_monic : DensePoly.Monic luebeckConwayPolynomial_11_2 := by rfl

/-- Positive degree of C(11, 2). -/
@[simp, grind .] theorem luebeckConwayPolynomial_11_2_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_11_2 := by decide

/-- Lookup identifies the imported C(11, 2). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_11_2 :
    luebeckConwayPolynomial? 11 2 = some luebeckConwayPolynomial_11_2 := by
  show some (luebeckConwayPolynomialOfCoeffs 11 [2, 7, 1]) = some luebeckConwayPolynomial_11_2
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 11 [2, 7, 1]) k =
        ([2, 7, 1].toArray.map (fun m => ZMod64.ofNat 11 m)).getD k
          (Zero.zero : ZMod64 11) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_11_2]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | _ + 3 => rfl

/-- Imported C(547, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_547_1 : FpPoly 547 :=
  { coeffs := #[(545 : ZMod64 547), 1]
    normalized := by right; decide }

/-- Monicity of C(547, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_547_1_monic : DensePoly.Monic luebeckConwayPolynomial_547_1 := by rfl

/-- Positive degree of C(547, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_547_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_547_1 := by decide

/-- Lookup identifies the imported C(547, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_547_1 :
    luebeckConwayPolynomial? 547 1 = some luebeckConwayPolynomial_547_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 547 [545, 1]) = some luebeckConwayPolynomial_547_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 547 [545, 1]) k =
        ([545, 1].toArray.map (fun m => ZMod64.ofNat 547 m)).getD k
          (Zero.zero : ZMod64 547) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_547_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(691, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_691_1 : FpPoly 691 :=
  { coeffs := #[(688 : ZMod64 691), 1]
    normalized := by right; decide }

/-- Monicity of C(691, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_691_1_monic : DensePoly.Monic luebeckConwayPolynomial_691_1 := by rfl

/-- Positive degree of C(691, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_691_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_691_1 := by decide

/-- Lookup identifies the imported C(691, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_691_1 :
    luebeckConwayPolynomial? 691 1 = some luebeckConwayPolynomial_691_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 691 [688, 1]) = some luebeckConwayPolynomial_691_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 691 [688, 1]) k =
        ([688, 1].toArray.map (fun m => ZMod64.ofNat 691 m)).getD k
          (Zero.zero : ZMod64 691) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_691_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(991, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_991_1 : FpPoly 991 :=
  { coeffs := #[(985 : ZMod64 991), 1]
    normalized := by right; decide }

/-- Monicity of C(991, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_991_1_monic : DensePoly.Monic luebeckConwayPolynomial_991_1 := by rfl

/-- Positive degree of C(991, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_991_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_991_1 := by decide

/-- Lookup identifies the imported C(991, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_991_1 :
    luebeckConwayPolynomial? 991 1 = some luebeckConwayPolynomial_991_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 991 [985, 1]) = some luebeckConwayPolynomial_991_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 991 [985, 1]) k =
        ([985, 1].toArray.map (fun m => ZMod64.ofNat 991 m)).getD k
          (Zero.zero : ZMod64 991) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_991_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(521, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_521_1 : FpPoly 521 :=
  { coeffs := #[(518 : ZMod64 521), 1]
    normalized := by right; decide }

/-- Monicity of C(521, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_521_1_monic : DensePoly.Monic luebeckConwayPolynomial_521_1 := by rfl

/-- Positive degree of C(521, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_521_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_521_1 := by decide

/-- Lookup identifies the imported C(521, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_521_1 :
    luebeckConwayPolynomial? 521 1 = some luebeckConwayPolynomial_521_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 521 [518, 1]) = some luebeckConwayPolynomial_521_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 521 [518, 1]) k =
        ([518, 1].toArray.map (fun m => ZMod64.ofNat 521 m)).getD k
          (Zero.zero : ZMod64 521) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_521_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(599, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_599_1 : FpPoly 599 :=
  { coeffs := #[(592 : ZMod64 599), 1]
    normalized := by right; decide }

/-- Monicity of C(599, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_599_1_monic : DensePoly.Monic luebeckConwayPolynomial_599_1 := by rfl

/-- Positive degree of C(599, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_599_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_599_1 := by decide

/-- Lookup identifies the imported C(599, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_599_1 :
    luebeckConwayPolynomial? 599 1 = some luebeckConwayPolynomial_599_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 599 [592, 1]) = some luebeckConwayPolynomial_599_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 599 [592, 1]) k =
        ([592, 1].toArray.map (fun m => ZMod64.ofNat 599 m)).getD k
          (Zero.zero : ZMod64 599) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_599_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(617, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_617_1 : FpPoly 617 :=
  { coeffs := #[(614 : ZMod64 617), 1]
    normalized := by right; decide }

/-- Monicity of C(617, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_617_1_monic : DensePoly.Monic luebeckConwayPolynomial_617_1 := by rfl

/-- Positive degree of C(617, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_617_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_617_1 := by decide

/-- Lookup identifies the imported C(617, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_617_1 :
    luebeckConwayPolynomial? 617 1 = some luebeckConwayPolynomial_617_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 617 [614, 1]) = some luebeckConwayPolynomial_617_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 617 [614, 1]) k =
        ([614, 1].toArray.map (fun m => ZMod64.ofNat 617 m)).getD k
          (Zero.zero : ZMod64 617) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_617_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(659, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_659_1 : FpPoly 659 :=
  { coeffs := #[(657 : ZMod64 659), 1]
    normalized := by right; decide }

/-- Monicity of C(659, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_659_1_monic : DensePoly.Monic luebeckConwayPolynomial_659_1 := by rfl

/-- Positive degree of C(659, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_659_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_659_1 := by decide

/-- Lookup identifies the imported C(659, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_659_1 :
    luebeckConwayPolynomial? 659 1 = some luebeckConwayPolynomial_659_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 659 [657, 1]) = some luebeckConwayPolynomial_659_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 659 [657, 1]) k =
        ([657, 1].toArray.map (fun m => ZMod64.ofNat 659 m)).getD k
          (Zero.zero : ZMod64 659) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_659_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(709, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_709_1 : FpPoly 709 :=
  { coeffs := #[(707 : ZMod64 709), 1]
    normalized := by right; decide }

/-- Monicity of C(709, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_709_1_monic : DensePoly.Monic luebeckConwayPolynomial_709_1 := by rfl

/-- Positive degree of C(709, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_709_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_709_1 := by decide

/-- Lookup identifies the imported C(709, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_709_1 :
    luebeckConwayPolynomial? 709 1 = some luebeckConwayPolynomial_709_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 709 [707, 1]) = some luebeckConwayPolynomial_709_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 709 [707, 1]) k =
        ([707, 1].toArray.map (fun m => ZMod64.ofNat 709 m)).getD k
          (Zero.zero : ZMod64 709) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_709_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(743, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_743_1 : FpPoly 743 :=
  { coeffs := #[(738 : ZMod64 743), 1]
    normalized := by right; decide }

/-- Monicity of C(743, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_743_1_monic : DensePoly.Monic luebeckConwayPolynomial_743_1 := by rfl

/-- Positive degree of C(743, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_743_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_743_1 := by decide

/-- Lookup identifies the imported C(743, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_743_1 :
    luebeckConwayPolynomial? 743 1 = some luebeckConwayPolynomial_743_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 743 [738, 1]) = some luebeckConwayPolynomial_743_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 743 [738, 1]) k =
        ([738, 1].toArray.map (fun m => ZMod64.ofNat 743 m)).getD k
          (Zero.zero : ZMod64 743) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_743_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(787, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_787_1 : FpPoly 787 :=
  { coeffs := #[(785 : ZMod64 787), 1]
    normalized := by right; decide }

/-- Monicity of C(787, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_787_1_monic : DensePoly.Monic luebeckConwayPolynomial_787_1 := by rfl

/-- Positive degree of C(787, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_787_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_787_1 := by decide

/-- Lookup identifies the imported C(787, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_787_1 :
    luebeckConwayPolynomial? 787 1 = some luebeckConwayPolynomial_787_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 787 [785, 1]) = some luebeckConwayPolynomial_787_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 787 [785, 1]) k =
        ([785, 1].toArray.map (fun m => ZMod64.ofNat 787 m)).getD k
          (Zero.zero : ZMod64 787) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_787_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(827, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_827_1 : FpPoly 827 :=
  { coeffs := #[(825 : ZMod64 827), 1]
    normalized := by right; decide }

/-- Monicity of C(827, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_827_1_monic : DensePoly.Monic luebeckConwayPolynomial_827_1 := by rfl

/-- Positive degree of C(827, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_827_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_827_1 := by decide

/-- Lookup identifies the imported C(827, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_827_1 :
    luebeckConwayPolynomial? 827 1 = some luebeckConwayPolynomial_827_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 827 [825, 1]) = some luebeckConwayPolynomial_827_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 827 [825, 1]) k =
        ([825, 1].toArray.map (fun m => ZMod64.ofNat 827 m)).getD k
          (Zero.zero : ZMod64 827) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_827_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(881, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_881_1 : FpPoly 881 :=
  { coeffs := #[(878 : ZMod64 881), 1]
    normalized := by right; decide }

/-- Monicity of C(881, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_881_1_monic : DensePoly.Monic luebeckConwayPolynomial_881_1 := by rfl

/-- Positive degree of C(881, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_881_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_881_1 := by decide

/-- Lookup identifies the imported C(881, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_881_1 :
    luebeckConwayPolynomial? 881 1 = some luebeckConwayPolynomial_881_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 881 [878, 1]) = some luebeckConwayPolynomial_881_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 881 [878, 1]) k =
        ([878, 1].toArray.map (fun m => ZMod64.ofNat 881 m)).getD k
          (Zero.zero : ZMod64 881) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_881_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(937, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_937_1 : FpPoly 937 :=
  { coeffs := #[(932 : ZMod64 937), 1]
    normalized := by right; decide }

/-- Monicity of C(937, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_937_1_monic : DensePoly.Monic luebeckConwayPolynomial_937_1 := by rfl

/-- Positive degree of C(937, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_937_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_937_1 := by decide

/-- Lookup identifies the imported C(937, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_937_1 :
    luebeckConwayPolynomial? 937 1 = some luebeckConwayPolynomial_937_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 937 [932, 1]) = some luebeckConwayPolynomial_937_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 937 [932, 1]) k =
        ([932, 1].toArray.map (fun m => ZMod64.ofNat 937 m)).getD k
          (Zero.zero : ZMod64 937) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_937_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(971, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_971_1 : FpPoly 971 :=
  { coeffs := #[(965 : ZMod64 971), 1]
    normalized := by right; decide }

/-- Monicity of C(971, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_971_1_monic : DensePoly.Monic luebeckConwayPolynomial_971_1 := by rfl

/-- Positive degree of C(971, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_971_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_971_1 := by decide

/-- Lookup identifies the imported C(971, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_971_1 :
    luebeckConwayPolynomial? 971 1 = some luebeckConwayPolynomial_971_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 971 [965, 1]) = some luebeckConwayPolynomial_971_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 971 [965, 1]) k =
        ([965, 1].toArray.map (fun m => ZMod64.ofNat 971 m)).getD k
          (Zero.zero : ZMod64 971) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_971_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl


end Conway

end Hex
