/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Coefficients

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Imported C(2, 12), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_2_12 : FpPoly 2 :=
  { coeffs := #[(1 : ZMod64 2), 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(2, 12). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_12_monic : DensePoly.Monic luebeckConwayPolynomial_2_12 := by rfl

/-- Positive degree of C(2, 12). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_12_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_2_12 := by decide

/-- Lookup identifies the imported C(2, 12). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_2_12 :
    luebeckConwayPolynomial? 2 12 = some luebeckConwayPolynomial_2_12 := by
  show some (luebeckConwayPolynomialOfCoeffs 2 [1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1]) = some luebeckConwayPolynomial_2_12
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 2 [1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1]) k =
        ([1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 2 m)).getD k
          (Zero.zero : ZMod64 2) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_2_12]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | 8 => rfl
  | 9 => rfl
  | 10 => rfl
  | 11 => rfl
  | 12 => rfl
  | _ + 13 => rfl

/-- Imported C(5, 8), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_5_8 : FpPoly 5 :=
  { coeffs := #[(2 : ZMod64 5), 4, 3, 0, 1, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(5, 8). -/
@[simp, grind .] theorem luebeckConwayPolynomial_5_8_monic : DensePoly.Monic luebeckConwayPolynomial_5_8 := by rfl

/-- Positive degree of C(5, 8). -/
@[simp, grind .] theorem luebeckConwayPolynomial_5_8_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_5_8 := by decide

/-- Lookup identifies the imported C(5, 8). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_5_8 :
    luebeckConwayPolynomial? 5 8 = some luebeckConwayPolynomial_5_8 := by
  show some (luebeckConwayPolynomialOfCoeffs 5 [2, 4, 3, 0, 1, 0, 0, 0, 1]) = some luebeckConwayPolynomial_5_8
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 5 [2, 4, 3, 0, 1, 0, 0, 0, 1]) k =
        ([2, 4, 3, 0, 1, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 5 m)).getD k
          (Zero.zero : ZMod64 5) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_5_8]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | 8 => rfl
  | _ + 9 => rfl

/-- Imported C(2, 10), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_2_10 : FpPoly 2 :=
  { coeffs := #[(1 : ZMod64 2), 1, 1, 1, 0, 1, 1, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(2, 10). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_10_monic : DensePoly.Monic luebeckConwayPolynomial_2_10 := by rfl

/-- Positive degree of C(2, 10). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_10_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_2_10 := by decide

/-- Lookup identifies the imported C(2, 10). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_2_10 :
    luebeckConwayPolynomial? 2 10 = some luebeckConwayPolynomial_2_10 := by
  show some (luebeckConwayPolynomialOfCoeffs 2 [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1]) = some luebeckConwayPolynomial_2_10
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 2 [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1]) k =
        ([1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 2 m)).getD k
          (Zero.zero : ZMod64 2) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_2_10]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | 8 => rfl
  | 9 => rfl
  | 10 => rfl
  | _ + 11 => rfl

/-- Imported C(13, 6), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_13_6 : FpPoly 13 :=
  { coeffs := #[(2 : ZMod64 13), 11, 11, 10, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(13, 6). -/
@[simp, grind .] theorem luebeckConwayPolynomial_13_6_monic : DensePoly.Monic luebeckConwayPolynomial_13_6 := by rfl

/-- Positive degree of C(13, 6). -/
@[simp, grind .] theorem luebeckConwayPolynomial_13_6_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_13_6 := by decide

/-- Lookup identifies the imported C(13, 6). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_13_6 :
    luebeckConwayPolynomial? 13 6 = some luebeckConwayPolynomial_13_6 := by
  show some (luebeckConwayPolynomialOfCoeffs 13 [2, 11, 11, 10, 0, 0, 1]) = some luebeckConwayPolynomial_13_6
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 13 [2, 11, 11, 10, 0, 0, 1]) k =
        ([2, 11, 11, 10, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 13 m)).getD k
          (Zero.zero : ZMod64 13) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_13_6]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | _ + 7 => rfl

/-- Imported C(293, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_293_4 : FpPoly 293 :=
  { coeffs := #[(2 : ZMod64 293), 166, 3, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(293, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_293_4_monic : DensePoly.Monic luebeckConwayPolynomial_293_4 := by rfl

/-- Positive degree of C(293, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_293_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_293_4 := by decide

/-- Lookup identifies the imported C(293, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_293_4 :
    luebeckConwayPolynomial? 293 4 = some luebeckConwayPolynomial_293_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 293 [2, 166, 3, 0, 1]) = some luebeckConwayPolynomial_293_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 293 [2, 166, 3, 0, 1]) k =
        ([2, 166, 3, 0, 1].toArray.map (fun m => ZMod64.ofNat 293 m)).getD k
          (Zero.zero : ZMod64 293) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_293_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(211, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_211_4 : FpPoly 211 :=
  { coeffs := #[(2 : ZMod64 211), 161, 8, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(211, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_211_4_monic : DensePoly.Monic luebeckConwayPolynomial_211_4 := by rfl

/-- Positive degree of C(211, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_211_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_211_4 := by decide

/-- Lookup identifies the imported C(211, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_211_4 :
    luebeckConwayPolynomial? 211 4 = some luebeckConwayPolynomial_211_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 211 [2, 161, 8, 0, 1]) = some luebeckConwayPolynomial_211_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 211 [2, 161, 8, 0, 1]) k =
        ([2, 161, 8, 0, 1].toArray.map (fun m => ZMod64.ofNat 211 m)).getD k
          (Zero.zero : ZMod64 211) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_211_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(269, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_269_4 : FpPoly 269 :=
  { coeffs := #[(2 : ZMod64 269), 262, 8, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(269, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_269_4_monic : DensePoly.Monic luebeckConwayPolynomial_269_4 := by rfl

/-- Positive degree of C(269, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_269_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_269_4 := by decide

/-- Lookup identifies the imported C(269, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_269_4 :
    luebeckConwayPolynomial? 269 4 = some luebeckConwayPolynomial_269_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 269 [2, 262, 8, 0, 1]) = some luebeckConwayPolynomial_269_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 269 [2, 262, 8, 0, 1]) k =
        ([2, 262, 8, 0, 1].toArray.map (fun m => ZMod64.ofNat 269 m)).getD k
          (Zero.zero : ZMod64 269) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_269_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(2, 8), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_2_8 : FpPoly 2 :=
  { coeffs := #[(1 : ZMod64 2), 0, 1, 1, 1, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(2, 8). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_8_monic : DensePoly.Monic luebeckConwayPolynomial_2_8 := by rfl

/-- Positive degree of C(2, 8). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_8_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_2_8 := by decide

/-- Lookup identifies the imported C(2, 8). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_2_8 :
    luebeckConwayPolynomial? 2 8 = some luebeckConwayPolynomial_2_8 := by
  show some (luebeckConwayPolynomialOfCoeffs 2 [1, 0, 1, 1, 1, 0, 0, 0, 1]) = some luebeckConwayPolynomial_2_8
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 2 [1, 0, 1, 1, 1, 0, 0, 0, 1]) k =
        ([1, 0, 1, 1, 1, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 2 m)).getD k
          (Zero.zero : ZMod64 2) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_2_8]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | 8 => rfl
  | _ + 9 => rfl

/-- Imported C(139, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_139_4 : FpPoly 139 :=
  { coeffs := #[(2 : ZMod64 139), 96, 7, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(139, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_139_4_monic : DensePoly.Monic luebeckConwayPolynomial_139_4 := by rfl

/-- Positive degree of C(139, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_139_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_139_4 := by decide

/-- Lookup identifies the imported C(139, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_139_4 :
    luebeckConwayPolynomial? 139 4 = some luebeckConwayPolynomial_139_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 139 [2, 96, 7, 0, 1]) = some luebeckConwayPolynomial_139_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 139 [2, 96, 7, 0, 1]) k =
        ([2, 96, 7, 0, 1].toArray.map (fun m => ZMod64.ofNat 139 m)).getD k
          (Zero.zero : ZMod64 139) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_139_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(179, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_179_4 : FpPoly 179 :=
  { coeffs := #[(2 : ZMod64 179), 109, 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(179, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_179_4_monic : DensePoly.Monic luebeckConwayPolynomial_179_4 := by rfl

/-- Positive degree of C(179, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_179_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_179_4 := by decide

/-- Lookup identifies the imported C(179, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_179_4 :
    luebeckConwayPolynomial? 179 4 = some luebeckConwayPolynomial_179_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 179 [2, 109, 1, 0, 1]) = some luebeckConwayPolynomial_179_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 179 [2, 109, 1, 0, 1]) k =
        ([2, 109, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 179 m)).getD k
          (Zero.zero : ZMod64 179) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_179_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(227, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_227_4 : FpPoly 227 :=
  { coeffs := #[(2 : ZMod64 227), 143, 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(227, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_227_4_monic : DensePoly.Monic luebeckConwayPolynomial_227_4 := by rfl

/-- Positive degree of C(227, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_227_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_227_4 := by decide

/-- Lookup identifies the imported C(227, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_227_4 :
    luebeckConwayPolynomial? 227 4 = some luebeckConwayPolynomial_227_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 227 [2, 143, 1, 0, 1]) = some luebeckConwayPolynomial_227_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 227 [2, 143, 1, 0, 1]) k =
        ([2, 143, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 227 m)).getD k
          (Zero.zero : ZMod64 227) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_227_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(2, 9), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_2_9 : FpPoly 2 :=
  { coeffs := #[(1 : ZMod64 2), 0, 0, 0, 1, 0, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(2, 9). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_9_monic : DensePoly.Monic luebeckConwayPolynomial_2_9 := by rfl

/-- Positive degree of C(2, 9). -/
@[simp, grind .] theorem luebeckConwayPolynomial_2_9_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_2_9 := by decide

/-- Lookup identifies the imported C(2, 9). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_2_9 :
    luebeckConwayPolynomial? 2 9 = some luebeckConwayPolynomial_2_9 := by
  show some (luebeckConwayPolynomialOfCoeffs 2 [1, 0, 0, 0, 1, 0, 0, 0, 0, 1]) = some luebeckConwayPolynomial_2_9
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 2 [1, 0, 0, 0, 1, 0, 0, 0, 0, 1]) k =
        ([1, 0, 0, 0, 1, 0, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 2 m)).getD k
          (Zero.zero : ZMod64 2) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_2_9]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | 8 => rfl
  | 9 => rfl
  | _ + 10 => rfl

/-- Imported C(73, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_73_4 : FpPoly 73 :=
  { coeffs := #[(5 : ZMod64 73), 56, 16, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(73, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_73_4_monic : DensePoly.Monic luebeckConwayPolynomial_73_4 := by rfl

/-- Positive degree of C(73, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_73_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_73_4 := by decide

/-- Lookup identifies the imported C(73, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_73_4 :
    luebeckConwayPolynomial? 73 4 = some luebeckConwayPolynomial_73_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 73 [5, 56, 16, 0, 1]) = some luebeckConwayPolynomial_73_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 73 [5, 56, 16, 0, 1]) k =
        ([5, 56, 16, 0, 1].toArray.map (fun m => ZMod64.ofNat 73 m)).getD k
          (Zero.zero : ZMod64 73) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_73_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(113, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_113_4 : FpPoly 113 :=
  { coeffs := #[(3 : ZMod64 113), 62, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(113, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_113_4_monic : DensePoly.Monic luebeckConwayPolynomial_113_4 := by rfl

/-- Positive degree of C(113, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_113_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_113_4 := by decide

/-- Lookup identifies the imported C(113, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_113_4 :
    luebeckConwayPolynomial? 113 4 = some luebeckConwayPolynomial_113_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 113 [3, 62, 0, 0, 1]) = some luebeckConwayPolynomial_113_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 113 [3, 62, 0, 0, 1]) k =
        ([3, 62, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 113 m)).getD k
          (Zero.zero : ZMod64 113) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_113_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(193, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_193_4 : FpPoly 193 :=
  { coeffs := #[(5 : ZMod64 193), 148, 6, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(193, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_193_4_monic : DensePoly.Monic luebeckConwayPolynomial_193_4 := by rfl

/-- Positive degree of C(193, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_193_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_193_4 := by decide

/-- Lookup identifies the imported C(193, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_193_4 :
    luebeckConwayPolynomial? 193 4 = some luebeckConwayPolynomial_193_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 193 [5, 148, 6, 0, 1]) = some luebeckConwayPolynomial_193_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 193 [5, 148, 6, 0, 1]) k =
        ([5, 148, 6, 0, 1].toArray.map (fun m => ZMod64.ofNat 193 m)).getD k
          (Zero.zero : ZMod64 193) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_193_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(71, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_71_4 : FpPoly 71 :=
  { coeffs := #[(7 : ZMod64 71), 41, 4, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(71, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_71_4_monic : DensePoly.Monic luebeckConwayPolynomial_71_4 := by rfl

/-- Positive degree of C(71, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_71_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_71_4 := by decide

/-- Lookup identifies the imported C(71, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_71_4 :
    luebeckConwayPolynomial? 71 4 = some luebeckConwayPolynomial_71_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 71 [7, 41, 4, 0, 1]) = some luebeckConwayPolynomial_71_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 71 [7, 41, 4, 0, 1]) k =
        ([7, 41, 4, 0, 1].toArray.map (fun m => ZMod64.ofNat 71 m)).getD k
          (Zero.zero : ZMod64 71) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_71_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(107, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_107_4 : FpPoly 107 :=
  { coeffs := #[(2 : ZMod64 107), 79, 13, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(107, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_107_4_monic : DensePoly.Monic luebeckConwayPolynomial_107_4 := by rfl

/-- Positive degree of C(107, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_107_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_107_4 := by decide

/-- Lookup identifies the imported C(107, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_107_4 :
    luebeckConwayPolynomial? 107 4 = some luebeckConwayPolynomial_107_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 107 [2, 79, 13, 0, 1]) = some luebeckConwayPolynomial_107_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 107 [2, 79, 13, 0, 1]) k =
        ([2, 79, 13, 0, 1].toArray.map (fun m => ZMod64.ofNat 107 m)).getD k
          (Zero.zero : ZMod64 107) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_107_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(41, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_41_4 : FpPoly 41 :=
  { coeffs := #[(6 : ZMod64 41), 23, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(41, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_41_4_monic : DensePoly.Monic luebeckConwayPolynomial_41_4 := by rfl

/-- Positive degree of C(41, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_41_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_41_4 := by decide

/-- Lookup identifies the imported C(41, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_41_4 :
    luebeckConwayPolynomial? 41 4 = some luebeckConwayPolynomial_41_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 41 [6, 23, 0, 0, 1]) = some luebeckConwayPolynomial_41_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 41 [6, 23, 0, 0, 1]) k =
        ([6, 23, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 41 m)).getD k
          (Zero.zero : ZMod64 41) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_41_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(571, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_571_3 : FpPoly 571 :=
  { coeffs := #[(568 : ZMod64 571), 8, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(571, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_571_3_monic : DensePoly.Monic luebeckConwayPolynomial_571_3 := by rfl

/-- Positive degree of C(571, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_571_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_571_3 := by decide

/-- Lookup identifies the imported C(571, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_571_3 :
    luebeckConwayPolynomial? 571 3 = some luebeckConwayPolynomial_571_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 571 [568, 8, 0, 1]) = some luebeckConwayPolynomial_571_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 571 [568, 8, 0, 1]) k =
        ([568, 8, 0, 1].toArray.map (fun m => ZMod64.ofNat 571 m)).getD k
          (Zero.zero : ZMod64 571) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_571_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(631, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_631_3 : FpPoly 631 :=
  { coeffs := #[(628 : ZMod64 631), 5, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(631, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_631_3_monic : DensePoly.Monic luebeckConwayPolynomial_631_3 := by rfl

/-- Positive degree of C(631, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_631_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_631_3 := by decide

/-- Lookup identifies the imported C(631, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_631_3 :
    luebeckConwayPolynomial? 631 3 = some luebeckConwayPolynomial_631_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 631 [628, 5, 0, 1]) = some luebeckConwayPolynomial_631_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 631 [628, 5, 0, 1]) k =
        ([628, 5, 0, 1].toArray.map (fun m => ZMod64.ofNat 631 m)).getD k
          (Zero.zero : ZMod64 631) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_631_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(821, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_821_3 : FpPoly 821 :=
  { coeffs := #[(819 : ZMod64 821), 2, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(821, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_821_3_monic : DensePoly.Monic luebeckConwayPolynomial_821_3 := by rfl

/-- Positive degree of C(821, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_821_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_821_3 := by decide

/-- Lookup identifies the imported C(821, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_821_3 :
    luebeckConwayPolynomial? 821 3 = some luebeckConwayPolynomial_821_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 821 [819, 2, 0, 1]) = some luebeckConwayPolynomial_821_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 821 [819, 2, 0, 1]) k =
        ([819, 2, 0, 1].toArray.map (fun m => ZMod64.ofNat 821 m)).getD k
          (Zero.zero : ZMod64 821) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_821_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(967, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_967_3 : FpPoly 967 :=
  { coeffs := #[(962 : ZMod64 967), 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(967, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_967_3_monic : DensePoly.Monic luebeckConwayPolynomial_967_3 := by rfl

/-- Positive degree of C(967, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_967_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_967_3 := by decide

/-- Lookup identifies the imported C(967, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_967_3 :
    luebeckConwayPolynomial? 967 3 = some luebeckConwayPolynomial_967_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 967 [962, 1, 0, 1]) = some luebeckConwayPolynomial_967_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 967 [962, 1, 0, 1]) k =
        ([962, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 967 m)).getD k
          (Zero.zero : ZMod64 967) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_967_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(29, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_29_4 : FpPoly 29 :=
  { coeffs := #[(2 : ZMod64 29), 15, 2, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(29, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_29_4_monic : DensePoly.Monic luebeckConwayPolynomial_29_4 := by rfl

/-- Positive degree of C(29, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_29_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_29_4 := by decide

/-- Lookup identifies the imported C(29, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_29_4 :
    luebeckConwayPolynomial? 29 4 = some luebeckConwayPolynomial_29_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 29 [2, 15, 2, 0, 1]) = some luebeckConwayPolynomial_29_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 29 [2, 15, 2, 0, 1]) k =
        ([2, 15, 2, 0, 1].toArray.map (fun m => ZMod64.ofNat 29 m)).getD k
          (Zero.zero : ZMod64 29) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_29_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(13, 5), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_13_5 : FpPoly 13 :=
  { coeffs := #[(11 : ZMod64 13), 4, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(13, 5). -/
@[simp, grind .] theorem luebeckConwayPolynomial_13_5_monic : DensePoly.Monic luebeckConwayPolynomial_13_5 := by rfl

/-- Positive degree of C(13, 5). -/
@[simp, grind .] theorem luebeckConwayPolynomial_13_5_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_13_5 := by decide

/-- Lookup identifies the imported C(13, 5). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_13_5 :
    luebeckConwayPolynomial? 13 5 = some luebeckConwayPolynomial_13_5 := by
  show some (luebeckConwayPolynomialOfCoeffs 13 [11, 4, 0, 0, 0, 1]) = some luebeckConwayPolynomial_13_5
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 13 [11, 4, 0, 0, 0, 1]) k =
        ([11, 4, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 13 m)).getD k
          (Zero.zero : ZMod64 13) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_13_5]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | _ + 6 => rfl


end Conway

end Hex
