/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Coefficients
public import HexConway.Entries.S3_0

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Imported C(431, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_431_3 : FpPoly 431 :=
  { coeffs := #[(424 : ZMod64 431), 2, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(431, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_431_3_monic : DensePoly.Monic luebeckConwayPolynomial_431_3 := by rfl

/-- Positive degree of C(431, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_431_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_431_3 := by decide

/-- Lookup identifies the imported C(431, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_431_3 :
    luebeckConwayPolynomial? 431 3 = some luebeckConwayPolynomial_431_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 431 [424, 2, 0, 1]) = some luebeckConwayPolynomial_431_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 431 [424, 2, 0, 1]) k =
        ([424, 2, 0, 1].toArray.map (fun m => ZMod64.ofNat 431 m)).getD k
          (Zero.zero : ZMod64 431) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_431_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(523, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_523_3 : FpPoly 523 :=
  { coeffs := #[(521 : ZMod64 523), 5, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(523, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_523_3_monic : DensePoly.Monic luebeckConwayPolynomial_523_3 := by rfl

/-- Positive degree of C(523, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_523_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_523_3 := by decide

/-- Lookup identifies the imported C(523, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_523_3 :
    luebeckConwayPolynomial? 523 3 = some luebeckConwayPolynomial_523_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 523 [521, 5, 0, 1]) = some luebeckConwayPolynomial_523_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 523 [521, 5, 0, 1]) k =
        ([521, 5, 0, 1].toArray.map (fun m => ZMod64.ofNat 523 m)).getD k
          (Zero.zero : ZMod64 523) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_523_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(607, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_607_3 : FpPoly 607 :=
  { coeffs := #[(604 : ZMod64 607), 5, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(607, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_607_3_monic : DensePoly.Monic luebeckConwayPolynomial_607_3 := by rfl

/-- Positive degree of C(607, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_607_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_607_3 := by decide

/-- Lookup identifies the imported C(607, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_607_3 :
    luebeckConwayPolynomial? 607 3 = some luebeckConwayPolynomial_607_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 607 [604, 5, 0, 1]) = some luebeckConwayPolynomial_607_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 607 [604, 5, 0, 1]) k =
        ([604, 5, 0, 1].toArray.map (fun m => ZMod64.ofNat 607 m)).getD k
          (Zero.zero : ZMod64 607) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_607_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(643, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_643_3 : FpPoly 643 :=
  { coeffs := #[(632 : ZMod64 643), 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(643, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_643_3_monic : DensePoly.Monic luebeckConwayPolynomial_643_3 := by rfl

/-- Positive degree of C(643, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_643_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_643_3 := by decide

/-- Lookup identifies the imported C(643, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_643_3 :
    luebeckConwayPolynomial? 643 3 = some luebeckConwayPolynomial_643_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 643 [632, 1, 0, 1]) = some luebeckConwayPolynomial_643_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 643 [632, 1, 0, 1]) k =
        ([632, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 643 m)).getD k
          (Zero.zero : ZMod64 643) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_643_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(661, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_661_3 : FpPoly 661 :=
  { coeffs := #[(659 : ZMod64 661), 4, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(661, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_661_3_monic : DensePoly.Monic luebeckConwayPolynomial_661_3 := by rfl

/-- Positive degree of C(661, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_661_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_661_3 := by decide

/-- Lookup identifies the imported C(661, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_661_3 :
    luebeckConwayPolynomial? 661 3 = some luebeckConwayPolynomial_661_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 661 [659, 4, 0, 1]) = some luebeckConwayPolynomial_661_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 661 [659, 4, 0, 1]) k =
        ([659, 4, 0, 1].toArray.map (fun m => ZMod64.ofNat 661 m)).getD k
          (Zero.zero : ZMod64 661) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_661_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(739, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_739_3 : FpPoly 739 :=
  { coeffs := #[(736 : ZMod64 739), 11, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(739, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_739_3_monic : DensePoly.Monic luebeckConwayPolynomial_739_3 := by rfl

/-- Positive degree of C(739, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_739_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_739_3 := by decide

/-- Lookup identifies the imported C(739, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_739_3 :
    luebeckConwayPolynomial? 739 3 = some luebeckConwayPolynomial_739_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 739 [736, 11, 0, 1]) = some luebeckConwayPolynomial_739_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 739 [736, 11, 0, 1]) k =
        ([736, 11, 0, 1].toArray.map (fun m => ZMod64.ofNat 739 m)).getD k
          (Zero.zero : ZMod64 739) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_739_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(829, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_829_3 : FpPoly 829 :=
  { coeffs := #[(827 : ZMod64 829), 5, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(829, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_829_3_monic : DensePoly.Monic luebeckConwayPolynomial_829_3 := by rfl

/-- Positive degree of C(829, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_829_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_829_3 := by decide

/-- Lookup identifies the imported C(829, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_829_3 :
    luebeckConwayPolynomial? 829 3 = some luebeckConwayPolynomial_829_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 829 [827, 5, 0, 1]) = some luebeckConwayPolynomial_829_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 829 [827, 5, 0, 1]) k =
        ([827, 5, 0, 1].toArray.map (fun m => ZMod64.ofNat 829 m)).getD k
          (Zero.zero : ZMod64 829) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_829_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(907, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_907_3 : FpPoly 907 :=
  { coeffs := #[(905 : ZMod64 907), 4, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(907, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_907_3_monic : DensePoly.Monic luebeckConwayPolynomial_907_3 := by rfl

/-- Positive degree of C(907, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_907_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_907_3 := by decide

/-- Lookup identifies the imported C(907, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_907_3 :
    luebeckConwayPolynomial? 907 3 = some luebeckConwayPolynomial_907_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 907 [905, 4, 0, 1]) = some luebeckConwayPolynomial_907_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 907 [905, 4, 0, 1]) k =
        ([905, 4, 0, 1].toArray.map (fun m => ZMod64.ofNat 907 m)).getD k
          (Zero.zero : ZMod64 907) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_907_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(3, 6), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_3_6 : FpPoly 3 :=
  { coeffs := #[(2 : ZMod64 3), 2, 1, 0, 2, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(3, 6). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_6_monic : DensePoly.Monic luebeckConwayPolynomial_3_6 := by rfl

/-- Positive degree of C(3, 6). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_6_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_3_6 := by decide

/-- Lookup identifies the imported C(3, 6). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_3_6 :
    luebeckConwayPolynomial? 3 6 = some luebeckConwayPolynomial_3_6 := by
  show some (luebeckConwayPolynomialOfCoeffs 3 [2, 2, 1, 0, 2, 0, 1]) = some luebeckConwayPolynomial_3_6
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 3 [2, 2, 1, 0, 2, 0, 1]) k =
        ([2, 2, 1, 0, 2, 0, 1].toArray.map (fun m => ZMod64.ofNat 3 m)).getD k
          (Zero.zero : ZMod64 3) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_3_6]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | _ + 7 => rfl

/-- Imported C(17, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_17_4 : FpPoly 17 :=
  { coeffs := #[(3 : ZMod64 17), 10, 7, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(17, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_17_4_monic : DensePoly.Monic luebeckConwayPolynomial_17_4 := by rfl

/-- Positive degree of C(17, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_17_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_17_4 := by decide

/-- Lookup identifies the imported C(17, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_17_4 :
    luebeckConwayPolynomial? 17 4 = some luebeckConwayPolynomial_17_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 17 [3, 10, 7, 0, 1]) = some luebeckConwayPolynomial_17_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 17 [3, 10, 7, 0, 1]) k =
        ([3, 10, 7, 0, 1].toArray.map (fun m => ZMod64.ofNat 17 m)).getD k
          (Zero.zero : ZMod64 17) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_17_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl

/-- Imported C(281, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_281_3 : FpPoly 281 :=
  { coeffs := #[(278 : ZMod64 281), 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(281, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_281_3_monic : DensePoly.Monic luebeckConwayPolynomial_281_3 := by rfl

/-- Positive degree of C(281, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_281_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_281_3 := by decide

/-- Lookup identifies the imported C(281, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_281_3 :
    luebeckConwayPolynomial? 281 3 = some luebeckConwayPolynomial_281_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 281 [278, 1, 0, 1]) = some luebeckConwayPolynomial_281_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 281 [278, 1, 0, 1]) k =
        ([278, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 281 m)).getD k
          (Zero.zero : ZMod64 281) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_281_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(337, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_337_3 : FpPoly 337 :=
  { coeffs := #[(327 : ZMod64 337), 2, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(337, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_337_3_monic : DensePoly.Monic luebeckConwayPolynomial_337_3 := by rfl

/-- Positive degree of C(337, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_337_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_337_3 := by decide

/-- Lookup identifies the imported C(337, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_337_3 :
    luebeckConwayPolynomial? 337 3 = some luebeckConwayPolynomial_337_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 337 [327, 2, 0, 1]) = some luebeckConwayPolynomial_337_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 337 [327, 2, 0, 1]) k =
        ([327, 2, 0, 1].toArray.map (fun m => ZMod64.ofNat 337 m)).getD k
          (Zero.zero : ZMod64 337) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_337_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(367, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_367_3 : FpPoly 367 :=
  { coeffs := #[(361 : ZMod64 367), 10, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(367, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_367_3_monic : DensePoly.Monic luebeckConwayPolynomial_367_3 := by rfl

/-- Positive degree of C(367, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_367_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_367_3 := by decide

/-- Lookup identifies the imported C(367, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_367_3 :
    luebeckConwayPolynomial? 367 3 = some luebeckConwayPolynomial_367_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 367 [361, 10, 0, 1]) = some luebeckConwayPolynomial_367_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 367 [361, 10, 0, 1]) k =
        ([361, 10, 0, 1].toArray.map (fun m => ZMod64.ofNat 367 m)).getD k
          (Zero.zero : ZMod64 367) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_367_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(421, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_421_3 : FpPoly 421 :=
  { coeffs := #[(419 : ZMod64 421), 2, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(421, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_421_3_monic : DensePoly.Monic luebeckConwayPolynomial_421_3 := by rfl

/-- Positive degree of C(421, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_421_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_421_3 := by decide

/-- Lookup identifies the imported C(421, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_421_3 :
    luebeckConwayPolynomial? 421 3 = some luebeckConwayPolynomial_421_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 421 [419, 2, 0, 1]) = some luebeckConwayPolynomial_421_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 421 [419, 2, 0, 1]) k =
        ([419, 2, 0, 1].toArray.map (fun m => ZMod64.ofNat 421 m)).getD k
          (Zero.zero : ZMod64 421) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_421_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(461, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_461_3 : FpPoly 461 :=
  { coeffs := #[(459 : ZMod64 461), 3, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(461, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_461_3_monic : DensePoly.Monic luebeckConwayPolynomial_461_3 := by rfl

/-- Positive degree of C(461, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_461_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_461_3 := by decide

/-- Lookup identifies the imported C(461, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_461_3 :
    luebeckConwayPolynomial? 461 3 = some luebeckConwayPolynomial_461_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 461 [459, 3, 0, 1]) = some luebeckConwayPolynomial_461_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 461 [459, 3, 0, 1]) k =
        ([459, 3, 0, 1].toArray.map (fun m => ZMod64.ofNat 461 m)).getD k
          (Zero.zero : ZMod64 461) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_461_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(7, 5), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_7_5 : FpPoly 7 :=
  { coeffs := #[(4 : ZMod64 7), 1, 0, 0, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(7, 5). -/
@[simp, grind .] theorem luebeckConwayPolynomial_7_5_monic : DensePoly.Monic luebeckConwayPolynomial_7_5 := by rfl

/-- Positive degree of C(7, 5). -/
@[simp, grind .] theorem luebeckConwayPolynomial_7_5_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_7_5 := by decide

/-- Lookup identifies the imported C(7, 5). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_7_5 :
    luebeckConwayPolynomial? 7 5 = some luebeckConwayPolynomial_7_5 := by
  show some (luebeckConwayPolynomialOfCoeffs 7 [4, 1, 0, 0, 0, 1]) = some luebeckConwayPolynomial_7_5
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 7 [4, 1, 0, 0, 0, 1]) k =
        ([4, 1, 0, 0, 0, 1].toArray.map (fun m => ZMod64.ofNat 7 m)).getD k
          (Zero.zero : ZMod64 7) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_7_5]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | _ + 6 => rfl

/-- Imported C(151, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_151_3 : FpPoly 151 :=
  { coeffs := #[(145 : ZMod64 151), 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(151, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_151_3_monic : DensePoly.Monic luebeckConwayPolynomial_151_3 := by rfl

/-- Positive degree of C(151, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_151_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_151_3 := by decide

/-- Lookup identifies the imported C(151, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_151_3 :
    luebeckConwayPolynomial? 151 3 = some luebeckConwayPolynomial_151_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 151 [145, 1, 0, 1]) = some luebeckConwayPolynomial_151_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 151 [145, 1, 0, 1]) k =
        ([145, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 151 m)).getD k
          (Zero.zero : ZMod64 151) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_151_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(239, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_239_3 : FpPoly 239 :=
  { coeffs := #[(232 : ZMod64 239), 11, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(239, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_239_3_monic : DensePoly.Monic luebeckConwayPolynomial_239_3 := by rfl

/-- Positive degree of C(239, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_239_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_239_3 := by decide

/-- Lookup identifies the imported C(239, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_239_3 :
    luebeckConwayPolynomial? 239 3 = some luebeckConwayPolynomial_239_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 239 [232, 11, 0, 1]) = some luebeckConwayPolynomial_239_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 239 [232, 11, 0, 1]) k =
        ([232, 11, 0, 1].toArray.map (fun m => ZMod64.ofNat 239 m)).getD k
          (Zero.zero : ZMod64 239) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_239_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(577, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_577_3 : FpPoly 577 :=
  { coeffs := #[(572 : ZMod64 577), 2, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(577, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_577_3_monic : DensePoly.Monic luebeckConwayPolynomial_577_3 := by rfl

/-- Positive degree of C(577, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_577_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_577_3 := by decide

/-- Lookup identifies the imported C(577, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_577_3 :
    luebeckConwayPolynomial? 577 3 = some luebeckConwayPolynomial_577_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 577 [572, 2, 0, 1]) = some luebeckConwayPolynomial_577_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 577 [572, 2, 0, 1]) k =
        ([572, 2, 0, 1].toArray.map (fun m => ZMod64.ofNat 577 m)).getD k
          (Zero.zero : ZMod64 577) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_577_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(673, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_673_3 : FpPoly 673 :=
  { coeffs := #[(668 : ZMod64 673), 1, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(673, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_673_3_monic : DensePoly.Monic luebeckConwayPolynomial_673_3 := by rfl

/-- Positive degree of C(673, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_673_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_673_3 := by decide

/-- Lookup identifies the imported C(673, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_673_3 :
    luebeckConwayPolynomial? 673 3 = some luebeckConwayPolynomial_673_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 673 [668, 1, 0, 1]) = some luebeckConwayPolynomial_673_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 673 [668, 1, 0, 1]) k =
        ([668, 1, 0, 1].toArray.map (fun m => ZMod64.ofNat 673 m)).getD k
          (Zero.zero : ZMod64 673) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_673_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(743, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_743_3 : FpPoly 743 :=
  { coeffs := #[(738 : ZMod64 743), 3, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(743, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_743_3_monic : DensePoly.Monic luebeckConwayPolynomial_743_3 := by rfl

/-- Positive degree of C(743, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_743_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_743_3 := by decide

/-- Lookup identifies the imported C(743, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_743_3 :
    luebeckConwayPolynomial? 743 3 = some luebeckConwayPolynomial_743_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 743 [738, 3, 0, 1]) = some luebeckConwayPolynomial_743_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 743 [738, 3, 0, 1]) k =
        ([738, 3, 0, 1].toArray.map (fun m => ZMod64.ofNat 743 m)).getD k
          (Zero.zero : ZMod64 743) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_743_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(827, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_827_3 : FpPoly 827 :=
  { coeffs := #[(825 : ZMod64 827), 5, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(827, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_827_3_monic : DensePoly.Monic luebeckConwayPolynomial_827_3 := by rfl

/-- Positive degree of C(827, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_827_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_827_3 := by decide

/-- Lookup identifies the imported C(827, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_827_3 :
    luebeckConwayPolynomial? 827 3 = some luebeckConwayPolynomial_827_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 827 [825, 5, 0, 1]) = some luebeckConwayPolynomial_827_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 827 [825, 5, 0, 1]) k =
        ([825, 5, 0, 1].toArray.map (fun m => ZMod64.ofNat 827 m)).getD k
          (Zero.zero : ZMod64 827) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_827_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(929, 3), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_929_3 : FpPoly 929 :=
  { coeffs := #[(926 : ZMod64 929), 5, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(929, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_929_3_monic : DensePoly.Monic luebeckConwayPolynomial_929_3 := by rfl

/-- Positive degree of C(929, 3). -/
@[simp, grind .] theorem luebeckConwayPolynomial_929_3_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_929_3 := by decide

/-- Lookup identifies the imported C(929, 3). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_929_3 :
    luebeckConwayPolynomial? 929 3 = some luebeckConwayPolynomial_929_3 := by
  show some (luebeckConwayPolynomialOfCoeffs 929 [926, 5, 0, 1]) = some luebeckConwayPolynomial_929_3
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 929 [926, 5, 0, 1]) k =
        ([926, 5, 0, 1].toArray.map (fun m => ZMod64.ofNat 929 m)).getD k
          (Zero.zero : ZMod64 929) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_929_3]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | _ + 4 => rfl

/-- Imported C(11, 4), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_11_4 : FpPoly 11 :=
  { coeffs := #[(2 : ZMod64 11), 10, 8, 0, 1]
    normalized := by right; decide }

/-- Monicity of C(11, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_11_4_monic : DensePoly.Monic luebeckConwayPolynomial_11_4 := by rfl

/-- Positive degree of C(11, 4). -/
@[simp, grind .] theorem luebeckConwayPolynomial_11_4_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_11_4 := by decide

/-- Lookup identifies the imported C(11, 4). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_11_4 :
    luebeckConwayPolynomial? 11 4 = some luebeckConwayPolynomial_11_4 := by
  show some (luebeckConwayPolynomialOfCoeffs 11 [2, 10, 8, 0, 1]) = some luebeckConwayPolynomial_11_4
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 11 [2, 10, 8, 0, 1]) k =
        ([2, 10, 8, 0, 1].toArray.map (fun m => ZMod64.ofNat 11 m)).getD k
          (Zero.zero : ZMod64 11) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_11_4]
  match k with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | _ + 5 => rfl


end Conway

end Hex
