/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Coefficients
public import HexConway.Entries.S3_5

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Imported C(73, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_73_1 : FpPoly 73 :=
  { coeffs := #[(68 : ZMod64 73), 1]
    normalized := by right; decide }

/-- Monicity of C(73, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_73_1_monic : DensePoly.Monic luebeckConwayPolynomial_73_1 := by rfl

/-- Positive degree of C(73, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_73_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_73_1 := by decide

/-- Lookup identifies the imported C(73, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_73_1 :
    luebeckConwayPolynomial? 73 1 = some luebeckConwayPolynomial_73_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 73 [68, 1]) = some luebeckConwayPolynomial_73_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 73 [68, 1]) k =
        ([68, 1].toArray.map (fun m => ZMod64.ofNat 73 m)).getD k
          (Zero.zero : ZMod64 73) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_73_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(83, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_83_1 : FpPoly 83 :=
  { coeffs := #[(81 : ZMod64 83), 1]
    normalized := by right; decide }

/-- Monicity of C(83, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_83_1_monic : DensePoly.Monic luebeckConwayPolynomial_83_1 := by rfl

/-- Positive degree of C(83, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_83_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_83_1 := by decide

/-- Lookup identifies the imported C(83, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_83_1 :
    luebeckConwayPolynomial? 83 1 = some luebeckConwayPolynomial_83_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 83 [81, 1]) = some luebeckConwayPolynomial_83_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 83 [81, 1]) k =
        ([81, 1].toArray.map (fun m => ZMod64.ofNat 83 m)).getD k
          (Zero.zero : ZMod64 83) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_83_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(107, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_107_1 : FpPoly 107 :=
  { coeffs := #[(105 : ZMod64 107), 1]
    normalized := by right; decide }

/-- Monicity of C(107, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_107_1_monic : DensePoly.Monic luebeckConwayPolynomial_107_1 := by rfl

/-- Positive degree of C(107, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_107_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_107_1 := by decide

/-- Lookup identifies the imported C(107, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_107_1 :
    luebeckConwayPolynomial? 107 1 = some luebeckConwayPolynomial_107_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 107 [105, 1]) = some luebeckConwayPolynomial_107_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 107 [105, 1]) k =
        ([105, 1].toArray.map (fun m => ZMod64.ofNat 107 m)).getD k
          (Zero.zero : ZMod64 107) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_107_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(47, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_47_1 : FpPoly 47 :=
  { coeffs := #[(42 : ZMod64 47), 1]
    normalized := by right; decide }

/-- Monicity of C(47, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_47_1_monic : DensePoly.Monic luebeckConwayPolynomial_47_1 := by rfl

/-- Positive degree of C(47, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_47_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_47_1 := by decide

/-- Lookup identifies the imported C(47, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_47_1 :
    luebeckConwayPolynomial? 47 1 = some luebeckConwayPolynomial_47_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 47 [42, 1]) = some luebeckConwayPolynomial_47_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 47 [42, 1]) k =
        ([42, 1].toArray.map (fun m => ZMod64.ofNat 47 m)).getD k
          (Zero.zero : ZMod64 47) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_47_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(23, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_23_1 : FpPoly 23 :=
  { coeffs := #[(18 : ZMod64 23), 1]
    normalized := by right; decide }

/-- Monicity of C(23, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_23_1_monic : DensePoly.Monic luebeckConwayPolynomial_23_1 := by rfl

/-- Positive degree of C(23, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_23_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_23_1 := by decide

/-- Lookup identifies the imported C(23, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_23_1 :
    luebeckConwayPolynomial? 23 1 = some luebeckConwayPolynomial_23_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 23 [18, 1]) = some luebeckConwayPolynomial_23_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 23 [18, 1]) k =
        ([18, 1].toArray.map (fun m => ZMod64.ofNat 23 m)).getD k
          (Zero.zero : ZMod64 23) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_23_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(7, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_7_1 : FpPoly 7 :=
  { coeffs := #[(4 : ZMod64 7), 1]
    normalized := by right; decide }

/-- Monicity of C(7, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_7_1_monic : DensePoly.Monic luebeckConwayPolynomial_7_1 := by rfl

/-- Positive degree of C(7, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_7_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_7_1 := by decide

/-- Lookup identifies the imported C(7, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_7_1 :
    luebeckConwayPolynomial? 7 1 = some luebeckConwayPolynomial_7_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 7 [4, 1]) = some luebeckConwayPolynomial_7_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 7 [4, 1]) k =
        ([4, 1].toArray.map (fun m => ZMod64.ofNat 7 m)).getD k
          (Zero.zero : ZMod64 7) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_7_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl

/-- Imported C(3, 1), with ascending coefficients. -/
@[expose] def luebeckConwayPolynomial_3_1 : FpPoly 3 :=
  { coeffs := #[(1 : ZMod64 3), 1]
    normalized := by right; decide }

/-- Monicity of C(3, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_1_monic : DensePoly.Monic luebeckConwayPolynomial_3_1 := by rfl

/-- Positive degree of C(3, 1). -/
@[simp, grind .] theorem luebeckConwayPolynomial_3_1_degree_pos : 0 < FpPoly.degree luebeckConwayPolynomial_3_1 := by decide

/-- Lookup identifies the imported C(3, 1). -/
@[simp, grind =] theorem luebeckConwayPolynomial?_hit_3_1 :
    luebeckConwayPolynomial? 3 1 = some luebeckConwayPolynomial_3_1 := by
  show some (luebeckConwayPolynomialOfCoeffs 3 [1, 1]) = some luebeckConwayPolynomial_3_1
  congr 1
  apply DensePoly.ext_coeff
  intro k
  rw [show DensePoly.coeff (luebeckConwayPolynomialOfCoeffs 3 [1, 1]) k =
        ([1, 1].toArray.map (fun m => ZMod64.ofNat 3 m)).getD k
          (Zero.zero : ZMod64 3) from DensePoly.coeff_ofCoeffs _ k]
  simp [List.toArray, Array.map, DensePoly.coeff, luebeckConwayPolynomial_3_1]
  match k with
  | 0 => rfl
  | 1 => rfl
  | _ + 2 => rfl


end Conway

end Hex
