/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPrimality.Cert
public import HexConway.FactorProofs.S0_3

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_823 : Hex.Nat.Prime 823 := by
  exact Hex.Nat.prime_of_bounded 823 28 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_827 : Hex.Nat.Prime 827 := by
  exact Hex.Nat.prime_of_bounded 827 28 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_839 : Hex.Nat.Prime 839 := by
  exact Hex.Nat.prime_of_bounded 839 28 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_857 : Hex.Nat.Prime 857 := by
  exact Hex.Nat.prime_of_bounded 857 29 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_877 : Hex.Nat.Prime 877 := by
  exact Hex.Nat.prime_of_bounded 877 29 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_883 : Hex.Nat.Prime 883 := by
  exact Hex.Nat.prime_of_bounded 883 29 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_911 : Hex.Nat.Prime 911 := by
  exact Hex.Nat.prime_of_bounded 911 30 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_919 : Hex.Nat.Prime 919 := by
  exact Hex.Nat.prime_of_bounded 919 30 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_941 : Hex.Nat.Prime 941 := by
  exact Hex.Nat.prime_of_bounded 941 30 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_991 : Hex.Nat.Prime 991 := by
  exact Hex.Nat.prime_of_bounded 991 31 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1061 : Hex.Nat.Prime 1061 := by
  exact Hex.Nat.prime_of_bounded 1061 32 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1063 : Hex.Nat.Prime 1063 := by
  exact Hex.Nat.prime_of_bounded 1063 32 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1087 : Hex.Nat.Prime 1087 := by
  exact Hex.Nat.prime_of_bounded 1087 32 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1093 : Hex.Nat.Prime 1093 := by
  exact Hex.Nat.prime_of_bounded 1093 33 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1201 : Hex.Nat.Prime 1201 := by
  exact Hex.Nat.prime_of_bounded 1201 34 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1277 : Hex.Nat.Prime 1277 := by
  exact Hex.Nat.prime_of_bounded 1277 35 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1321 : Hex.Nat.Prime 1321 := by
  exact Hex.Nat.prime_of_bounded 1321 36 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1327 : Hex.Nat.Prime 1327 := by
  exact Hex.Nat.prime_of_bounded 1327 36 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1423 : Hex.Nat.Prime 1423 := by
  exact Hex.Nat.prime_of_bounded 1423 37 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1471 : Hex.Nat.Prime 1471 := by
  exact Hex.Nat.prime_of_bounded 1471 38 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1613 : Hex.Nat.Prime 1613 := by
  exact Hex.Nat.prime_of_bounded 1613 40 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1693 : Hex.Nat.Prime 1693 := by
  exact Hex.Nat.prime_of_bounded 1693 41 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1699 : Hex.Nat.Prime 1699 := by
  exact Hex.Nat.prime_of_bounded 1699 41 (by decide) (by decide) (by decide)

/-- Primality of a multiplicative-order factor or a Pocklington child. -/
theorem factorPrime_1723 : Hex.Nat.Prime 1723 := by
  exact Hex.Nat.prime_of_bounded 1723 41 (by decide) (by decide) (by decide)


end Conway

end Hex
