/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Transport.S0_0
public import HexConway.Transport.S0_1
public import HexConway.Transport.S0_2
public import HexConway.Transport.S0_3
public import HexConway.Transport.S0_4
public import HexConway.Transport.S0_5
public import HexConway.Transport.S0_6
public import HexConway.Transport.S0_7
public import HexConway.Transport.S0_8
public import HexConway.Transport.S0_9
public import HexConway.Transport.S0_10
public import HexConway.Transport.S0_11
public import HexConway.Transport.S0_12
public import HexConway.Transport.S1_0
public import HexConway.Transport.S1_1
public import HexConway.Transport.S1_2
public import HexConway.Transport.S1_3
public import HexConway.Transport.S1_4
public import HexConway.Transport.S1_5
public import HexConway.Transport.S1_6
public import HexConway.Transport.S1_7
public import HexConway.Transport.S1_8
public import HexConway.Transport.S1_9
public import HexConway.Transport.S1_10
public import HexConway.Transport.S1_11
public import HexConway.Transport.S1_12
public import HexConway.Transport.S2_0
public import HexConway.Transport.S2_1
public import HexConway.Transport.S2_2
public import HexConway.Transport.S2_3
public import HexConway.Transport.S2_4
public import HexConway.Transport.S2_5
public import HexConway.Transport.S2_6
public import HexConway.Transport.S2_7
public import HexConway.Transport.S2_8
public import HexConway.Transport.S2_9
public import HexConway.Transport.S2_10
public import HexConway.Transport.S2_11
public import HexConway.Transport.S2_12
public import HexConway.Transport.S3_0
public import HexConway.Transport.S3_1
public import HexConway.Transport.S3_2
public import HexConway.Transport.S3_3
public import HexConway.Transport.S3_4
public import HexConway.Transport.S3_5
public import HexConway.Transport.S3_6
public import HexConway.Transport.S3_7
public import HexConway.Transport.S3_8
public import HexConway.Transport.S3_9
public import HexConway.Transport.S3_10
public import HexConway.Transport.S3_11
public import HexConway.Transport.S3_12

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- Every successful lookup carries irreducible certification. -/
@[grind →] theorem luebeckConwayPolynomial?_irreducible
    {p n : Nat} [ZMod64.Bounds p] {f : FpPoly p}
    (h : luebeckConwayPolynomial? p n = some f) : FpPoly.Irreducible f := by
  unfold luebeckConwayPolynomial? at h
  rw [Option.map_eq_some_iff] at h
  obtain ⟨coeffs, hcoeffs, hf⟩ := h
  subst hf
  unfold luebeckConwayCoeffs? at hcoeffs
  split at hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_2_1_irreducible
    · cases hcoeffs; exact ofCoeffs_2_2_irreducible
    · cases hcoeffs; exact ofCoeffs_2_3_irreducible
    · cases hcoeffs; exact ofCoeffs_2_4_irreducible
    · cases hcoeffs; exact ofCoeffs_2_5_irreducible
    · cases hcoeffs; exact ofCoeffs_2_6_irreducible
    · cases hcoeffs; exact ofCoeffs_2_7_irreducible
    · cases hcoeffs; exact ofCoeffs_2_8_irreducible
    · cases hcoeffs; exact ofCoeffs_2_9_irreducible
    · cases hcoeffs; exact ofCoeffs_2_10_irreducible
    · cases hcoeffs; exact ofCoeffs_2_11_irreducible
    · cases hcoeffs; exact ofCoeffs_2_12_irreducible
    · cases hcoeffs; exact ofCoeffs_2_13_irreducible
    · cases hcoeffs; exact ofCoeffs_2_14_irreducible
    · cases hcoeffs; exact ofCoeffs_2_15_irreducible
    · cases hcoeffs; exact ofCoeffs_2_16_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_3_1_irreducible
    · cases hcoeffs; exact ofCoeffs_3_2_irreducible
    · cases hcoeffs; exact ofCoeffs_3_3_irreducible
    · cases hcoeffs; exact ofCoeffs_3_4_irreducible
    · cases hcoeffs; exact ofCoeffs_3_5_irreducible
    · cases hcoeffs; exact ofCoeffs_3_6_irreducible
    · cases hcoeffs; exact ofCoeffs_3_7_irreducible
    · cases hcoeffs; exact ofCoeffs_3_8_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_5_1_irreducible
    · cases hcoeffs; exact ofCoeffs_5_2_irreducible
    · cases hcoeffs; exact ofCoeffs_5_3_irreducible
    · cases hcoeffs; exact ofCoeffs_5_4_irreducible
    · cases hcoeffs; exact ofCoeffs_5_5_irreducible
    · cases hcoeffs; exact ofCoeffs_5_6_irreducible
    · cases hcoeffs; exact ofCoeffs_5_7_irreducible
    · cases hcoeffs; exact ofCoeffs_5_8_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_7_1_irreducible
    · cases hcoeffs; exact ofCoeffs_7_2_irreducible
    · cases hcoeffs; exact ofCoeffs_7_3_irreducible
    · cases hcoeffs; exact ofCoeffs_7_4_irreducible
    · cases hcoeffs; exact ofCoeffs_7_5_irreducible
    · cases hcoeffs; exact ofCoeffs_7_6_irreducible
    · cases hcoeffs; exact ofCoeffs_7_7_irreducible
    · cases hcoeffs; exact ofCoeffs_7_8_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_11_1_irreducible
    · cases hcoeffs; exact ofCoeffs_11_2_irreducible
    · cases hcoeffs; exact ofCoeffs_11_3_irreducible
    · cases hcoeffs; exact ofCoeffs_11_4_irreducible
    · cases hcoeffs; exact ofCoeffs_11_5_irreducible
    · cases hcoeffs; exact ofCoeffs_11_6_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_13_1_irreducible
    · cases hcoeffs; exact ofCoeffs_13_2_irreducible
    · cases hcoeffs; exact ofCoeffs_13_3_irreducible
    · cases hcoeffs; exact ofCoeffs_13_4_irreducible
    · cases hcoeffs; exact ofCoeffs_13_5_irreducible
    · cases hcoeffs; exact ofCoeffs_13_6_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_17_1_irreducible
    · cases hcoeffs; exact ofCoeffs_17_2_irreducible
    · cases hcoeffs; exact ofCoeffs_17_3_irreducible
    · cases hcoeffs; exact ofCoeffs_17_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_19_1_irreducible
    · cases hcoeffs; exact ofCoeffs_19_2_irreducible
    · cases hcoeffs; exact ofCoeffs_19_3_irreducible
    · cases hcoeffs; exact ofCoeffs_19_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_23_1_irreducible
    · cases hcoeffs; exact ofCoeffs_23_2_irreducible
    · cases hcoeffs; exact ofCoeffs_23_3_irreducible
    · cases hcoeffs; exact ofCoeffs_23_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_29_1_irreducible
    · cases hcoeffs; exact ofCoeffs_29_2_irreducible
    · cases hcoeffs; exact ofCoeffs_29_3_irreducible
    · cases hcoeffs; exact ofCoeffs_29_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_31_1_irreducible
    · cases hcoeffs; exact ofCoeffs_31_2_irreducible
    · cases hcoeffs; exact ofCoeffs_31_3_irreducible
    · cases hcoeffs; exact ofCoeffs_31_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_37_1_irreducible
    · cases hcoeffs; exact ofCoeffs_37_2_irreducible
    · cases hcoeffs; exact ofCoeffs_37_3_irreducible
    · cases hcoeffs; exact ofCoeffs_37_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_41_1_irreducible
    · cases hcoeffs; exact ofCoeffs_41_2_irreducible
    · cases hcoeffs; exact ofCoeffs_41_3_irreducible
    · cases hcoeffs; exact ofCoeffs_41_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_43_1_irreducible
    · cases hcoeffs; exact ofCoeffs_43_2_irreducible
    · cases hcoeffs; exact ofCoeffs_43_3_irreducible
    · cases hcoeffs; exact ofCoeffs_43_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_47_1_irreducible
    · cases hcoeffs; exact ofCoeffs_47_2_irreducible
    · cases hcoeffs; exact ofCoeffs_47_3_irreducible
    · cases hcoeffs; exact ofCoeffs_47_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_53_1_irreducible
    · cases hcoeffs; exact ofCoeffs_53_2_irreducible
    · cases hcoeffs; exact ofCoeffs_53_3_irreducible
    · cases hcoeffs; exact ofCoeffs_53_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_59_1_irreducible
    · cases hcoeffs; exact ofCoeffs_59_2_irreducible
    · cases hcoeffs; exact ofCoeffs_59_3_irreducible
    · cases hcoeffs; exact ofCoeffs_59_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_61_1_irreducible
    · cases hcoeffs; exact ofCoeffs_61_2_irreducible
    · cases hcoeffs; exact ofCoeffs_61_3_irreducible
    · cases hcoeffs; exact ofCoeffs_61_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_67_1_irreducible
    · cases hcoeffs; exact ofCoeffs_67_2_irreducible
    · cases hcoeffs; exact ofCoeffs_67_3_irreducible
    · cases hcoeffs; exact ofCoeffs_67_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_71_1_irreducible
    · cases hcoeffs; exact ofCoeffs_71_2_irreducible
    · cases hcoeffs; exact ofCoeffs_71_3_irreducible
    · cases hcoeffs; exact ofCoeffs_71_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_73_1_irreducible
    · cases hcoeffs; exact ofCoeffs_73_2_irreducible
    · cases hcoeffs; exact ofCoeffs_73_3_irreducible
    · cases hcoeffs; exact ofCoeffs_73_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_79_1_irreducible
    · cases hcoeffs; exact ofCoeffs_79_2_irreducible
    · cases hcoeffs; exact ofCoeffs_79_3_irreducible
    · cases hcoeffs; exact ofCoeffs_79_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_83_1_irreducible
    · cases hcoeffs; exact ofCoeffs_83_2_irreducible
    · cases hcoeffs; exact ofCoeffs_83_3_irreducible
    · cases hcoeffs; exact ofCoeffs_83_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_89_1_irreducible
    · cases hcoeffs; exact ofCoeffs_89_2_irreducible
    · cases hcoeffs; exact ofCoeffs_89_3_irreducible
    · cases hcoeffs; exact ofCoeffs_89_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_97_1_irreducible
    · cases hcoeffs; exact ofCoeffs_97_2_irreducible
    · cases hcoeffs; exact ofCoeffs_97_3_irreducible
    · cases hcoeffs; exact ofCoeffs_97_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_101_1_irreducible
    · cases hcoeffs; exact ofCoeffs_101_2_irreducible
    · cases hcoeffs; exact ofCoeffs_101_3_irreducible
    · cases hcoeffs; exact ofCoeffs_101_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_103_1_irreducible
    · cases hcoeffs; exact ofCoeffs_103_2_irreducible
    · cases hcoeffs; exact ofCoeffs_103_3_irreducible
    · cases hcoeffs; exact ofCoeffs_103_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_107_1_irreducible
    · cases hcoeffs; exact ofCoeffs_107_2_irreducible
    · cases hcoeffs; exact ofCoeffs_107_3_irreducible
    · cases hcoeffs; exact ofCoeffs_107_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_109_1_irreducible
    · cases hcoeffs; exact ofCoeffs_109_2_irreducible
    · cases hcoeffs; exact ofCoeffs_109_3_irreducible
    · cases hcoeffs; exact ofCoeffs_109_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_113_1_irreducible
    · cases hcoeffs; exact ofCoeffs_113_2_irreducible
    · cases hcoeffs; exact ofCoeffs_113_3_irreducible
    · cases hcoeffs; exact ofCoeffs_113_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_127_1_irreducible
    · cases hcoeffs; exact ofCoeffs_127_2_irreducible
    · cases hcoeffs; exact ofCoeffs_127_3_irreducible
    · cases hcoeffs; exact ofCoeffs_127_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_131_1_irreducible
    · cases hcoeffs; exact ofCoeffs_131_2_irreducible
    · cases hcoeffs; exact ofCoeffs_131_3_irreducible
    · cases hcoeffs; exact ofCoeffs_131_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_137_1_irreducible
    · cases hcoeffs; exact ofCoeffs_137_2_irreducible
    · cases hcoeffs; exact ofCoeffs_137_3_irreducible
    · cases hcoeffs; exact ofCoeffs_137_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_139_1_irreducible
    · cases hcoeffs; exact ofCoeffs_139_2_irreducible
    · cases hcoeffs; exact ofCoeffs_139_3_irreducible
    · cases hcoeffs; exact ofCoeffs_139_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_149_1_irreducible
    · cases hcoeffs; exact ofCoeffs_149_2_irreducible
    · cases hcoeffs; exact ofCoeffs_149_3_irreducible
    · cases hcoeffs; exact ofCoeffs_149_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_151_1_irreducible
    · cases hcoeffs; exact ofCoeffs_151_2_irreducible
    · cases hcoeffs; exact ofCoeffs_151_3_irreducible
    · cases hcoeffs; exact ofCoeffs_151_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_157_1_irreducible
    · cases hcoeffs; exact ofCoeffs_157_2_irreducible
    · cases hcoeffs; exact ofCoeffs_157_3_irreducible
    · cases hcoeffs; exact ofCoeffs_157_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_163_1_irreducible
    · cases hcoeffs; exact ofCoeffs_163_2_irreducible
    · cases hcoeffs; exact ofCoeffs_163_3_irreducible
    · cases hcoeffs; exact ofCoeffs_163_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_167_1_irreducible
    · cases hcoeffs; exact ofCoeffs_167_2_irreducible
    · cases hcoeffs; exact ofCoeffs_167_3_irreducible
    · cases hcoeffs; exact ofCoeffs_167_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_173_1_irreducible
    · cases hcoeffs; exact ofCoeffs_173_2_irreducible
    · cases hcoeffs; exact ofCoeffs_173_3_irreducible
    · cases hcoeffs; exact ofCoeffs_173_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_179_1_irreducible
    · cases hcoeffs; exact ofCoeffs_179_2_irreducible
    · cases hcoeffs; exact ofCoeffs_179_3_irreducible
    · cases hcoeffs; exact ofCoeffs_179_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_181_1_irreducible
    · cases hcoeffs; exact ofCoeffs_181_2_irreducible
    · cases hcoeffs; exact ofCoeffs_181_3_irreducible
    · cases hcoeffs; exact ofCoeffs_181_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_191_1_irreducible
    · cases hcoeffs; exact ofCoeffs_191_2_irreducible
    · cases hcoeffs; exact ofCoeffs_191_3_irreducible
    · cases hcoeffs; exact ofCoeffs_191_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_193_1_irreducible
    · cases hcoeffs; exact ofCoeffs_193_2_irreducible
    · cases hcoeffs; exact ofCoeffs_193_3_irreducible
    · cases hcoeffs; exact ofCoeffs_193_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_197_1_irreducible
    · cases hcoeffs; exact ofCoeffs_197_2_irreducible
    · cases hcoeffs; exact ofCoeffs_197_3_irreducible
    · cases hcoeffs; exact ofCoeffs_197_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_199_1_irreducible
    · cases hcoeffs; exact ofCoeffs_199_2_irreducible
    · cases hcoeffs; exact ofCoeffs_199_3_irreducible
    · cases hcoeffs; exact ofCoeffs_199_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_211_1_irreducible
    · cases hcoeffs; exact ofCoeffs_211_2_irreducible
    · cases hcoeffs; exact ofCoeffs_211_3_irreducible
    · cases hcoeffs; exact ofCoeffs_211_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_223_1_irreducible
    · cases hcoeffs; exact ofCoeffs_223_2_irreducible
    · cases hcoeffs; exact ofCoeffs_223_3_irreducible
    · cases hcoeffs; exact ofCoeffs_223_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_227_1_irreducible
    · cases hcoeffs; exact ofCoeffs_227_2_irreducible
    · cases hcoeffs; exact ofCoeffs_227_3_irreducible
    · cases hcoeffs; exact ofCoeffs_227_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_229_1_irreducible
    · cases hcoeffs; exact ofCoeffs_229_2_irreducible
    · cases hcoeffs; exact ofCoeffs_229_3_irreducible
    · cases hcoeffs; exact ofCoeffs_229_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_233_1_irreducible
    · cases hcoeffs; exact ofCoeffs_233_2_irreducible
    · cases hcoeffs; exact ofCoeffs_233_3_irreducible
    · cases hcoeffs; exact ofCoeffs_233_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_239_1_irreducible
    · cases hcoeffs; exact ofCoeffs_239_2_irreducible
    · cases hcoeffs; exact ofCoeffs_239_3_irreducible
    · cases hcoeffs; exact ofCoeffs_239_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_241_1_irreducible
    · cases hcoeffs; exact ofCoeffs_241_2_irreducible
    · cases hcoeffs; exact ofCoeffs_241_3_irreducible
    · cases hcoeffs; exact ofCoeffs_241_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_251_1_irreducible
    · cases hcoeffs; exact ofCoeffs_251_2_irreducible
    · cases hcoeffs; exact ofCoeffs_251_3_irreducible
    · cases hcoeffs; exact ofCoeffs_251_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_257_1_irreducible
    · cases hcoeffs; exact ofCoeffs_257_2_irreducible
    · cases hcoeffs; exact ofCoeffs_257_3_irreducible
    · cases hcoeffs; exact ofCoeffs_257_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_263_1_irreducible
    · cases hcoeffs; exact ofCoeffs_263_2_irreducible
    · cases hcoeffs; exact ofCoeffs_263_3_irreducible
    · cases hcoeffs; exact ofCoeffs_263_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_269_1_irreducible
    · cases hcoeffs; exact ofCoeffs_269_2_irreducible
    · cases hcoeffs; exact ofCoeffs_269_3_irreducible
    · cases hcoeffs; exact ofCoeffs_269_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_271_1_irreducible
    · cases hcoeffs; exact ofCoeffs_271_2_irreducible
    · cases hcoeffs; exact ofCoeffs_271_3_irreducible
    · cases hcoeffs; exact ofCoeffs_271_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_277_1_irreducible
    · cases hcoeffs; exact ofCoeffs_277_2_irreducible
    · cases hcoeffs; exact ofCoeffs_277_3_irreducible
    · cases hcoeffs; exact ofCoeffs_277_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_281_1_irreducible
    · cases hcoeffs; exact ofCoeffs_281_2_irreducible
    · cases hcoeffs; exact ofCoeffs_281_3_irreducible
    · cases hcoeffs; exact ofCoeffs_281_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_283_1_irreducible
    · cases hcoeffs; exact ofCoeffs_283_2_irreducible
    · cases hcoeffs; exact ofCoeffs_283_3_irreducible
    · cases hcoeffs; exact ofCoeffs_283_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_293_1_irreducible
    · cases hcoeffs; exact ofCoeffs_293_2_irreducible
    · cases hcoeffs; exact ofCoeffs_293_3_irreducible
    · cases hcoeffs; exact ofCoeffs_293_4_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_307_1_irreducible
    · cases hcoeffs; exact ofCoeffs_307_2_irreducible
    · cases hcoeffs; exact ofCoeffs_307_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_311_1_irreducible
    · cases hcoeffs; exact ofCoeffs_311_2_irreducible
    · cases hcoeffs; exact ofCoeffs_311_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_313_1_irreducible
    · cases hcoeffs; exact ofCoeffs_313_2_irreducible
    · cases hcoeffs; exact ofCoeffs_313_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_317_1_irreducible
    · cases hcoeffs; exact ofCoeffs_317_2_irreducible
    · cases hcoeffs; exact ofCoeffs_317_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_331_1_irreducible
    · cases hcoeffs; exact ofCoeffs_331_2_irreducible
    · cases hcoeffs; exact ofCoeffs_331_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_337_1_irreducible
    · cases hcoeffs; exact ofCoeffs_337_2_irreducible
    · cases hcoeffs; exact ofCoeffs_337_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_347_1_irreducible
    · cases hcoeffs; exact ofCoeffs_347_2_irreducible
    · cases hcoeffs; exact ofCoeffs_347_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_349_1_irreducible
    · cases hcoeffs; exact ofCoeffs_349_2_irreducible
    · cases hcoeffs; exact ofCoeffs_349_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_353_1_irreducible
    · cases hcoeffs; exact ofCoeffs_353_2_irreducible
    · cases hcoeffs; exact ofCoeffs_353_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_359_1_irreducible
    · cases hcoeffs; exact ofCoeffs_359_2_irreducible
    · cases hcoeffs; exact ofCoeffs_359_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_367_1_irreducible
    · cases hcoeffs; exact ofCoeffs_367_2_irreducible
    · cases hcoeffs; exact ofCoeffs_367_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_373_1_irreducible
    · cases hcoeffs; exact ofCoeffs_373_2_irreducible
    · cases hcoeffs; exact ofCoeffs_373_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_379_1_irreducible
    · cases hcoeffs; exact ofCoeffs_379_2_irreducible
    · cases hcoeffs; exact ofCoeffs_379_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_383_1_irreducible
    · cases hcoeffs; exact ofCoeffs_383_2_irreducible
    · cases hcoeffs; exact ofCoeffs_383_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_389_1_irreducible
    · cases hcoeffs; exact ofCoeffs_389_2_irreducible
    · cases hcoeffs; exact ofCoeffs_389_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_397_1_irreducible
    · cases hcoeffs; exact ofCoeffs_397_2_irreducible
    · cases hcoeffs; exact ofCoeffs_397_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_401_1_irreducible
    · cases hcoeffs; exact ofCoeffs_401_2_irreducible
    · cases hcoeffs; exact ofCoeffs_401_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_409_1_irreducible
    · cases hcoeffs; exact ofCoeffs_409_2_irreducible
    · cases hcoeffs; exact ofCoeffs_409_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_419_1_irreducible
    · cases hcoeffs; exact ofCoeffs_419_2_irreducible
    · cases hcoeffs; exact ofCoeffs_419_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_421_1_irreducible
    · cases hcoeffs; exact ofCoeffs_421_2_irreducible
    · cases hcoeffs; exact ofCoeffs_421_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_431_1_irreducible
    · cases hcoeffs; exact ofCoeffs_431_2_irreducible
    · cases hcoeffs; exact ofCoeffs_431_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_433_1_irreducible
    · cases hcoeffs; exact ofCoeffs_433_2_irreducible
    · cases hcoeffs; exact ofCoeffs_433_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_439_1_irreducible
    · cases hcoeffs; exact ofCoeffs_439_2_irreducible
    · cases hcoeffs; exact ofCoeffs_439_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_443_1_irreducible
    · cases hcoeffs; exact ofCoeffs_443_2_irreducible
    · cases hcoeffs; exact ofCoeffs_443_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_449_1_irreducible
    · cases hcoeffs; exact ofCoeffs_449_2_irreducible
    · cases hcoeffs; exact ofCoeffs_449_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_457_1_irreducible
    · cases hcoeffs; exact ofCoeffs_457_2_irreducible
    · cases hcoeffs; exact ofCoeffs_457_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_461_1_irreducible
    · cases hcoeffs; exact ofCoeffs_461_2_irreducible
    · cases hcoeffs; exact ofCoeffs_461_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_463_1_irreducible
    · cases hcoeffs; exact ofCoeffs_463_2_irreducible
    · cases hcoeffs; exact ofCoeffs_463_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_467_1_irreducible
    · cases hcoeffs; exact ofCoeffs_467_2_irreducible
    · cases hcoeffs; exact ofCoeffs_467_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_479_1_irreducible
    · cases hcoeffs; exact ofCoeffs_479_2_irreducible
    · cases hcoeffs; exact ofCoeffs_479_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_487_1_irreducible
    · cases hcoeffs; exact ofCoeffs_487_2_irreducible
    · cases hcoeffs; exact ofCoeffs_487_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_491_1_irreducible
    · cases hcoeffs; exact ofCoeffs_491_2_irreducible
    · cases hcoeffs; exact ofCoeffs_491_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_499_1_irreducible
    · cases hcoeffs; exact ofCoeffs_499_2_irreducible
    · cases hcoeffs; exact ofCoeffs_499_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_503_1_irreducible
    · cases hcoeffs; exact ofCoeffs_503_2_irreducible
    · cases hcoeffs; exact ofCoeffs_503_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_509_1_irreducible
    · cases hcoeffs; exact ofCoeffs_509_2_irreducible
    · cases hcoeffs; exact ofCoeffs_509_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_521_1_irreducible
    · cases hcoeffs; exact ofCoeffs_521_2_irreducible
    · cases hcoeffs; exact ofCoeffs_521_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_523_1_irreducible
    · cases hcoeffs; exact ofCoeffs_523_2_irreducible
    · cases hcoeffs; exact ofCoeffs_523_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_541_1_irreducible
    · cases hcoeffs; exact ofCoeffs_541_2_irreducible
    · cases hcoeffs; exact ofCoeffs_541_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_547_1_irreducible
    · cases hcoeffs; exact ofCoeffs_547_2_irreducible
    · cases hcoeffs; exact ofCoeffs_547_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_557_1_irreducible
    · cases hcoeffs; exact ofCoeffs_557_2_irreducible
    · cases hcoeffs; exact ofCoeffs_557_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_563_1_irreducible
    · cases hcoeffs; exact ofCoeffs_563_2_irreducible
    · cases hcoeffs; exact ofCoeffs_563_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_569_1_irreducible
    · cases hcoeffs; exact ofCoeffs_569_2_irreducible
    · cases hcoeffs; exact ofCoeffs_569_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_571_1_irreducible
    · cases hcoeffs; exact ofCoeffs_571_2_irreducible
    · cases hcoeffs; exact ofCoeffs_571_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_577_1_irreducible
    · cases hcoeffs; exact ofCoeffs_577_2_irreducible
    · cases hcoeffs; exact ofCoeffs_577_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_587_1_irreducible
    · cases hcoeffs; exact ofCoeffs_587_2_irreducible
    · cases hcoeffs; exact ofCoeffs_587_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_593_1_irreducible
    · cases hcoeffs; exact ofCoeffs_593_2_irreducible
    · cases hcoeffs; exact ofCoeffs_593_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_599_1_irreducible
    · cases hcoeffs; exact ofCoeffs_599_2_irreducible
    · cases hcoeffs; exact ofCoeffs_599_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_601_1_irreducible
    · cases hcoeffs; exact ofCoeffs_601_2_irreducible
    · cases hcoeffs; exact ofCoeffs_601_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_607_1_irreducible
    · cases hcoeffs; exact ofCoeffs_607_2_irreducible
    · cases hcoeffs; exact ofCoeffs_607_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_613_1_irreducible
    · cases hcoeffs; exact ofCoeffs_613_2_irreducible
    · cases hcoeffs; exact ofCoeffs_613_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_617_1_irreducible
    · cases hcoeffs; exact ofCoeffs_617_2_irreducible
    · cases hcoeffs; exact ofCoeffs_617_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_619_1_irreducible
    · cases hcoeffs; exact ofCoeffs_619_2_irreducible
    · cases hcoeffs; exact ofCoeffs_619_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_631_1_irreducible
    · cases hcoeffs; exact ofCoeffs_631_2_irreducible
    · cases hcoeffs; exact ofCoeffs_631_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_641_1_irreducible
    · cases hcoeffs; exact ofCoeffs_641_2_irreducible
    · cases hcoeffs; exact ofCoeffs_641_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_643_1_irreducible
    · cases hcoeffs; exact ofCoeffs_643_2_irreducible
    · cases hcoeffs; exact ofCoeffs_643_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_647_1_irreducible
    · cases hcoeffs; exact ofCoeffs_647_2_irreducible
    · cases hcoeffs; exact ofCoeffs_647_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_653_1_irreducible
    · cases hcoeffs; exact ofCoeffs_653_2_irreducible
    · cases hcoeffs; exact ofCoeffs_653_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_659_1_irreducible
    · cases hcoeffs; exact ofCoeffs_659_2_irreducible
    · cases hcoeffs; exact ofCoeffs_659_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_661_1_irreducible
    · cases hcoeffs; exact ofCoeffs_661_2_irreducible
    · cases hcoeffs; exact ofCoeffs_661_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_673_1_irreducible
    · cases hcoeffs; exact ofCoeffs_673_2_irreducible
    · cases hcoeffs; exact ofCoeffs_673_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_677_1_irreducible
    · cases hcoeffs; exact ofCoeffs_677_2_irreducible
    · cases hcoeffs; exact ofCoeffs_677_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_683_1_irreducible
    · cases hcoeffs; exact ofCoeffs_683_2_irreducible
    · cases hcoeffs; exact ofCoeffs_683_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_691_1_irreducible
    · cases hcoeffs; exact ofCoeffs_691_2_irreducible
    · cases hcoeffs; exact ofCoeffs_691_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_701_1_irreducible
    · cases hcoeffs; exact ofCoeffs_701_2_irreducible
    · cases hcoeffs; exact ofCoeffs_701_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_709_1_irreducible
    · cases hcoeffs; exact ofCoeffs_709_2_irreducible
    · cases hcoeffs; exact ofCoeffs_709_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_719_1_irreducible
    · cases hcoeffs; exact ofCoeffs_719_2_irreducible
    · cases hcoeffs; exact ofCoeffs_719_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_727_1_irreducible
    · cases hcoeffs; exact ofCoeffs_727_2_irreducible
    · cases hcoeffs; exact ofCoeffs_727_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_733_1_irreducible
    · cases hcoeffs; exact ofCoeffs_733_2_irreducible
    · cases hcoeffs; exact ofCoeffs_733_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_739_1_irreducible
    · cases hcoeffs; exact ofCoeffs_739_2_irreducible
    · cases hcoeffs; exact ofCoeffs_739_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_743_1_irreducible
    · cases hcoeffs; exact ofCoeffs_743_2_irreducible
    · cases hcoeffs; exact ofCoeffs_743_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_751_1_irreducible
    · cases hcoeffs; exact ofCoeffs_751_2_irreducible
    · cases hcoeffs; exact ofCoeffs_751_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_757_1_irreducible
    · cases hcoeffs; exact ofCoeffs_757_2_irreducible
    · cases hcoeffs; exact ofCoeffs_757_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_761_1_irreducible
    · cases hcoeffs; exact ofCoeffs_761_2_irreducible
    · cases hcoeffs; exact ofCoeffs_761_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_769_1_irreducible
    · cases hcoeffs; exact ofCoeffs_769_2_irreducible
    · cases hcoeffs; exact ofCoeffs_769_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_773_1_irreducible
    · cases hcoeffs; exact ofCoeffs_773_2_irreducible
    · cases hcoeffs; exact ofCoeffs_773_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_787_1_irreducible
    · cases hcoeffs; exact ofCoeffs_787_2_irreducible
    · cases hcoeffs; exact ofCoeffs_787_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_797_1_irreducible
    · cases hcoeffs; exact ofCoeffs_797_2_irreducible
    · cases hcoeffs; exact ofCoeffs_797_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_809_1_irreducible
    · cases hcoeffs; exact ofCoeffs_809_2_irreducible
    · cases hcoeffs; exact ofCoeffs_809_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_811_1_irreducible
    · cases hcoeffs; exact ofCoeffs_811_2_irreducible
    · cases hcoeffs; exact ofCoeffs_811_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_821_1_irreducible
    · cases hcoeffs; exact ofCoeffs_821_2_irreducible
    · cases hcoeffs; exact ofCoeffs_821_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_823_1_irreducible
    · cases hcoeffs; exact ofCoeffs_823_2_irreducible
    · cases hcoeffs; exact ofCoeffs_823_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_827_1_irreducible
    · cases hcoeffs; exact ofCoeffs_827_2_irreducible
    · cases hcoeffs; exact ofCoeffs_827_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_829_1_irreducible
    · cases hcoeffs; exact ofCoeffs_829_2_irreducible
    · cases hcoeffs; exact ofCoeffs_829_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_839_1_irreducible
    · cases hcoeffs; exact ofCoeffs_839_2_irreducible
    · cases hcoeffs; exact ofCoeffs_839_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_853_1_irreducible
    · cases hcoeffs; exact ofCoeffs_853_2_irreducible
    · cases hcoeffs; exact ofCoeffs_853_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_857_1_irreducible
    · cases hcoeffs; exact ofCoeffs_857_2_irreducible
    · cases hcoeffs; exact ofCoeffs_857_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_859_1_irreducible
    · cases hcoeffs; exact ofCoeffs_859_2_irreducible
    · cases hcoeffs; exact ofCoeffs_859_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_863_1_irreducible
    · cases hcoeffs; exact ofCoeffs_863_2_irreducible
    · cases hcoeffs; exact ofCoeffs_863_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_877_1_irreducible
    · cases hcoeffs; exact ofCoeffs_877_2_irreducible
    · cases hcoeffs; exact ofCoeffs_877_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_881_1_irreducible
    · cases hcoeffs; exact ofCoeffs_881_2_irreducible
    · cases hcoeffs; exact ofCoeffs_881_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_883_1_irreducible
    · cases hcoeffs; exact ofCoeffs_883_2_irreducible
    · cases hcoeffs; exact ofCoeffs_883_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_887_1_irreducible
    · cases hcoeffs; exact ofCoeffs_887_2_irreducible
    · cases hcoeffs; exact ofCoeffs_887_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_907_1_irreducible
    · cases hcoeffs; exact ofCoeffs_907_2_irreducible
    · cases hcoeffs; exact ofCoeffs_907_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_911_1_irreducible
    · cases hcoeffs; exact ofCoeffs_911_2_irreducible
    · cases hcoeffs; exact ofCoeffs_911_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_919_1_irreducible
    · cases hcoeffs; exact ofCoeffs_919_2_irreducible
    · cases hcoeffs; exact ofCoeffs_919_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_929_1_irreducible
    · cases hcoeffs; exact ofCoeffs_929_2_irreducible
    · cases hcoeffs; exact ofCoeffs_929_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_937_1_irreducible
    · cases hcoeffs; exact ofCoeffs_937_2_irreducible
    · cases hcoeffs; exact ofCoeffs_937_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_941_1_irreducible
    · cases hcoeffs; exact ofCoeffs_941_2_irreducible
    · cases hcoeffs; exact ofCoeffs_941_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_947_1_irreducible
    · cases hcoeffs; exact ofCoeffs_947_2_irreducible
    · cases hcoeffs; exact ofCoeffs_947_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_953_1_irreducible
    · cases hcoeffs; exact ofCoeffs_953_2_irreducible
    · cases hcoeffs; exact ofCoeffs_953_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_967_1_irreducible
    · cases hcoeffs; exact ofCoeffs_967_2_irreducible
    · cases hcoeffs; exact ofCoeffs_967_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_971_1_irreducible
    · cases hcoeffs; exact ofCoeffs_971_2_irreducible
    · cases hcoeffs; exact ofCoeffs_971_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_977_1_irreducible
    · cases hcoeffs; exact ofCoeffs_977_2_irreducible
    · cases hcoeffs; exact ofCoeffs_977_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_983_1_irreducible
    · cases hcoeffs; exact ofCoeffs_983_2_irreducible
    · cases hcoeffs; exact ofCoeffs_983_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_991_1_irreducible
    · cases hcoeffs; exact ofCoeffs_991_2_irreducible
    · cases hcoeffs; exact ofCoeffs_991_3_irreducible
    · cases hcoeffs
  · split at hcoeffs
    · cases hcoeffs; exact ofCoeffs_997_1_irreducible
    · cases hcoeffs; exact ofCoeffs_997_2_irreducible
    · cases hcoeffs; exact ofCoeffs_997_3_irreducible
    · cases hcoeffs
  · cases hcoeffs


end Conway

end Hex
