/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Certificates
public import HexConway.Transport.S0_2

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

theorem ofCoeffs_113_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 113 [110, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_113_1
  change luebeckConwayPolynomialOfCoeffs 113 [110, 1] = luebeckConwayPolynomial_113_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_113_1_irreducible

theorem ofCoeffs_113_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 113 [110, 8, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_113_3
  change luebeckConwayPolynomialOfCoeffs 113 [110, 8, 0, 1] = luebeckConwayPolynomial_113_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_113_3_irreducible

theorem ofCoeffs_127_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 127 [124, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_127_1
  change luebeckConwayPolynomialOfCoeffs 127 [124, 1] = luebeckConwayPolynomial_127_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_127_1_irreducible

theorem ofCoeffs_127_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 127 [124, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_127_3
  change luebeckConwayPolynomialOfCoeffs 127 [124, 3, 0, 1] = luebeckConwayPolynomial_127_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_127_3_irreducible

theorem ofCoeffs_131_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 131 [129, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_131_1
  change luebeckConwayPolynomialOfCoeffs 131 [129, 1] = luebeckConwayPolynomial_131_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_131_1_irreducible

theorem ofCoeffs_131_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 131 [129, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_131_3
  change luebeckConwayPolynomialOfCoeffs 131 [129, 3, 0, 1] = luebeckConwayPolynomial_131_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_131_3_irreducible

theorem ofCoeffs_137_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 137 [134, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_137_1
  change luebeckConwayPolynomialOfCoeffs 137 [134, 1] = luebeckConwayPolynomial_137_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_137_1_irreducible

theorem ofCoeffs_137_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 137 [134, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_137_3
  change luebeckConwayPolynomialOfCoeffs 137 [134, 6, 0, 1] = luebeckConwayPolynomial_137_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_137_3_irreducible

theorem ofCoeffs_139_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 139 [137, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_139_1
  change luebeckConwayPolynomialOfCoeffs 139 [137, 1] = luebeckConwayPolynomial_139_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_139_1_irreducible

theorem ofCoeffs_139_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 139 [137, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_139_3
  change luebeckConwayPolynomialOfCoeffs 139 [137, 6, 0, 1] = luebeckConwayPolynomial_139_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_139_3_irreducible

theorem ofCoeffs_149_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 149 [147, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_149_1
  change luebeckConwayPolynomialOfCoeffs 149 [147, 1] = luebeckConwayPolynomial_149_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_149_1_irreducible

theorem ofCoeffs_149_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 149 [147, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_149_3
  change luebeckConwayPolynomialOfCoeffs 149 [147, 3, 0, 1] = luebeckConwayPolynomial_149_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_149_3_irreducible

theorem ofCoeffs_151_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 151 [145, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_151_1
  change luebeckConwayPolynomialOfCoeffs 151 [145, 1] = luebeckConwayPolynomial_151_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_151_1_irreducible

theorem ofCoeffs_151_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 151 [145, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_151_3
  change luebeckConwayPolynomialOfCoeffs 151 [145, 1, 0, 1] = luebeckConwayPolynomial_151_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_151_3_irreducible

theorem ofCoeffs_157_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 157 [152, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_157_1
  change luebeckConwayPolynomialOfCoeffs 157 [152, 1] = luebeckConwayPolynomial_157_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_157_1_irreducible

theorem ofCoeffs_157_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 157 [152, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_157_3
  change luebeckConwayPolynomialOfCoeffs 157 [152, 1, 0, 1] = luebeckConwayPolynomial_157_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_157_3_irreducible

theorem ofCoeffs_163_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 163 [161, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_163_1
  change luebeckConwayPolynomialOfCoeffs 163 [161, 1] = luebeckConwayPolynomial_163_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_163_1_irreducible

theorem ofCoeffs_163_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 163 [161, 7, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_163_3
  change luebeckConwayPolynomialOfCoeffs 163 [161, 7, 0, 1] = luebeckConwayPolynomial_163_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_163_3_irreducible

theorem ofCoeffs_167_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 167 [162, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_167_1
  change luebeckConwayPolynomialOfCoeffs 167 [162, 1] = luebeckConwayPolynomial_167_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_167_1_irreducible

theorem ofCoeffs_167_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 167 [162, 7, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_167_3
  change luebeckConwayPolynomialOfCoeffs 167 [162, 7, 0, 1] = luebeckConwayPolynomial_167_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_167_3_irreducible

theorem ofCoeffs_173_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 173 [171, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_173_1
  change luebeckConwayPolynomialOfCoeffs 173 [171, 1] = luebeckConwayPolynomial_173_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_173_1_irreducible

theorem ofCoeffs_173_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 173 [171, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_173_3
  change luebeckConwayPolynomialOfCoeffs 173 [171, 2, 0, 1] = luebeckConwayPolynomial_173_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_173_3_irreducible

theorem ofCoeffs_179_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 179 [177, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_179_1
  change luebeckConwayPolynomialOfCoeffs 179 [177, 1] = luebeckConwayPolynomial_179_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_179_1_irreducible

theorem ofCoeffs_179_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 179 [177, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_179_3
  change luebeckConwayPolynomialOfCoeffs 179 [177, 4, 0, 1] = luebeckConwayPolynomial_179_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_179_3_irreducible


end Conway

end Hex
