/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Certificates
public import HexConway.Transport.S0_7

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

theorem ofCoeffs_523_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 523 [521, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_523_1
  change luebeckConwayPolynomialOfCoeffs 523 [521, 1] = luebeckConwayPolynomial_523_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_523_1_irreducible

theorem ofCoeffs_523_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 523 [521, 5, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_523_3
  change luebeckConwayPolynomialOfCoeffs 523 [521, 5, 0, 1] = luebeckConwayPolynomial_523_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_523_3_irreducible

theorem ofCoeffs_541_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 541 [2, 537, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_541_2
  change luebeckConwayPolynomialOfCoeffs 541 [2, 537, 1] = luebeckConwayPolynomial_541_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_541_2_irreducible

theorem ofCoeffs_547_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 547 [545, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_547_1
  change luebeckConwayPolynomialOfCoeffs 547 [545, 1] = luebeckConwayPolynomial_547_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_547_1_irreducible

theorem ofCoeffs_547_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 547 [545, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_547_3
  change luebeckConwayPolynomialOfCoeffs 547 [545, 4, 0, 1] = luebeckConwayPolynomial_547_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_547_3_irreducible

theorem ofCoeffs_557_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 557 [2, 553, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_557_2
  change luebeckConwayPolynomialOfCoeffs 557 [2, 553, 1] = luebeckConwayPolynomial_557_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_557_2_irreducible

theorem ofCoeffs_563_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 563 [561, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_563_1
  change luebeckConwayPolynomialOfCoeffs 563 [561, 1] = luebeckConwayPolynomial_563_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_563_1_irreducible

theorem ofCoeffs_563_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 563 [561, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_563_3
  change luebeckConwayPolynomialOfCoeffs 563 [561, 3, 0, 1] = luebeckConwayPolynomial_563_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_563_3_irreducible

theorem ofCoeffs_569_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 569 [3, 568, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_569_2
  change luebeckConwayPolynomialOfCoeffs 569 [3, 568, 1] = luebeckConwayPolynomial_569_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_569_2_irreducible

theorem ofCoeffs_571_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 571 [568, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_571_1
  change luebeckConwayPolynomialOfCoeffs 571 [568, 1] = luebeckConwayPolynomial_571_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_571_1_irreducible

theorem ofCoeffs_571_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 571 [568, 8, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_571_3
  change luebeckConwayPolynomialOfCoeffs 571 [568, 8, 0, 1] = luebeckConwayPolynomial_571_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_571_3_irreducible

theorem ofCoeffs_577_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 577 [5, 572, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_577_2
  change luebeckConwayPolynomialOfCoeffs 577 [5, 572, 1] = luebeckConwayPolynomial_577_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_577_2_irreducible

theorem ofCoeffs_587_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 587 [585, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_587_1
  change luebeckConwayPolynomialOfCoeffs 587 [585, 1] = luebeckConwayPolynomial_587_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_587_1_irreducible

theorem ofCoeffs_587_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 587 [585, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_587_3
  change luebeckConwayPolynomialOfCoeffs 587 [585, 3, 0, 1] = luebeckConwayPolynomial_587_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_587_3_irreducible

theorem ofCoeffs_593_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 593 [3, 592, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_593_2
  change luebeckConwayPolynomialOfCoeffs 593 [3, 592, 1] = luebeckConwayPolynomial_593_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_593_2_irreducible

theorem ofCoeffs_599_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 599 [592, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_599_1
  change luebeckConwayPolynomialOfCoeffs 599 [592, 1] = luebeckConwayPolynomial_599_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_599_1_irreducible

theorem ofCoeffs_599_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 599 [592, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_599_3
  change luebeckConwayPolynomialOfCoeffs 599 [592, 2, 0, 1] = luebeckConwayPolynomial_599_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_599_3_irreducible

theorem ofCoeffs_601_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 601 [7, 598, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_601_2
  change luebeckConwayPolynomialOfCoeffs 601 [7, 598, 1] = luebeckConwayPolynomial_601_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_601_2_irreducible

theorem ofCoeffs_607_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 607 [604, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_607_1
  change luebeckConwayPolynomialOfCoeffs 607 [604, 1] = luebeckConwayPolynomial_607_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_607_1_irreducible

theorem ofCoeffs_607_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 607 [604, 5, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_607_3
  change luebeckConwayPolynomialOfCoeffs 607 [604, 5, 0, 1] = luebeckConwayPolynomial_607_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_607_3_irreducible

theorem ofCoeffs_613_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 613 [2, 609, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_613_2
  change luebeckConwayPolynomialOfCoeffs 613 [2, 609, 1] = luebeckConwayPolynomial_613_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_613_2_irreducible

theorem ofCoeffs_617_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 617 [614, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_617_1
  change luebeckConwayPolynomialOfCoeffs 617 [614, 1] = luebeckConwayPolynomial_617_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_617_1_irreducible

theorem ofCoeffs_617_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 617 [614, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_617_3
  change luebeckConwayPolynomialOfCoeffs 617 [614, 3, 0, 1] = luebeckConwayPolynomial_617_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_617_3_irreducible

theorem ofCoeffs_619_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 619 [2, 618, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_619_2
  change luebeckConwayPolynomialOfCoeffs 619 [2, 618, 1] = luebeckConwayPolynomial_619_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_619_2_irreducible


end Conway

end Hex
