/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Certificates
public import HexConway.Transport.S1_4

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

theorem ofCoeffs_251_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 251 [245, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_251_1
  change luebeckConwayPolynomialOfCoeffs 251 [245, 1] = luebeckConwayPolynomial_251_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_251_1_monic

theorem ofCoeffs_251_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 251 [245, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_251_3
  change luebeckConwayPolynomialOfCoeffs 251 [245, 3, 0, 1] = luebeckConwayPolynomial_251_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_251_3_monic

theorem ofCoeffs_257_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 257 [254, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_257_1
  change luebeckConwayPolynomialOfCoeffs 257 [254, 1] = luebeckConwayPolynomial_257_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_257_1_monic

theorem ofCoeffs_257_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 257 [254, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_257_3
  change luebeckConwayPolynomialOfCoeffs 257 [254, 6, 0, 1] = luebeckConwayPolynomial_257_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_257_3_monic

theorem ofCoeffs_263_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 263 [258, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_263_1
  change luebeckConwayPolynomialOfCoeffs 263 [258, 1] = luebeckConwayPolynomial_263_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_263_1_monic

theorem ofCoeffs_263_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 263 [258, 14, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_263_3
  change luebeckConwayPolynomialOfCoeffs 263 [258, 14, 0, 1] = luebeckConwayPolynomial_263_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_263_3_monic

theorem ofCoeffs_269_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 269 [267, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_269_1
  change luebeckConwayPolynomialOfCoeffs 269 [267, 1] = luebeckConwayPolynomial_269_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_269_1_monic

theorem ofCoeffs_269_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 269 [267, 9, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_269_3
  change luebeckConwayPolynomialOfCoeffs 269 [267, 9, 0, 1] = luebeckConwayPolynomial_269_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_269_3_monic

theorem ofCoeffs_271_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 271 [265, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_271_1
  change luebeckConwayPolynomialOfCoeffs 271 [265, 1] = luebeckConwayPolynomial_271_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_271_1_monic

theorem ofCoeffs_271_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 271 [265, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_271_3
  change luebeckConwayPolynomialOfCoeffs 271 [265, 2, 0, 1] = luebeckConwayPolynomial_271_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_271_3_monic

theorem ofCoeffs_277_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 277 [272, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_277_1
  change luebeckConwayPolynomialOfCoeffs 277 [272, 1] = luebeckConwayPolynomial_277_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_277_1_monic

theorem ofCoeffs_277_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 277 [272, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_277_3
  change luebeckConwayPolynomialOfCoeffs 277 [272, 3, 0, 1] = luebeckConwayPolynomial_277_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_277_3_monic

theorem ofCoeffs_281_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 281 [278, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_281_1
  change luebeckConwayPolynomialOfCoeffs 281 [278, 1] = luebeckConwayPolynomial_281_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_281_1_monic

theorem ofCoeffs_281_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 281 [278, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_281_3
  change luebeckConwayPolynomialOfCoeffs 281 [278, 1, 0, 1] = luebeckConwayPolynomial_281_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_281_3_monic

theorem ofCoeffs_283_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 283 [280, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_283_1
  change luebeckConwayPolynomialOfCoeffs 283 [280, 1] = luebeckConwayPolynomial_283_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_283_1_monic

theorem ofCoeffs_283_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 283 [280, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_283_3
  change luebeckConwayPolynomialOfCoeffs 283 [280, 3, 0, 1] = luebeckConwayPolynomial_283_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_283_3_monic

theorem ofCoeffs_293_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 293 [291, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_293_1
  change luebeckConwayPolynomialOfCoeffs 293 [291, 1] = luebeckConwayPolynomial_293_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_293_1_monic

theorem ofCoeffs_293_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 293 [291, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_293_3
  change luebeckConwayPolynomialOfCoeffs 293 [291, 2, 0, 1] = luebeckConwayPolynomial_293_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_293_3_monic

theorem ofCoeffs_307_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 307 [302, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_307_1
  change luebeckConwayPolynomialOfCoeffs 307 [302, 1] = luebeckConwayPolynomial_307_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_307_1_monic

theorem ofCoeffs_307_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 307 [302, 7, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_307_3
  change luebeckConwayPolynomialOfCoeffs 307 [302, 7, 0, 1] = luebeckConwayPolynomial_307_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_307_3_monic

theorem ofCoeffs_311_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 311 [17, 310, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_311_2
  change luebeckConwayPolynomialOfCoeffs 311 [17, 310, 1] = luebeckConwayPolynomial_311_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_311_2_monic

theorem ofCoeffs_313_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 313 [303, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_313_1
  change luebeckConwayPolynomialOfCoeffs 313 [303, 1] = luebeckConwayPolynomial_313_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_313_1_monic

theorem ofCoeffs_313_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 313 [303, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_313_3
  change luebeckConwayPolynomialOfCoeffs 313 [303, 2, 0, 1] = luebeckConwayPolynomial_313_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_313_3_monic

theorem ofCoeffs_317_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 317 [2, 313, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_317_2
  change luebeckConwayPolynomialOfCoeffs 317 [2, 313, 1] = luebeckConwayPolynomial_317_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_317_2_monic


end Conway

end Hex
