/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Certificates
public import HexConway.Transport.S1_8

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

theorem ofCoeffs_631_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 631 [628, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_631_1
  change luebeckConwayPolynomialOfCoeffs 631 [628, 1] = luebeckConwayPolynomial_631_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_631_1_monic

theorem ofCoeffs_631_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 631 [628, 5, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_631_3
  change luebeckConwayPolynomialOfCoeffs 631 [628, 5, 0, 1] = luebeckConwayPolynomial_631_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_631_3_monic

theorem ofCoeffs_641_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 641 [3, 635, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_641_2
  change luebeckConwayPolynomialOfCoeffs 641 [3, 635, 1] = luebeckConwayPolynomial_641_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_641_2_monic

theorem ofCoeffs_643_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 643 [632, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_643_1
  change luebeckConwayPolynomialOfCoeffs 643 [632, 1] = luebeckConwayPolynomial_643_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_643_1_monic

theorem ofCoeffs_643_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 643 [632, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_643_3
  change luebeckConwayPolynomialOfCoeffs 643 [632, 1, 0, 1] = luebeckConwayPolynomial_643_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_643_3_monic

theorem ofCoeffs_647_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 647 [5, 645, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_647_2
  change luebeckConwayPolynomialOfCoeffs 647 [5, 645, 1] = luebeckConwayPolynomial_647_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_647_2_monic

theorem ofCoeffs_653_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 653 [651, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_653_1
  change luebeckConwayPolynomialOfCoeffs 653 [651, 1] = luebeckConwayPolynomial_653_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_653_1_monic

theorem ofCoeffs_653_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 653 [651, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_653_3
  change luebeckConwayPolynomialOfCoeffs 653 [651, 3, 0, 1] = luebeckConwayPolynomial_653_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_653_3_monic

theorem ofCoeffs_659_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 659 [2, 655, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_659_2
  change luebeckConwayPolynomialOfCoeffs 659 [2, 655, 1] = luebeckConwayPolynomial_659_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_659_2_monic

theorem ofCoeffs_661_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 661 [659, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_661_1
  change luebeckConwayPolynomialOfCoeffs 661 [659, 1] = luebeckConwayPolynomial_661_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_661_1_monic

theorem ofCoeffs_661_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 661 [659, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_661_3
  change luebeckConwayPolynomialOfCoeffs 661 [659, 4, 0, 1] = luebeckConwayPolynomial_661_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_661_3_monic

theorem ofCoeffs_673_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 673 [5, 672, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_673_2
  change luebeckConwayPolynomialOfCoeffs 673 [5, 672, 1] = luebeckConwayPolynomial_673_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_673_2_monic

theorem ofCoeffs_677_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 677 [675, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_677_1
  change luebeckConwayPolynomialOfCoeffs 677 [675, 1] = luebeckConwayPolynomial_677_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_677_1_monic

theorem ofCoeffs_677_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 677 [675, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_677_3
  change luebeckConwayPolynomialOfCoeffs 677 [675, 2, 0, 1] = luebeckConwayPolynomial_677_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_677_3_monic

theorem ofCoeffs_683_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 683 [5, 682, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_683_2
  change luebeckConwayPolynomialOfCoeffs 683 [5, 682, 1] = luebeckConwayPolynomial_683_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_683_2_monic

theorem ofCoeffs_691_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 691 [688, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_691_1
  change luebeckConwayPolynomialOfCoeffs 691 [688, 1] = luebeckConwayPolynomial_691_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_691_1_monic

theorem ofCoeffs_691_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 691 [688, 14, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_691_3
  change luebeckConwayPolynomialOfCoeffs 691 [688, 14, 0, 1] = luebeckConwayPolynomial_691_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_691_3_monic

theorem ofCoeffs_701_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 701 [2, 697, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_701_2
  change luebeckConwayPolynomialOfCoeffs 701 [2, 697, 1] = luebeckConwayPolynomial_701_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_701_2_monic

theorem ofCoeffs_709_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 709 [707, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_709_1
  change luebeckConwayPolynomialOfCoeffs 709 [707, 1] = luebeckConwayPolynomial_709_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_709_1_monic

theorem ofCoeffs_709_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 709 [707, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_709_3
  change luebeckConwayPolynomialOfCoeffs 709 [707, 2, 0, 1] = luebeckConwayPolynomial_709_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_709_3_monic

theorem ofCoeffs_719_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 719 [11, 715, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_719_2
  change luebeckConwayPolynomialOfCoeffs 719 [11, 715, 1] = luebeckConwayPolynomial_719_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_719_2_monic

theorem ofCoeffs_727_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 727 [722, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_727_1
  change luebeckConwayPolynomialOfCoeffs 727 [722, 1] = luebeckConwayPolynomial_727_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_727_1_monic

theorem ofCoeffs_727_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 727 [722, 7, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_727_3
  change luebeckConwayPolynomialOfCoeffs 727 [722, 7, 0, 1] = luebeckConwayPolynomial_727_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_727_3_monic

theorem ofCoeffs_733_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 733 [6, 732, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_733_2
  change luebeckConwayPolynomialOfCoeffs 733 [6, 732, 1] = luebeckConwayPolynomial_733_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_733_2_monic


end Conway

end Hex
