/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Certificates
public import HexConway.Transport.S2_10

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

theorem ofCoeffs_853_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 853 [2, 852, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_853_2
  change luebeckConwayPolynomialOfCoeffs 853 [2, 852, 1] = luebeckConwayPolynomial_853_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_853_2_irreducible

theorem ofCoeffs_857_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 857 [854, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_857_1
  change luebeckConwayPolynomialOfCoeffs 857 [854, 1] = luebeckConwayPolynomial_857_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_857_1_irreducible

theorem ofCoeffs_857_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 857 [854, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_857_3
  change luebeckConwayPolynomialOfCoeffs 857 [854, 4, 0, 1] = luebeckConwayPolynomial_857_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_857_3_irreducible

theorem ofCoeffs_859_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 859 [2, 858, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_859_2
  change luebeckConwayPolynomialOfCoeffs 859 [2, 858, 1] = luebeckConwayPolynomial_859_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_859_2_irreducible

theorem ofCoeffs_863_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 863 [858, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_863_1
  change luebeckConwayPolynomialOfCoeffs 863 [858, 1] = luebeckConwayPolynomial_863_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_863_1_irreducible

theorem ofCoeffs_863_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 863 [858, 5, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_863_3
  change luebeckConwayPolynomialOfCoeffs 863 [858, 5, 0, 1] = luebeckConwayPolynomial_863_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_863_3_irreducible

theorem ofCoeffs_877_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 877 [2, 873, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_877_2
  change luebeckConwayPolynomialOfCoeffs 877 [2, 873, 1] = luebeckConwayPolynomial_877_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_877_2_irreducible

theorem ofCoeffs_881_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 881 [878, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_881_1
  change luebeckConwayPolynomialOfCoeffs 881 [878, 1] = luebeckConwayPolynomial_881_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_881_1_irreducible

theorem ofCoeffs_881_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 881 [878, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_881_3
  change luebeckConwayPolynomialOfCoeffs 881 [878, 1, 0, 1] = luebeckConwayPolynomial_881_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_881_3_irreducible

theorem ofCoeffs_883_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 883 [2, 879, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_883_2
  change luebeckConwayPolynomialOfCoeffs 883 [2, 879, 1] = luebeckConwayPolynomial_883_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_883_2_irreducible

theorem ofCoeffs_887_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 887 [882, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_887_1
  change luebeckConwayPolynomialOfCoeffs 887 [882, 1] = luebeckConwayPolynomial_887_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_887_1_irreducible

theorem ofCoeffs_887_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 887 [882, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_887_3
  change luebeckConwayPolynomialOfCoeffs 887 [882, 1, 0, 1] = luebeckConwayPolynomial_887_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_887_3_irreducible

theorem ofCoeffs_907_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 907 [2, 903, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_907_2
  change luebeckConwayPolynomialOfCoeffs 907 [2, 903, 1] = luebeckConwayPolynomial_907_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_907_2_irreducible

theorem ofCoeffs_911_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 911 [894, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_911_1
  change luebeckConwayPolynomialOfCoeffs 911 [894, 1] = luebeckConwayPolynomial_911_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_911_1_irreducible

theorem ofCoeffs_911_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 911 [894, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_911_3
  change luebeckConwayPolynomialOfCoeffs 911 [894, 1, 0, 1] = luebeckConwayPolynomial_911_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_911_3_irreducible

theorem ofCoeffs_919_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 919 [7, 910, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_919_2
  change luebeckConwayPolynomialOfCoeffs 919 [7, 910, 1] = luebeckConwayPolynomial_919_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_919_2_irreducible

theorem ofCoeffs_929_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 929 [926, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_929_1
  change luebeckConwayPolynomialOfCoeffs 929 [926, 1] = luebeckConwayPolynomial_929_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_929_1_irreducible

theorem ofCoeffs_929_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 929 [926, 5, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_929_3
  change luebeckConwayPolynomialOfCoeffs 929 [926, 5, 0, 1] = luebeckConwayPolynomial_929_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_929_3_irreducible

theorem ofCoeffs_937_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 937 [5, 934, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_937_2
  change luebeckConwayPolynomialOfCoeffs 937 [5, 934, 1] = luebeckConwayPolynomial_937_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_937_2_irreducible

theorem ofCoeffs_941_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 941 [939, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_941_1
  change luebeckConwayPolynomialOfCoeffs 941 [939, 1] = luebeckConwayPolynomial_941_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_941_1_irreducible

theorem ofCoeffs_941_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 941 [939, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_941_3
  change luebeckConwayPolynomialOfCoeffs 941 [939, 3, 0, 1] = luebeckConwayPolynomial_941_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_941_3_irreducible

theorem ofCoeffs_947_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 947 [2, 943, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_947_2
  change luebeckConwayPolynomialOfCoeffs 947 [2, 943, 1] = luebeckConwayPolynomial_947_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_947_2_irreducible

theorem ofCoeffs_953_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 953 [950, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_953_1
  change luebeckConwayPolynomialOfCoeffs 953 [950, 1] = luebeckConwayPolynomial_953_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_953_1_irreducible

theorem ofCoeffs_953_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 953 [950, 7, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_953_3
  change luebeckConwayPolynomialOfCoeffs 953 [950, 7, 0, 1] = luebeckConwayPolynomial_953_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_953_3_irreducible


end Conway

end Hex
