/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Certificates
public import HexConway.Transport.S2_6

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

theorem ofCoeffs_431_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 431 [7, 430, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_431_2
  change luebeckConwayPolynomialOfCoeffs 431 [7, 430, 1] = luebeckConwayPolynomial_431_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_431_2_irreducible

theorem ofCoeffs_433_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 433 [428, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_433_1
  change luebeckConwayPolynomialOfCoeffs 433 [428, 1] = luebeckConwayPolynomial_433_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_433_1_irreducible

theorem ofCoeffs_433_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 433 [428, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_433_3
  change luebeckConwayPolynomialOfCoeffs 433 [428, 1, 0, 1] = luebeckConwayPolynomial_433_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_433_3_irreducible

theorem ofCoeffs_439_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 439 [15, 436, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_439_2
  change luebeckConwayPolynomialOfCoeffs 439 [15, 436, 1] = luebeckConwayPolynomial_439_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_439_2_irreducible

theorem ofCoeffs_443_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 443 [441, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_443_1
  change luebeckConwayPolynomialOfCoeffs 443 [441, 1] = luebeckConwayPolynomial_443_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_443_1_irreducible

theorem ofCoeffs_443_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 443 [441, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_443_3
  change luebeckConwayPolynomialOfCoeffs 443 [441, 4, 0, 1] = luebeckConwayPolynomial_443_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_443_3_irreducible

theorem ofCoeffs_449_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 449 [3, 444, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_449_2
  change luebeckConwayPolynomialOfCoeffs 449 [3, 444, 1] = luebeckConwayPolynomial_449_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_449_2_irreducible

theorem ofCoeffs_457_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 457 [444, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_457_1
  change luebeckConwayPolynomialOfCoeffs 457 [444, 1] = luebeckConwayPolynomial_457_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_457_1_irreducible

theorem ofCoeffs_457_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 457 [444, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_457_3
  change luebeckConwayPolynomialOfCoeffs 457 [444, 1, 0, 1] = luebeckConwayPolynomial_457_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_457_3_irreducible

theorem ofCoeffs_461_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 461 [2, 460, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_461_2
  change luebeckConwayPolynomialOfCoeffs 461 [2, 460, 1] = luebeckConwayPolynomial_461_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_461_2_irreducible

theorem ofCoeffs_463_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 463 [460, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_463_1
  change luebeckConwayPolynomialOfCoeffs 463 [460, 1] = luebeckConwayPolynomial_463_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_463_1_irreducible

theorem ofCoeffs_463_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 463 [460, 10, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_463_3
  change luebeckConwayPolynomialOfCoeffs 463 [460, 10, 0, 1] = luebeckConwayPolynomial_463_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_463_3_irreducible

theorem ofCoeffs_467_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 467 [2, 463, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_467_2
  change luebeckConwayPolynomialOfCoeffs 467 [2, 463, 1] = luebeckConwayPolynomial_467_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_467_2_irreducible

theorem ofCoeffs_479_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 479 [466, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_479_1
  change luebeckConwayPolynomialOfCoeffs 479 [466, 1] = luebeckConwayPolynomial_479_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_479_1_irreducible

theorem ofCoeffs_479_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 479 [466, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_479_3
  change luebeckConwayPolynomialOfCoeffs 479 [466, 4, 0, 1] = luebeckConwayPolynomial_479_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_479_3_irreducible

theorem ofCoeffs_487_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 487 [3, 485, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_487_2
  change luebeckConwayPolynomialOfCoeffs 487 [3, 485, 1] = luebeckConwayPolynomial_487_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_487_2_irreducible

theorem ofCoeffs_491_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 491 [489, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_491_1
  change luebeckConwayPolynomialOfCoeffs 491 [489, 1] = luebeckConwayPolynomial_491_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_491_1_irreducible

theorem ofCoeffs_491_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 491 [489, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_491_3
  change luebeckConwayPolynomialOfCoeffs 491 [489, 2, 0, 1] = luebeckConwayPolynomial_491_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_491_3_irreducible

theorem ofCoeffs_499_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 499 [7, 493, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_499_2
  change luebeckConwayPolynomialOfCoeffs 499 [7, 493, 1] = luebeckConwayPolynomial_499_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_499_2_irreducible

theorem ofCoeffs_503_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 503 [498, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_503_1
  change luebeckConwayPolynomialOfCoeffs 503 [498, 1] = luebeckConwayPolynomial_503_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_503_1_irreducible

theorem ofCoeffs_503_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 503 [498, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_503_3
  change luebeckConwayPolynomialOfCoeffs 503 [498, 2, 0, 1] = luebeckConwayPolynomial_503_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_503_3_irreducible

theorem ofCoeffs_509_2_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 509 [2, 508, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_509_2
  change luebeckConwayPolynomialOfCoeffs 509 [2, 508, 1] = luebeckConwayPolynomial_509_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_509_2_irreducible

theorem ofCoeffs_521_1_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 521 [518, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_521_1
  change luebeckConwayPolynomialOfCoeffs 521 [518, 1] = luebeckConwayPolynomial_521_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_521_1_irreducible

theorem ofCoeffs_521_3_irreducible :
    FpPoly.Irreducible (luebeckConwayPolynomialOfCoeffs 521 [518, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_521_3
  change luebeckConwayPolynomialOfCoeffs 521 [518, 4, 0, 1] = luebeckConwayPolynomial_521_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_521_3_irreducible


end Conway

end Hex
