/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Certificates
public import HexConway.Transport.S3_1

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

theorem ofCoeffs_61_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 61 [2, 60, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_61_2
  change luebeckConwayPolynomialOfCoeffs 61 [2, 60, 1] = luebeckConwayPolynomial_61_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_61_2_monic

theorem ofCoeffs_61_4_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 61 [2, 40, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_61_4
  change luebeckConwayPolynomialOfCoeffs 61 [2, 40, 3, 0, 1] = luebeckConwayPolynomial_61_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_61_4_monic

theorem ofCoeffs_67_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 67 [2, 63, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_67_2
  change luebeckConwayPolynomialOfCoeffs 67 [2, 63, 1] = luebeckConwayPolynomial_67_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_67_2_monic

theorem ofCoeffs_67_4_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 67 [2, 54, 8, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_67_4
  change luebeckConwayPolynomialOfCoeffs 67 [2, 54, 8, 0, 1] = luebeckConwayPolynomial_67_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_67_4_monic

theorem ofCoeffs_71_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 71 [7, 69, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_71_2
  change luebeckConwayPolynomialOfCoeffs 71 [7, 69, 1] = luebeckConwayPolynomial_71_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_71_2_monic

theorem ofCoeffs_71_4_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 71 [7, 41, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_71_4
  change luebeckConwayPolynomialOfCoeffs 71 [7, 41, 4, 0, 1] = luebeckConwayPolynomial_71_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_71_4_monic

theorem ofCoeffs_73_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 73 [5, 70, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_73_2
  change luebeckConwayPolynomialOfCoeffs 73 [5, 70, 1] = luebeckConwayPolynomial_73_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_73_2_monic

theorem ofCoeffs_73_4_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 73 [5, 56, 16, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_73_4
  change luebeckConwayPolynomialOfCoeffs 73 [5, 56, 16, 0, 1] = luebeckConwayPolynomial_73_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_73_4_monic

theorem ofCoeffs_79_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 79 [3, 78, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_79_2
  change luebeckConwayPolynomialOfCoeffs 79 [3, 78, 1] = luebeckConwayPolynomial_79_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_79_2_monic

theorem ofCoeffs_79_4_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 79 [3, 66, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_79_4
  change luebeckConwayPolynomialOfCoeffs 79 [3, 66, 2, 0, 1] = luebeckConwayPolynomial_79_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_79_4_monic

theorem ofCoeffs_83_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 83 [2, 82, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_83_2
  change luebeckConwayPolynomialOfCoeffs 83 [2, 82, 1] = luebeckConwayPolynomial_83_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_83_2_monic

theorem ofCoeffs_83_4_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 83 [2, 42, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_83_4
  change luebeckConwayPolynomialOfCoeffs 83 [2, 42, 4, 0, 1] = luebeckConwayPolynomial_83_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_83_4_monic

theorem ofCoeffs_89_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 89 [3, 82, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_89_2
  change luebeckConwayPolynomialOfCoeffs 89 [3, 82, 1] = luebeckConwayPolynomial_89_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_89_2_monic

theorem ofCoeffs_89_4_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 89 [3, 72, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_89_4
  change luebeckConwayPolynomialOfCoeffs 89 [3, 72, 4, 0, 1] = luebeckConwayPolynomial_89_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_89_4_monic

theorem ofCoeffs_97_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 97 [5, 96, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_97_2
  change luebeckConwayPolynomialOfCoeffs 97 [5, 96, 1] = luebeckConwayPolynomial_97_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_97_2_monic

theorem ofCoeffs_97_4_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 97 [5, 80, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_97_4
  change luebeckConwayPolynomialOfCoeffs 97 [5, 80, 6, 0, 1] = luebeckConwayPolynomial_97_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_97_4_monic

theorem ofCoeffs_101_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 101 [2, 97, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_101_2
  change luebeckConwayPolynomialOfCoeffs 101 [2, 97, 1] = luebeckConwayPolynomial_101_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_101_2_monic

theorem ofCoeffs_101_4_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 101 [2, 78, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_101_4
  change luebeckConwayPolynomialOfCoeffs 101 [2, 78, 1, 0, 1] = luebeckConwayPolynomial_101_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_101_4_monic

theorem ofCoeffs_103_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 103 [5, 102, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_103_2
  change luebeckConwayPolynomialOfCoeffs 103 [5, 102, 1] = luebeckConwayPolynomial_103_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_103_2_monic

theorem ofCoeffs_103_4_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 103 [5, 88, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_103_4
  change luebeckConwayPolynomialOfCoeffs 103 [5, 88, 2, 0, 1] = luebeckConwayPolynomial_103_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_103_4_monic

theorem ofCoeffs_107_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 107 [2, 103, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_107_2
  change luebeckConwayPolynomialOfCoeffs 107 [2, 103, 1] = luebeckConwayPolynomial_107_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_107_2_monic

theorem ofCoeffs_107_4_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 107 [2, 79, 13, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_107_4
  change luebeckConwayPolynomialOfCoeffs 107 [2, 79, 13, 0, 1] = luebeckConwayPolynomial_107_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_107_4_monic

theorem ofCoeffs_109_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 109 [6, 108, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_109_2
  change luebeckConwayPolynomialOfCoeffs 109 [6, 108, 1] = luebeckConwayPolynomial_109_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_109_2_monic

theorem ofCoeffs_109_4_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 109 [6, 98, 11, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_109_4
  change luebeckConwayPolynomialOfCoeffs 109 [6, 98, 11, 0, 1] = luebeckConwayPolynomial_109_4 at heq
  rw [heq]
  exact luebeckConwayPolynomial_109_4_monic


end Conway

end Hex
