/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.Certificates
public import HexConway.Transport.S3_7

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

theorem ofCoeffs_523_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 523 [2, 522, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_523_2
  change luebeckConwayPolynomialOfCoeffs 523 [2, 522, 1] = luebeckConwayPolynomial_523_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_523_2_monic

theorem ofCoeffs_541_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 541 [539, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_541_1
  change luebeckConwayPolynomialOfCoeffs 541 [539, 1] = luebeckConwayPolynomial_541_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_541_1_monic

theorem ofCoeffs_541_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 541 [539, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_541_3
  change luebeckConwayPolynomialOfCoeffs 541 [539, 2, 0, 1] = luebeckConwayPolynomial_541_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_541_3_monic

theorem ofCoeffs_547_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 547 [2, 543, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_547_2
  change luebeckConwayPolynomialOfCoeffs 547 [2, 543, 1] = luebeckConwayPolynomial_547_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_547_2_monic

theorem ofCoeffs_557_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 557 [555, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_557_1
  change luebeckConwayPolynomialOfCoeffs 557 [555, 1] = luebeckConwayPolynomial_557_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_557_1_monic

theorem ofCoeffs_557_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 557 [555, 3, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_557_3
  change luebeckConwayPolynomialOfCoeffs 557 [555, 3, 0, 1] = luebeckConwayPolynomial_557_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_557_3_monic

theorem ofCoeffs_563_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 563 [2, 559, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_563_2
  change luebeckConwayPolynomialOfCoeffs 563 [2, 559, 1] = luebeckConwayPolynomial_563_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_563_2_monic

theorem ofCoeffs_569_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 569 [566, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_569_1
  change luebeckConwayPolynomialOfCoeffs 569 [566, 1] = luebeckConwayPolynomial_569_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_569_1_monic

theorem ofCoeffs_569_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 569 [566, 4, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_569_3
  change luebeckConwayPolynomialOfCoeffs 569 [566, 4, 0, 1] = luebeckConwayPolynomial_569_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_569_3_monic

theorem ofCoeffs_571_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 571 [3, 570, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_571_2
  change luebeckConwayPolynomialOfCoeffs 571 [3, 570, 1] = luebeckConwayPolynomial_571_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_571_2_monic

theorem ofCoeffs_577_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 577 [572, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_577_1
  change luebeckConwayPolynomialOfCoeffs 577 [572, 1] = luebeckConwayPolynomial_577_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_577_1_monic

theorem ofCoeffs_577_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 577 [572, 2, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_577_3
  change luebeckConwayPolynomialOfCoeffs 577 [572, 2, 0, 1] = luebeckConwayPolynomial_577_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_577_3_monic

theorem ofCoeffs_587_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 587 [2, 583, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_587_2
  change luebeckConwayPolynomialOfCoeffs 587 [2, 583, 1] = luebeckConwayPolynomial_587_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_587_2_monic

theorem ofCoeffs_593_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 593 [590, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_593_1
  change luebeckConwayPolynomialOfCoeffs 593 [590, 1] = luebeckConwayPolynomial_593_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_593_1_monic

theorem ofCoeffs_593_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 593 [590, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_593_3
  change luebeckConwayPolynomialOfCoeffs 593 [590, 6, 0, 1] = luebeckConwayPolynomial_593_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_593_3_monic

theorem ofCoeffs_599_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 599 [7, 598, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_599_2
  change luebeckConwayPolynomialOfCoeffs 599 [7, 598, 1] = luebeckConwayPolynomial_599_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_599_2_monic

theorem ofCoeffs_601_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 601 [594, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_601_1
  change luebeckConwayPolynomialOfCoeffs 601 [594, 1] = luebeckConwayPolynomial_601_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_601_1_monic

theorem ofCoeffs_601_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 601 [594, 1, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_601_3
  change luebeckConwayPolynomialOfCoeffs 601 [594, 1, 0, 1] = luebeckConwayPolynomial_601_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_601_3_monic

theorem ofCoeffs_607_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 607 [3, 606, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_607_2
  change luebeckConwayPolynomialOfCoeffs 607 [3, 606, 1] = luebeckConwayPolynomial_607_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_607_2_monic

theorem ofCoeffs_613_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 613 [611, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_613_1
  change luebeckConwayPolynomialOfCoeffs 613 [611, 1] = luebeckConwayPolynomial_613_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_613_1_monic

theorem ofCoeffs_613_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 613 [611, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_613_3
  change luebeckConwayPolynomialOfCoeffs 613 [611, 6, 0, 1] = luebeckConwayPolynomial_613_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_613_3_monic

theorem ofCoeffs_617_2_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 617 [3, 612, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_617_2
  change luebeckConwayPolynomialOfCoeffs 617 [3, 612, 1] = luebeckConwayPolynomial_617_2 at heq
  rw [heq]
  exact luebeckConwayPolynomial_617_2_monic

theorem ofCoeffs_619_1_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 619 [617, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_619_1
  change luebeckConwayPolynomialOfCoeffs 619 [617, 1] = luebeckConwayPolynomial_619_1 at heq
  rw [heq]
  exact luebeckConwayPolynomial_619_1_monic

theorem ofCoeffs_619_3_monic :
    DensePoly.Monic (luebeckConwayPolynomialOfCoeffs 619 [617, 6, 0, 1]) := by
  have heq := Option.some.inj luebeckConwayPolynomial?_hit_619_3
  change luebeckConwayPolynomialOfCoeffs 619 [617, 6, 0, 1] = luebeckConwayPolynomial_619_3 at heq
  rw [heq]
  exact luebeckConwayPolynomial_619_3_monic


end Conway

end Hex
