/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.PrimitivityCore
public import HexConway.PrimeFactors
public import HexConway.PrimitiveProofs.S0_1

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- C(179, 3) has a generator of order 5735338. -/
theorem primitive_179_3 :
    Primitive 179 3 supportedEntry_179_3 [2, 7, 89, 4603] [1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_89
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_4603
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(223, 3) has a generator of order 11089566. -/
theorem primitive_223_3 :
    Primitive 223 3 supportedEntry_223_3 [2, 3, 37, 16651] [1, 2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_37
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_16651
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(251, 3) has a generator of order 15813250. -/
theorem primitive_251_3 :
    Primitive 251 3 supportedEntry_251_3 [2, 5, 43, 1471] [1, 3, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_43
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_1471
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(839, 3) has a generator of order 590589718. -/
theorem primitive_839_3 :
    Primitive 839 3 supportedEntry_839_3 [2, 419, 704761] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_419
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_704761
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(103, 3) has a generator of order 1092726. -/
theorem primitive_103_3 :
    Primitive 103 3 supportedEntry_103_3 [2, 3, 17, 3571] [1, 2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3571
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(257, 3) has a generator of order 16974592. -/
theorem primitive_257_3 :
    Primitive 257 3 supportedEntry_257_3 [2, 61, 1087] [8, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_61
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_1087
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(2, 7) has a generator of order 127. -/
theorem primitive_2_7 :
    Primitive 2 7 supportedEntry_2_7 [127] [1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_127
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(47, 3) has a generator of order 103822. -/
theorem primitive_47_3 :
    Primitive 47 3 supportedEntry_47_3 [2, 23, 37, 61] [1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_37
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_61
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(5, 4) has a generator of order 624. -/
theorem primitive_5_4 :
    Primitive 5 4 supportedEntry_5_4 [2, 3, 13] [4, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(89, 3) has a generator of order 704968. -/
theorem primitive_89_3 :
    Primitive 89 3 supportedEntry_89_3 [2, 11, 8011] [3, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_8011
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(29, 3) has a generator of order 24388. -/
theorem primitive_29_3 :
    Primitive 29 3 supportedEntry_29_3 [2, 7, 13, 67] [2, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_67
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(659, 2) has a generator of order 434280. -/
theorem primitive_659_2 :
    Primitive 659 2 supportedEntry_659_2 [2, 3, 5, 7, 11, 47] [3, 1, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_47
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(419, 2) has a generator of order 175560. -/
theorem primitive_419_2 :
    Primitive 419 2 supportedEntry_419_2 [2, 3, 5, 7, 11, 19] [3, 1, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(521, 2) has a generator of order 271440. -/
theorem primitive_521_2 :
    Primitive 521 2 supportedEntry_521_2 [2, 3, 5, 13, 29] [4, 2, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_29
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(601, 2) has a generator of order 361200. -/
theorem primitive_601_2 :
    Primitive 601 2 supportedEntry_601_2 [2, 3, 5, 7, 43] [4, 1, 2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_43
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(643, 2) has a generator of order 413448. -/
theorem primitive_643_2 :
    Primitive 643 2 supportedEntry_643_2 [2, 3, 7, 23, 107] [3, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_107
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(701, 2) has a generator of order 491400. -/
theorem primitive_701_2 :
    Primitive 701 2 supportedEntry_701_2 [2, 3, 5, 7, 13] [3, 3, 2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(743, 2) has a generator of order 552048. -/
theorem primitive_743_2 :
    Primitive 743 2 supportedEntry_743_2 [2, 3, 7, 31, 53] [4, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_31
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_53
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(811, 2) has a generator of order 657720. -/
theorem primitive_811_2 :
    Primitive 811 2 supportedEntry_811_2 [2, 3, 5, 7, 29] [3, 4, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_29
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(839, 2) has a generator of order 703920. -/
theorem primitive_839_2 :
    Primitive 839 2 supportedEntry_839_2 [2, 3, 5, 7, 419] [4, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_419
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(883, 2) has a generator of order 779688. -/
theorem primitive_883_2 :
    Primitive 883 2 supportedEntry_883_2 [2, 3, 7, 13, 17] [3, 2, 2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(941, 2) has a generator of order 885480. -/
theorem primitive_941_2 :
    Primitive 941 2 supportedEntry_941_2 [2, 3, 5, 47, 157] [3, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_47
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_157
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(991, 2) has a generator of order 982080. -/
theorem primitive_991_2 :
    Primitive 991 2 supportedEntry_991_2 [2, 3, 5, 11, 31] [6, 2, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_31
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(373, 2) has a generator of order 139128. -/
theorem primitive_373_2 :
    Primitive 373 2 supportedEntry_373_2 [2, 3, 11, 17, 31] [3, 1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_31
    exact absurd hq (by simp)
  check := by decide +kernel


end Conway

end Hex
