/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.PrimitivityCore
public import HexConway.PrimeFactors
public import HexConway.PrimitiveProofs.S1_3

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- C(7, 3) has a generator of order 342. -/
theorem primitive_7_3 :
    Primitive 7 3 supportedEntry_7_3 [2, 3, 19] [1, 2, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(863, 2) has a generator of order 744768. -/
theorem primitive_863_2 :
    Primitive 863 2 supportedEntry_863_2 [2, 3, 431] [6, 3, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_431
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(103, 2) has a generator of order 10608. -/
theorem primitive_103_2 :
    Primitive 103 2 supportedEntry_103_2 [2, 3, 13, 17] [4, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_17
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(383, 2) has a generator of order 146688. -/
theorem primitive_383_2 :
    Primitive 383 2 supportedEntry_383_2 [2, 3, 191] [8, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_191
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(59, 2) has a generator of order 3480. -/
theorem primitive_59_2 :
    Primitive 59 2 supportedEntry_59_2 [2, 3, 5, 29] [3, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_29
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(193, 2) has a generator of order 37248. -/
theorem primitive_193_2 :
    Primitive 193 2 supportedEntry_193_2 [2, 3, 97] [7, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_97
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(5, 3) has a generator of order 124. -/
theorem primitive_5_3 :
    Primitive 5 3 supportedEntry_5_3 [2, 31] [2, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_31
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(37, 2) has a generator of order 1368. -/
theorem primitive_37_2 :
    Primitive 37 2 supportedEntry_37_2 [2, 3, 19] [3, 2, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_19
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(19, 2) has a generator of order 360. -/
theorem primitive_19_2 :
    Primitive 19 2 supportedEntry_19_2 [2, 3, 5] [3, 2, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(11, 2) has a generator of order 120. -/
theorem primitive_11_2 :
    Primitive 11 2 supportedEntry_11_2 [2, 3, 5] [3, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(547, 1) has a generator of order 546. -/
theorem primitive_547_1 :
    Primitive 547 1 supportedEntry_547_1 [2, 3, 7, 13] [1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(691, 1) has a generator of order 690. -/
theorem primitive_691_1 :
    Primitive 691 1 supportedEntry_691_1 [2, 3, 5, 23] [1, 1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(991, 1) has a generator of order 990. -/
theorem primitive_991_1 :
    Primitive 991 1 supportedEntry_991_1 [2, 3, 5, 11] [1, 2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(521, 1) has a generator of order 520. -/
theorem primitive_521_1 :
    Primitive 521 1 supportedEntry_521_1 [2, 5, 13] [3, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(599, 1) has a generator of order 598. -/
theorem primitive_599_1 :
    Primitive 599 1 supportedEntry_599_1 [2, 13, 23] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(617, 1) has a generator of order 616. -/
theorem primitive_617_1 :
    Primitive 617 1 supportedEntry_617_1 [2, 7, 11] [3, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(659, 1) has a generator of order 658. -/
theorem primitive_659_1 :
    Primitive 659 1 supportedEntry_659_1 [2, 7, 47] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_47
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(709, 1) has a generator of order 708. -/
theorem primitive_709_1 :
    Primitive 709 1 supportedEntry_709_1 [2, 3, 59] [2, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_59
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(743, 1) has a generator of order 742. -/
theorem primitive_743_1 :
    Primitive 743 1 supportedEntry_743_1 [2, 7, 53] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_53
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(787, 1) has a generator of order 786. -/
theorem primitive_787_1 :
    Primitive 787 1 supportedEntry_787_1 [2, 3, 131] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_131
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(827, 1) has a generator of order 826. -/
theorem primitive_827_1 :
    Primitive 827 1 supportedEntry_827_1 [2, 7, 59] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_59
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(881, 1) has a generator of order 880. -/
theorem primitive_881_1 :
    Primitive 881 1 supportedEntry_881_1 [2, 5, 11] [4, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(937, 1) has a generator of order 936. -/
theorem primitive_937_1 :
    Primitive 937 1 supportedEntry_937_1 [2, 3, 13] [3, 2, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_13
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(971, 1) has a generator of order 970. -/
theorem primitive_971_1 :
    Primitive 971 1 supportedEntry_971_1 [2, 5, 97] [1, 1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_5
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_97
    exact absurd hq (by simp)
  check := by decide +kernel


end Conway

end Hex
