/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.PrimitivityCore
public import HexConway.PrimeFactors
public import HexConway.PrimitiveProofs.S1_5

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- C(113, 1) has a generator of order 112. -/
theorem primitive_113_1 :
    Primitive 113 1 supportedEntry_113_1 [2, 7] [4, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_7
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(59, 1) has a generator of order 58. -/
theorem primitive_59_1 :
    Primitive 59 1 supportedEntry_59_1 [2, 29] [1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_29
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(257, 1) has a generator of order 256. -/
theorem primitive_257_1 :
    Primitive 257 1 supportedEntry_257_1 [2] [8] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(13, 1) has a generator of order 12. -/
theorem primitive_13_1 :
    Primitive 13 1 supportedEntry_13_1 [2, 3] [2, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    exact absurd hq (by simp)
  check := by decide +kernel


end Conway

end Hex
