/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexConway.PrimitivityCore
public import HexConway.PrimeFactors
public import HexConway.PrimitiveProofs.S3_5

public section

/-! Generated by scripts/conway/generate.py from the committed scope and source data. -/

set_option maxRecDepth 1000000
set_option maxHeartbeats 80000000

namespace Hex
namespace Conway

/-- C(73, 1) has a generator of order 72. -/
theorem primitive_73_1 :
    Primitive 73 1 supportedEntry_73_1 [2, 3] [3, 2] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(83, 1) has a generator of order 82. -/
theorem primitive_83_1 :
    Primitive 83 1 supportedEntry_83_1 [2, 41] [1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_41
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(107, 1) has a generator of order 106. -/
theorem primitive_107_1 :
    Primitive 107 1 supportedEntry_107_1 [2, 53] [1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_53
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(47, 1) has a generator of order 46. -/
theorem primitive_47_1 :
    Primitive 47 1 supportedEntry_47_1 [2, 23] [1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_23
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(23, 1) has a generator of order 22. -/
theorem primitive_23_1 :
    Primitive 23 1 supportedEntry_23_1 [2, 11] [1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_11
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(7, 1) has a generator of order 6. -/
theorem primitive_7_1 :
    Primitive 7 1 supportedEntry_7_1 [2, 3] [1, 1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_3
    exact absurd hq (by simp)
  check := by decide +kernel

/-- C(3, 1) has a generator of order 2. -/
theorem primitive_3_1 :
    Primitive 3 1 supportedEntry_3_1 [2] [1] where
  primes := by
    intro q hq
    rcases List.mem_cons.mp hq with rfl | hq
    · exact factorPrime_2
    exact absurd hq (by simp)
  check := by decide +kernel


end Conway

end Hex
